
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045;

public class BitField16x16x1 implements BitField {
	public static final int WIDTH = 16;
	public static final int HEIGHT = 16;
	public static final int DEPTH = 1;
	protected long _0;
	protected long _1;
	protected long _2;
	protected long _3;

	public int getWidth() {
		return WIDTH;
	}
	public int getHeight() {
		return HEIGHT;
	}
	public int getDepth() {
		return DEPTH;
	}

	public boolean getValue(int x, int y, int z) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) return this.getValue0(position);
		assert false;
		return false;
	}
	protected boolean getValue0(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 64) return (this._0 & mask) != 0;
		if(position < 128) return (this._1 & mask) != 0;
		if(position < 192) return (this._2 & mask) != 0;
		if(position < 256) return (this._3 & mask) != 0;
		assert false;
		return false;
	}

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue0(position, v); return; }
		assert false;
	}
	protected void setValue0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		if(position < 128) { this._1 = (this._1 & mask) | value; return; }
		if(position < 192) { this._2 = (this._2 & mask) | value; return; }
		if(position < 256) { this._3 = (this._3 & mask) | value; return; }
		assert false;
	}

	public void offsetX(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {
		this.offsetPX4A();
	}
	protected void offsetPX4A() {
		this._0 = (this._0 & -4096L) | ((this._0 >> 4) & 4095L);
		this._0 = (this._0 & -268369921L) | ((this._0 >> 4) & 268369920L);
		this._0 = (this._0 & -17587891077121L) | ((this._0 >> 4) & 17587891077120L);
		this._0 = (this._0 & -1152640029630136321L) | ((this._0 >> 4) & 1152640029630136320L);
		this._1 = (this._1 & -4096L) | ((this._1 >> 4) & 4095L);
		this._1 = (this._1 & -268369921L) | ((this._1 >> 4) & 268369920L);
		this._1 = (this._1 & -17587891077121L) | ((this._1 >> 4) & 17587891077120L);
		this._1 = (this._1 & -1152640029630136321L) | ((this._1 >> 4) & 1152640029630136320L);
		this._2 = (this._2 & -4096L) | ((this._2 >> 4) & 4095L);
		this._2 = (this._2 & -268369921L) | ((this._2 >> 4) & 268369920L);
		this._2 = (this._2 & -17587891077121L) | ((this._2 >> 4) & 17587891077120L);
		this._2 = (this._2 & -1152640029630136321L) | ((this._2 >> 4) & 1152640029630136320L);
		this._3 = (this._3 & -4096L) | ((this._3 >> 4) & 4095L);
		this._3 = (this._3 & -268369921L) | ((this._3 >> 4) & 268369920L);
		this._3 = (this._3 & -17587891077121L) | ((this._3 >> 4) & 17587891077120L);
		this._3 = (this._3 & -1152640029630136321L) | ((this._3 >> 4) & 1152640029630136320L);
	}
	protected void offsetPX2() {
		this.offsetPX2A();
	}
	protected void offsetPX2A() {
		this._0 = (this._0 & -16384L) | ((this._0 >> 2) & 16383L);
		this._0 = (this._0 & -1073676289L) | ((this._0 >> 2) & 1073676288L);
		this._0 = (this._0 & -70364449210369L) | ((this._0 >> 2) & 70364449210368L);
		this._0 = (this._0 & -4611404543450677249L) | ((this._0 >> 2) & 4611404543450677248L);
		this._1 = (this._1 & -16384L) | ((this._1 >> 2) & 16383L);
		this._1 = (this._1 & -1073676289L) | ((this._1 >> 2) & 1073676288L);
		this._1 = (this._1 & -70364449210369L) | ((this._1 >> 2) & 70364449210368L);
		this._1 = (this._1 & -4611404543450677249L) | ((this._1 >> 2) & 4611404543450677248L);
		this._2 = (this._2 & -16384L) | ((this._2 >> 2) & 16383L);
		this._2 = (this._2 & -1073676289L) | ((this._2 >> 2) & 1073676288L);
		this._2 = (this._2 & -70364449210369L) | ((this._2 >> 2) & 70364449210368L);
		this._2 = (this._2 & -4611404543450677249L) | ((this._2 >> 2) & 4611404543450677248L);
		this._3 = (this._3 & -16384L) | ((this._3 >> 2) & 16383L);
		this._3 = (this._3 & -1073676289L) | ((this._3 >> 2) & 1073676288L);
		this._3 = (this._3 & -70364449210369L) | ((this._3 >> 2) & 70364449210368L);
		this._3 = (this._3 & -4611404543450677249L) | ((this._3 >> 2) & 4611404543450677248L);
	}
	protected void offsetPX1() {
		this.offsetPX1A();
	}
	protected void offsetPX1A() {
		this._0 = (this._0 & -32768L) | ((this._0 >> 1) & 32767L);
		this._0 = (this._0 & -2147418113L) | ((this._0 >> 1) & 2147418112L);
		this._0 = (this._0 & -140733193388033L) | ((this._0 >> 1) & 140733193388032L);
		this._0 = (this._0 & -9223090561878065153L) | ((this._0 >> 1) & 9223090561878065152L);
		this._1 = (this._1 & -32768L) | ((this._1 >> 1) & 32767L);
		this._1 = (this._1 & -2147418113L) | ((this._1 >> 1) & 2147418112L);
		this._1 = (this._1 & -140733193388033L) | ((this._1 >> 1) & 140733193388032L);
		this._1 = (this._1 & -9223090561878065153L) | ((this._1 >> 1) & 9223090561878065152L);
		this._2 = (this._2 & -32768L) | ((this._2 >> 1) & 32767L);
		this._2 = (this._2 & -2147418113L) | ((this._2 >> 1) & 2147418112L);
		this._2 = (this._2 & -140733193388033L) | ((this._2 >> 1) & 140733193388032L);
		this._2 = (this._2 & -9223090561878065153L) | ((this._2 >> 1) & 9223090561878065152L);
		this._3 = (this._3 & -32768L) | ((this._3 >> 1) & 32767L);
		this._3 = (this._3 & -2147418113L) | ((this._3 >> 1) & 2147418112L);
		this._3 = (this._3 & -140733193388033L) | ((this._3 >> 1) & 140733193388032L);
		this._3 = (this._3 & -9223090561878065153L) | ((this._3 >> 1) & 9223090561878065152L);
	}
	protected void offsetNX4() {
		this.offsetNX4A();
	}
	protected void offsetNX4A() {
		this._0 = (this._0 & -65521L) | ((this._0 << 4) & 65520L);
		this._0 = (this._0 & -4293918721L) | ((this._0 << 4) & 4293918720L);
		this._0 = (this._0 & -281406257233921L) | ((this._0 << 4) & 281406257233920L);
		this._0 = (this._0 & 4503599627370495L) | ((this._0 << 4) & -4503599627370496L);
		this._1 = (this._1 & -65521L) | ((this._1 << 4) & 65520L);
		this._1 = (this._1 & -4293918721L) | ((this._1 << 4) & 4293918720L);
		this._1 = (this._1 & -281406257233921L) | ((this._1 << 4) & 281406257233920L);
		this._1 = (this._1 & 4503599627370495L) | ((this._1 << 4) & -4503599627370496L);
		this._2 = (this._2 & -65521L) | ((this._2 << 4) & 65520L);
		this._2 = (this._2 & -4293918721L) | ((this._2 << 4) & 4293918720L);
		this._2 = (this._2 & -281406257233921L) | ((this._2 << 4) & 281406257233920L);
		this._2 = (this._2 & 4503599627370495L) | ((this._2 << 4) & -4503599627370496L);
		this._3 = (this._3 & -65521L) | ((this._3 << 4) & 65520L);
		this._3 = (this._3 & -4293918721L) | ((this._3 << 4) & 4293918720L);
		this._3 = (this._3 & -281406257233921L) | ((this._3 << 4) & 281406257233920L);
		this._3 = (this._3 & 4503599627370495L) | ((this._3 << 4) & -4503599627370496L);
	}
	protected void offsetNX2() {
		this.offsetNX2A();
	}
	protected void offsetNX2A() {
		this._0 = (this._0 & -65533L) | ((this._0 << 2) & 65532L);
		this._0 = (this._0 & -4294705153L) | ((this._0 << 2) & 4294705152L);
		this._0 = (this._0 & -281457796841473L) | ((this._0 << 2) & 281457796841472L);
		this._0 = (this._0 & 1125899906842623L) | ((this._0 << 2) & -1125899906842624L);
		this._1 = (this._1 & -65533L) | ((this._1 << 2) & 65532L);
		this._1 = (this._1 & -4294705153L) | ((this._1 << 2) & 4294705152L);
		this._1 = (this._1 & -281457796841473L) | ((this._1 << 2) & 281457796841472L);
		this._1 = (this._1 & 1125899906842623L) | ((this._1 << 2) & -1125899906842624L);
		this._2 = (this._2 & -65533L) | ((this._2 << 2) & 65532L);
		this._2 = (this._2 & -4294705153L) | ((this._2 << 2) & 4294705152L);
		this._2 = (this._2 & -281457796841473L) | ((this._2 << 2) & 281457796841472L);
		this._2 = (this._2 & 1125899906842623L) | ((this._2 << 2) & -1125899906842624L);
		this._3 = (this._3 & -65533L) | ((this._3 << 2) & 65532L);
		this._3 = (this._3 & -4294705153L) | ((this._3 << 2) & 4294705152L);
		this._3 = (this._3 & -281457796841473L) | ((this._3 << 2) & 281457796841472L);
		this._3 = (this._3 & 1125899906842623L) | ((this._3 << 2) & -1125899906842624L);
	}
	protected void offsetNX1() {
		this.offsetNX1A();
	}
	protected void offsetNX1A() {
		this._0 = (this._0 & -65535L) | ((this._0 << 1) & 65534L);
		this._0 = (this._0 & -4294836225L) | ((this._0 << 1) & 4294836224L);
		this._0 = (this._0 & -281466386776065L) | ((this._0 << 1) & 281466386776064L);
		this._0 = (this._0 & 562949953421311L) | ((this._0 << 1) & -562949953421312L);
		this._1 = (this._1 & -65535L) | ((this._1 << 1) & 65534L);
		this._1 = (this._1 & -4294836225L) | ((this._1 << 1) & 4294836224L);
		this._1 = (this._1 & -281466386776065L) | ((this._1 << 1) & 281466386776064L);
		this._1 = (this._1 & 562949953421311L) | ((this._1 << 1) & -562949953421312L);
		this._2 = (this._2 & -65535L) | ((this._2 << 1) & 65534L);
		this._2 = (this._2 & -4294836225L) | ((this._2 << 1) & 4294836224L);
		this._2 = (this._2 & -281466386776065L) | ((this._2 << 1) & 281466386776064L);
		this._2 = (this._2 & 562949953421311L) | ((this._2 << 1) & -562949953421312L);
		this._3 = (this._3 & -65535L) | ((this._3 << 1) & 65534L);
		this._3 = (this._3 & -4294836225L) | ((this._3 << 1) & 4294836224L);
		this._3 = (this._3 & -281466386776065L) | ((this._3 << 1) & 281466386776064L);
		this._3 = (this._3 & 562949953421311L) | ((this._3 << 1) & -562949953421312L);
	}

	public void offsetY(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {
		this.offsetPY4A();
	}
	protected void offsetPY4A() {
		this._1 = (this._1 & 0L) | (this._0 & -1L);
		this._2 = (this._2 & 0L) | (this._1 & -1L);
		this._3 = (this._3 & 0L) | (this._2 & -1L);
	}
	protected void offsetPY2() {
		this.offsetPY2A();
	}
	protected void offsetPY2A() {
		this._1 = (this._1 & -4294967296L) | ((this._0 >> 32) & 4294967295L);
		this._1 = (this._1 & 4294967295L) | ((this._1 << 32) & -4294967296L);
		this._2 = (this._2 & -4294967296L) | ((this._1 >> 32) & 4294967295L);
		this._2 = (this._2 & 4294967295L) | ((this._2 << 32) & -4294967296L);
		this._3 = (this._3 & -4294967296L) | ((this._2 >> 32) & 4294967295L);
	}
	protected void offsetPY1() {
		this.offsetPY1A();
	}
	protected void offsetPY1A() {
		this._1 = (this._1 & -65536L) | ((this._0 >> 48) & 65535L);
		this._1 = (this._1 & 65535L) | ((this._1 << 16) & -65536L);
		this._2 = (this._2 & -65536L) | ((this._1 >> 48) & 65535L);
		this._2 = (this._2 & 65535L) | ((this._2 << 16) & -65536L);
		this._3 = (this._3 & -65536L) | ((this._2 >> 48) & 65535L);
	}
	protected void offsetNY4() {
		this.offsetNY4A();
	}
	protected void offsetNY4A() {
		this._0 = (this._0 & 0L) | (this._1 & -1L);
		this._1 = (this._1 & 0L) | (this._2 & -1L);
		this._2 = (this._2 & 0L) | (this._3 & -1L);
	}
	protected void offsetNY2() {
		this.offsetNY2A();
	}
	protected void offsetNY2A() {
		this._0 = (this._0 & 4294967295L) | ((this._1 << 32) & -4294967296L);
		this._1 = (this._1 & -4294967296L) | ((this._1 >> 32) & 4294967295L);
		this._1 = (this._1 & 4294967295L) | ((this._2 << 32) & -4294967296L);
		this._2 = (this._2 & -4294967296L) | ((this._2 >> 32) & 4294967295L);
		this._2 = (this._2 & 4294967295L) | ((this._3 << 32) & -4294967296L);
	}
	protected void offsetNY1() {
		this.offsetNY1A();
	}
	protected void offsetNY1A() {
		this._0 = (this._0 & 281474976710655L) | ((this._1 << 48) & -281474976710656L);
		this._1 = (this._1 & -281474976710656L) | ((this._1 >> 16) & 281474976710655L);
		this._1 = (this._1 & 281474976710655L) | ((this._2 << 48) & -281474976710656L);
		this._2 = (this._2 & -281474976710656L) | ((this._2 >> 16) & 281474976710655L);
		this._2 = (this._2 & 281474976710655L) | ((this._3 << 48) & -281474976710656L);
	}

	public void offsetZ(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {

	}

	protected void offsetPZ2() {

	}

	protected void offsetPZ1() {

	}

	protected void offsetNZ4() {

	}

	protected void offsetNZ2() {

	}

	protected void offsetNZ1() {

	}


	public void complement() {
		this.complement0();
	}
	protected void complement0() {
		this._0 = ~this._0;
		this._1 = ~this._1;
		this._2 = ~this._2;
		this._3 = ~this._3;
	}

	public boolean isIntersecting(BitField that0) {
		if(!(that0 instanceof BitField16x16x1))
			return BitField.super.isIntersecting(that0);
		var that = (BitField16x16x1) that0;
		if(this.isIntersecting0(that)) return true;
		return false;
	}
	protected boolean isIntersecting0(BitField16x16x1 that) {
		if((this._0 & that._0) != 0) return true;
		if((this._1 & that._1) != 0) return true;
		if((this._2 & that._2) != 0) return true;
		if((this._3 & that._3) != 0) return true;
		return false;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField16x16x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1) that0;
		this.union0(that);
	}
	protected void union0(BitField16x16x1 that) {
		this._0 |= that._0;
		this._1 |= that._1;
		this._2 |= that._2;
		this._3 |= that._3;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField16x16x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1) that0;
		this.intersect0(that);
	}
	protected void intersect0(BitField16x16x1 that) {
		this._0 &= that._0;
		this._1 &= that._1;
		this._2 &= that._2;
		this._3 &= that._3;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField16x16x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1) that0;
		this.exclusive0(that);
	}
	protected void exclusive0(BitField16x16x1 that) {
		this._0 ^= that._0;
		this._1 ^= that._1;
		this._2 ^= that._2;
		this._3 ^= that._3;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField16x16x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1) that0;
		this.subtract0(that);
	}
	protected void subtract0(BitField16x16x1 that) {
		this._0 &= ~that._0;
		this._1 &= ~that._1;
		this._2 &= ~that._2;
		this._3 &= ~that._3;
	}
}
