
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045;

public class BitField12x12x12 extends BitField {
	public static final int WIDTH = 12;
	public static final int HEIGHT = 12;
	public static final int DEPTH = 12;
	protected long _0;
	protected long _1;
	protected long _2;
	protected long _3;
	protected long _4;
	protected long _5;
	protected long _6;
	protected long _7;
	protected long _8;
	protected long _9;
	protected long _10;
	protected long _11;
	protected long _12;
	protected long _13;
	protected long _14;
	protected long _15;
	protected long _16;
	protected long _17;
	protected long _18;
	protected long _19;
	protected long _20;
	protected long _21;
	protected long _22;
	protected long _23;
	protected long _24;
	protected long _25;
	protected long _26;

	public int getWidth() {
		return WIDTH;
	}
	public int getHeight() {
		return HEIGHT;
	}
	public int getDepth() {
		return DEPTH;
	}

	public boolean getValue(int x, int y, int z) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) return this.getValue_0(position);
		if(position < 2048) return this.getValue_1(position);
		assert false;
		return false;
	}
	protected boolean getValue_0(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 64) return (this._0 & mask) != 0;
		if(position < 128) return (this._1 & mask) != 0;
		if(position < 192) return (this._2 & mask) != 0;
		if(position < 256) return (this._3 & mask) != 0;
		if(position < 320) return (this._4 & mask) != 0;
		if(position < 384) return (this._5 & mask) != 0;
		if(position < 448) return (this._6 & mask) != 0;
		if(position < 512) return (this._7 & mask) != 0;
		if(position < 576) return (this._8 & mask) != 0;
		if(position < 640) return (this._9 & mask) != 0;
		if(position < 704) return (this._10 & mask) != 0;
		if(position < 768) return (this._11 & mask) != 0;
		if(position < 832) return (this._12 & mask) != 0;
		if(position < 896) return (this._13 & mask) != 0;
		if(position < 960) return (this._14 & mask) != 0;
		if(position < 1024) return (this._15 & mask) != 0;
		assert false;
		return false;
	}
	protected boolean getValue_1(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 1088) return (this._16 & mask) != 0;
		if(position < 1152) return (this._17 & mask) != 0;
		if(position < 1216) return (this._18 & mask) != 0;
		if(position < 1280) return (this._19 & mask) != 0;
		if(position < 1344) return (this._20 & mask) != 0;
		if(position < 1408) return (this._21 & mask) != 0;
		if(position < 1472) return (this._22 & mask) != 0;
		if(position < 1536) return (this._23 & mask) != 0;
		if(position < 1600) return (this._24 & mask) != 0;
		if(position < 1664) return (this._25 & mask) != 0;
		if(position < 1728) return (this._26 & mask) != 0;
		assert false;
		return false;
	}

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue_0(position, v); return; }
		if(position < 2048) { this.setValue_1(position, v); return; }
		assert false;
	}
	protected void setValue_0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		if(position < 128) { this._1 = (this._1 & mask) | value; return; }
		if(position < 192) { this._2 = (this._2 & mask) | value; return; }
		if(position < 256) { this._3 = (this._3 & mask) | value; return; }
		if(position < 320) { this._4 = (this._4 & mask) | value; return; }
		if(position < 384) { this._5 = (this._5 & mask) | value; return; }
		if(position < 448) { this._6 = (this._6 & mask) | value; return; }
		if(position < 512) { this._7 = (this._7 & mask) | value; return; }
		if(position < 576) { this._8 = (this._8 & mask) | value; return; }
		if(position < 640) { this._9 = (this._9 & mask) | value; return; }
		if(position < 704) { this._10 = (this._10 & mask) | value; return; }
		if(position < 768) { this._11 = (this._11 & mask) | value; return; }
		if(position < 832) { this._12 = (this._12 & mask) | value; return; }
		if(position < 896) { this._13 = (this._13 & mask) | value; return; }
		if(position < 960) { this._14 = (this._14 & mask) | value; return; }
		if(position < 1024) { this._15 = (this._15 & mask) | value; return; }
		assert false;
	}
	protected void setValue_1(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 1088) { this._16 = (this._16 & mask) | value; return; }
		if(position < 1152) { this._17 = (this._17 & mask) | value; return; }
		if(position < 1216) { this._18 = (this._18 & mask) | value; return; }
		if(position < 1280) { this._19 = (this._19 & mask) | value; return; }
		if(position < 1344) { this._20 = (this._20 & mask) | value; return; }
		if(position < 1408) { this._21 = (this._21 & mask) | value; return; }
		if(position < 1472) { this._22 = (this._22 & mask) | value; return; }
		if(position < 1536) { this._23 = (this._23 & mask) | value; return; }
		if(position < 1600) { this._24 = (this._24 & mask) | value; return; }
		if(position < 1664) { this._25 = (this._25 & mask) | value; return; }
		if(position < 1728) { this._26 = (this._26 & mask) | value; return; }
		assert false;
	}

	public void set(BitField that0) {
		if(!(that0 instanceof BitField12x12x12)) {
			super.set(that0);
			return;
		}
		var that = (BitField12x12x12) that0;
		this.set_0(that);
		this.set_1(that);
	}
	protected void set_0(BitField12x12x12 that) {
		this._0 = that._0;
		this._1 = that._1;
		this._2 = that._2;
		this._3 = that._3;
		this._4 = that._4;
		this._5 = that._5;
		this._6 = that._6;
		this._7 = that._7;
		this._8 = that._8;
		this._9 = that._9;
		this._10 = that._10;
		this._11 = that._11;
		this._12 = that._12;
		this._13 = that._13;
		this._14 = that._14;
		this._15 = that._15;
	}
	protected void set_1(BitField12x12x12 that) {
		this._16 = that._16;
		this._17 = that._17;
		this._18 = that._18;
		this._19 = that._19;
		this._20 = that._20;
		this._21 = that._21;
		this._22 = that._22;
		this._23 = that._23;
		this._24 = that._24;
		this._25 = that._25;
		this._26 = that._26;
	}

	public void clear() {
		this.clear_0();
		this.clear_1();
	}
	protected void clear_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
		this._4 = 0;
		this._5 = 0;
		this._6 = 0;
		this._7 = 0;
		this._8 = 0;
		this._9 = 0;
		this._10 = 0;
		this._11 = 0;
		this._12 = 0;
		this._13 = 0;
		this._14 = 0;
		this._15 = 0;
	}
	protected void clear_1() {
		this._16 = 0;
		this._17 = 0;
		this._18 = 0;
		this._19 = 0;
		this._20 = 0;
		this._21 = 0;
		this._22 = 0;
		this._23 = 0;
		this._24 = 0;
		this._25 = 0;
		this._26 = 0;
	}

	public BitField12x12x12 clone() {
		var result = new BitField12x12x12();
		result.set(this);
		return result;
	}

	public void offsetX(int amount) {
		amount = Math.max(-WIDTH, Math.min(WIDTH, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {
		long _22 = this._22;
		long _13 = this._13;
		long _4 = this._4;
		long _21 = this._21;
		long _12 = this._12;
		long _3 = this._3;
		long _18 = this._18;
		long _9 = this._9;
		long _0 = this._0;
		long _24 = this._24;
		long _15 = this._15;
		long _6 = this._6;
		this.offsetPX4_0(_22, _13, _4, _21, _12, _3, _18, _9, _0, _24, _15, _6);
		this.offsetPX4_1();
	}
	protected void offsetPX4_0(long _22, long _13, long _4, long _21, long _12, long _3, long _18, long _9, long _0, long _24, long _15, long _6) {
		this._26 = (this._26 & -71793646807019776L) | ((this._26 & 1148698348912316400L) >> 4);
		this._24 = (this._24 & -1148698348912316401L) | ((this._24 & -67570491112489216L) >> 4);
		this._22 = (this._22 & -1085351013494357776L) | ((this._22 & -1081127857799827216L) >> 4);
		this._20 = (this._20 & -71793646807019776L) | ((this._20 & 1148698348912316400L) >> 4);
		this._17 = (this._17 & -71793646807019776L) | ((this._17 & 1148698348912316400L) >> 4);
		this._15 = (this._15 & -1148698348912316401L) | ((this._15 & -67570491112489216L) >> 4);
		this._13 = (this._13 & -1085351013494357776L) | ((this._13 & -1081127857799827216L) >> 4);
		this._11 = (this._11 & -71793646807019776L) | ((this._11 & 1148698348912316400L) >> 4);
		this._8 = (this._8 & -71793646807019776L) | ((this._8 & 1148698348912316400L) >> 4);
		this._6 = (this._6 & -1148698348912316401L) | ((this._6 & -67570491112489216L) >> 4);
		this._4 = (this._4 & -1085351013494357776L) | ((this._4 & -1081127857799827216L) >> 4);
		this._2 = (this._2 & -71793646807019776L) | ((this._2 & 1148698348912316400L) >> 4);
		this._20 = (this._20 & 1152921504606846975L) | ((this._19 & 15L) << 60);
		this._11 = (this._11 & 1152921504606846975L) | ((this._10 & 15L) << 60);
		this._2 = (this._2 & 1152921504606846975L) | ((this._1 & 15L) << 60);
		this._19 = (this._19 & -1085351013494357776L) | ((this._19 & -1081127857799827216L) >> 4);
		this._10 = (this._10 & -1085351013494357776L) | ((this._10 & -1081127857799827216L) >> 4);
		this._1 = (this._1 & -1085351013494357776L) | ((this._1 & -1081127857799827216L) >> 4);
		this._21 = (this._21 & -1148698348912316401L) | ((this._21 & -67570491112489216L) >> 4);
		this._12 = (this._12 & -1148698348912316401L) | ((this._12 & -67570491112489216L) >> 4);
		this._3 = (this._3 & -1148698348912316401L) | ((this._3 & -67570491112489216L) >> 4);
		this._23 = (this._23 & -71793646807019776L) | ((this._23 & 1148698348912316400L) >> 4);
		this._14 = (this._14 & -71793646807019776L) | ((this._14 & 1148698348912316400L) >> 4);
		this._5 = (this._5 & -71793646807019776L) | ((this._5 & 1148698348912316400L) >> 4);
		this._26 = (this._26 & 1152921504606846975L) | ((this._25 & 15L) << 60);
		this._17 = (this._17 & 1152921504606846975L) | ((this._16 & 15L) << 60);
		this._8 = (this._8 & 1152921504606846975L) | ((this._7 & 15L) << 60);
		this._25 = (this._25 & -1085351013494357776L) | ((this._25 & -1081127857799827216L) >> 4);
		this._16 = (this._16 & -1085351013494357776L) | ((this._16 & -1081127857799827216L) >> 4);
		this._7 = (this._7 & -1085351013494357776L) | ((this._7 & -1081127857799827216L) >> 4);
		this._18 = (this._18 & -1148698348912316401L) | ((this._18 & -67570491112489216L) >> 4);
		this._9 = (this._9 & -1148698348912316401L) | ((this._9 & -67570491112489216L) >> 4);
		this._0 = (this._0 & -1148698348912316401L) | ((this._0 & -67570491112489216L) >> 4);
		this._23 = (this._23 & 1152921504606846975L) | ((_22 & 15L) << 60);
		this._14 = (this._14 & 1152921504606846975L) | ((_13 & 15L) << 60);
		this._5 = (this._5 & 1152921504606846975L) | ((_4 & 15L) << 60);
		this._22 = (this._22 & 1152921504606846975L) | ((_21 & 15L) << 60);
		this._13 = (this._13 & 1152921504606846975L) | ((_12 & 15L) << 60);
		this._4 = (this._4 & 1152921504606846975L) | ((_3 & 15L) << 60);
		this._19 = (this._19 & 1152921504606846975L) | ((_18 & 15L) << 60);
		this._10 = (this._10 & 1152921504606846975L) | ((_9 & 15L) << 60);
		this._1 = (this._1 & 1152921504606846975L) | ((_0 & 15L) << 60);
		this._25 = (this._25 & 1152921504606846975L) | ((_24 & 15L) << 60);
		this._16 = (this._16 & 1152921504606846975L) | ((_15 & 15L) << 60);
		this._7 = (this._7 & 1152921504606846975L) | ((_6 & 15L) << 60);
		this._26 = this._26 & -1081127857799827201L;
		this._24 = this._24 & 1148698348912316400L;
		this._22 = this._22 & -67570491112489201L;
		this._20 = this._20 & -1081127857799827201L;
		this._17 = this._17 & -1081127857799827201L;
		this._15 = this._15 & 1148698348912316400L;
		this._13 = this._13 & -67570491112489201L;
		this._11 = this._11 & -1081127857799827201L;
		this._8 = this._8 & -1081127857799827201L;
		this._6 = this._6 & 1148698348912316400L;
		this._4 = this._4 & -67570491112489201L;
		this._2 = this._2 & -1081127857799827201L;
		this._19 = this._19 & -67570491112489201L;
		this._10 = this._10 & -67570491112489201L;
		this._1 = this._1 & -67570491112489201L;
		this._21 = this._21 & 1148698348912316400L;
		this._12 = this._12 & 1148698348912316400L;
		this._3 = this._3 & 1148698348912316400L;
		this._23 = this._23 & -1081127857799827201L;
	}
	protected void offsetPX4_1() {
		this._14 = this._14 & -1081127857799827201L;
		this._5 = this._5 & -1081127857799827201L;
		this._25 = this._25 & -67570491112489201L;
		this._16 = this._16 & -67570491112489201L;
		this._7 = this._7 & -67570491112489201L;
		this._18 = this._18 & 1148698348912316400L;
		this._9 = this._9 & 1148698348912316400L;
		this._0 = this._0 & 1148698348912316400L;
	}
	protected void offsetPX2() {
		long _6 = this._6;
		long _15 = this._15;
		long _24 = this._24;
		long _0 = this._0;
		long _9 = this._9;
		long _18 = this._18;
		long _3 = this._3;
		long _12 = this._12;
		long _21 = this._21;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _7 = this._7;
		long _16 = this._16;
		long _25 = this._25;
		long _1 = this._1;
		long _10 = this._10;
		long _19 = this._19;
		this.offsetPX2_0(_6, _15, _24, _0, _9, _18, _3, _12, _21, _4, _13, _22, _7, _16, _25, _1, _10, _19);
		this.offsetPX2_1();
	}
	protected void offsetPX2_0(long _6, long _15, long _24, long _0, long _9, long _18, long _3, long _12, long _21, long _4, long _13, long _22, long _7, long _16, long _25, long _1, long _10, long _19) {
		this._0 = (this._0 & -4608307493871763444L) | ((this._0 & -13514098222497844L) >> 2);
		this._2 = (this._2 & -3746783732187526144L) | ((this._2 & -3459609144959447044L) >> 2);
		this._4 = (this._4 & -4557629625537396544L) | ((this._4 & -216225571559965444L) >> 2);
		this._6 = (this._6 & -4608307493871763444L) | ((this._6 & -13514098222497844L) >> 2);
		this._9 = (this._9 & -4608307493871763444L) | ((this._9 & -13514098222497844L) >> 2);
		this._11 = (this._11 & -3746783732187526144L) | ((this._11 & -3459609144959447044L) >> 2);
		this._13 = (this._13 & -4557629625537396544L) | ((this._13 & -216225571559965444L) >> 2);
		this._15 = (this._15 & -4608307493871763444L) | ((this._15 & -13514098222497844L) >> 2);
		this._18 = (this._18 & -4608307493871763444L) | ((this._18 & -13514098222497844L) >> 2);
		this._20 = (this._20 & -3746783732187526144L) | ((this._20 & -3459609144959447044L) >> 2);
		this._22 = (this._22 & -4557629625537396544L) | ((this._22 & -216225571559965444L) >> 2);
		this._24 = (this._24 & -4608307493871763444L) | ((this._24 & -13514098222497844L) >> 2);
		this._7 = (this._7 & -4557629625537396544L) | ((this._7 & -216225571559965444L) >> 2);
		this._16 = (this._16 & -4557629625537396544L) | ((this._16 & -216225571559965444L) >> 2);
		this._25 = (this._25 & -4557629625537396544L) | ((this._25 & -216225571559965444L) >> 2);
		this._5 = (this._5 & -3746783732187526144L) | ((this._5 & -3459609144959447044L) >> 2);
		this._14 = (this._14 & -3746783732187526144L) | ((this._14 & -3459609144959447044L) >> 2);
		this._23 = (this._23 & -3746783732187526144L) | ((this._23 & -3459609144959447044L) >> 2);
		this._3 = (this._3 & -4608307493871763444L) | ((this._3 & -13514098222497844L) >> 2);
		this._12 = (this._12 & -4608307493871763444L) | ((this._12 & -13514098222497844L) >> 2);
		this._21 = (this._21 & -4608307493871763444L) | ((this._21 & -13514098222497844L) >> 2);
		this._1 = (this._1 & -4557629625537396544L) | ((this._1 & -216225571559965444L) >> 2);
		this._10 = (this._10 & -4557629625537396544L) | ((this._10 & -216225571559965444L) >> 2);
		this._19 = (this._19 & -4557629625537396544L) | ((this._19 & -216225571559965444L) >> 2);
		this._8 = (this._8 & -3746783732187526144L) | ((this._8 & -3459609144959447044L) >> 2);
		this._17 = (this._17 & -3746783732187526144L) | ((this._17 & -3459609144959447044L) >> 2);
		this._26 = (this._26 & -3746783732187526144L) | ((this._26 & -3459609144959447044L) >> 2);
		this._7 = (this._7 & 4611686018427387903L) | ((_6 & 3L) << 62);
		this._16 = (this._16 & 4611686018427387903L) | ((_15 & 3L) << 62);
		this._25 = (this._25 & 4611686018427387903L) | ((_24 & 3L) << 62);
		this._1 = (this._1 & 4611686018427387903L) | ((_0 & 3L) << 62);
		this._10 = (this._10 & 4611686018427387903L) | ((_9 & 3L) << 62);
		this._19 = (this._19 & 4611686018427387903L) | ((_18 & 3L) << 62);
		this._4 = (this._4 & 4611686018427387903L) | ((_3 & 3L) << 62);
		this._13 = (this._13 & 4611686018427387903L) | ((_12 & 3L) << 62);
		this._22 = (this._22 & 4611686018427387903L) | ((_21 & 3L) << 62);
		this._5 = (this._5 & 4611686018427387903L) | ((_4 & 3L) << 62);
		this._14 = (this._14 & 4611686018427387903L) | ((_13 & 3L) << 62);
		this._23 = (this._23 & 4611686018427387903L) | ((_22 & 3L) << 62);
		this._8 = (this._8 & 4611686018427387903L) | ((_7 & 3L) << 62);
		this._17 = (this._17 & 4611686018427387903L) | ((_16 & 3L) << 62);
		this._26 = (this._26 & 4611686018427387903L) | ((_25 & 3L) << 62);
		this._2 = (this._2 & 4611686018427387903L) | ((_1 & 3L) << 62);
		this._11 = (this._11 & 4611686018427387903L) | ((_10 & 3L) << 62);
		this._20 = (this._20 & 4611686018427387903L) | ((_19 & 3L) << 62);
		this._0 = this._0 & 4608307493871763443L;
		this._2 = this._2 & -864902286239861761L;
		this._4 = this._4 & -54056392889991361L;
		this._6 = this._6 & 4608307493871763443L;
		this._9 = this._9 & 4608307493871763443L;
		this._11 = this._11 & -864902286239861761L;
		this._13 = this._13 & -54056392889991361L;
		this._15 = this._15 & 4608307493871763443L;
		this._18 = this._18 & 4608307493871763443L;
		this._20 = this._20 & -864902286239861761L;
		this._22 = this._22 & -54056392889991361L;
		this._24 = this._24 & 4608307493871763443L;
		this._7 = this._7 & -54056392889991361L;
		this._16 = this._16 & -54056392889991361L;
		this._25 = this._25 & -54056392889991361L;
		this._5 = this._5 & -864902286239861761L;
		this._14 = this._14 & -864902286239861761L;
		this._23 = this._23 & -864902286239861761L;
		this._3 = this._3 & 4608307493871763443L;
	}
	protected void offsetPX2_1() {
		this._12 = this._12 & 4608307493871763443L;
		this._21 = this._21 & 4608307493871763443L;
		this._1 = this._1 & -54056392889991361L;
		this._10 = this._10 & -54056392889991361L;
		this._19 = this._19 & -54056392889991361L;
		this._8 = this._8 & -864902286239861761L;
		this._17 = this._17 & -864902286239861761L;
		this._26 = this._26 & -864902286239861761L;
	}
	protected void offsetPX1() {
		long _6 = this._6;
		long _15 = this._15;
		long _24 = this._24;
		long _0 = this._0;
		long _9 = this._9;
		long _18 = this._18;
		long _3 = this._3;
		long _12 = this._12;
		long _21 = this._21;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _7 = this._7;
		long _16 = this._16;
		long _25 = this._25;
		long _1 = this._1;
		long _10 = this._10;
		long _19 = this._19;
		this.offsetPX1_0(_6, _15, _24, _0, _9, _18, _3, _12, _21, _4, _13, _22, _7, _16, _25, _1, _10, _19);
		this.offsetPX1_1();
	}
	protected void offsetPX1_0(long _6, long _15, long _24, long _0, long _9, long _18, long _3, long _12, long _21, long _4, long _13, long _22, long _7, long _16, long _25, long _1, long _10, long _19) {
		this._0 = (this._0 & -9221119687151026168L) | ((this._0 & -4504699407499282L) >> 1);
		this._2 = (this._2 & -8646770512694867968L) | ((this._2 & -1153203048319815682L) >> 1);
		this._4 = (this._4 & -9187334441594781568L) | ((this._4 & -72075190519988482L) >> 1);
		this._6 = (this._6 & -9221119687151026168L) | ((this._6 & -4504699407499282L) >> 1);
		this._9 = (this._9 & -9221119687151026168L) | ((this._9 & -4504699407499282L) >> 1);
		this._11 = (this._11 & -8646770512694867968L) | ((this._11 & -1153203048319815682L) >> 1);
		this._13 = (this._13 & -9187334441594781568L) | ((this._13 & -72075190519988482L) >> 1);
		this._15 = (this._15 & -9221119687151026168L) | ((this._15 & -4504699407499282L) >> 1);
		this._18 = (this._18 & -9221119687151026168L) | ((this._18 & -4504699407499282L) >> 1);
		this._20 = (this._20 & -8646770512694867968L) | ((this._20 & -1153203048319815682L) >> 1);
		this._22 = (this._22 & -9187334441594781568L) | ((this._22 & -72075190519988482L) >> 1);
		this._24 = (this._24 & -9221119687151026168L) | ((this._24 & -4504699407499282L) >> 1);
		this._7 = (this._7 & -9187334441594781568L) | ((this._7 & -72075190519988482L) >> 1);
		this._16 = (this._16 & -9187334441594781568L) | ((this._16 & -72075190519988482L) >> 1);
		this._25 = (this._25 & -9187334441594781568L) | ((this._25 & -72075190519988482L) >> 1);
		this._5 = (this._5 & -8646770512694867968L) | ((this._5 & -1153203048319815682L) >> 1);
		this._14 = (this._14 & -8646770512694867968L) | ((this._14 & -1153203048319815682L) >> 1);
		this._23 = (this._23 & -8646770512694867968L) | ((this._23 & -1153203048319815682L) >> 1);
		this._3 = (this._3 & -9221119687151026168L) | ((this._3 & -4504699407499282L) >> 1);
		this._12 = (this._12 & -9221119687151026168L) | ((this._12 & -4504699407499282L) >> 1);
		this._21 = (this._21 & -9221119687151026168L) | ((this._21 & -4504699407499282L) >> 1);
		this._1 = (this._1 & -9187334441594781568L) | ((this._1 & -72075190519988482L) >> 1);
		this._10 = (this._10 & -9187334441594781568L) | ((this._10 & -72075190519988482L) >> 1);
		this._19 = (this._19 & -9187334441594781568L) | ((this._19 & -72075190519988482L) >> 1);
		this._8 = (this._8 & -8646770512694867968L) | ((this._8 & -1153203048319815682L) >> 1);
		this._17 = (this._17 & -8646770512694867968L) | ((this._17 & -1153203048319815682L) >> 1);
		this._26 = (this._26 & -8646770512694867968L) | ((this._26 & -1153203048319815682L) >> 1);
		this._7 = (this._7 & 9223372036854775807L) | ((_6 & 1L) << 63);
		this._16 = (this._16 & 9223372036854775807L) | ((_15 & 1L) << 63);
		this._25 = (this._25 & 9223372036854775807L) | ((_24 & 1L) << 63);
		this._1 = (this._1 & 9223372036854775807L) | ((_0 & 1L) << 63);
		this._10 = (this._10 & 9223372036854775807L) | ((_9 & 1L) << 63);
		this._19 = (this._19 & 9223372036854775807L) | ((_18 & 1L) << 63);
		this._4 = (this._4 & 9223372036854775807L) | ((_3 & 1L) << 63);
		this._13 = (this._13 & 9223372036854775807L) | ((_12 & 1L) << 63);
		this._22 = (this._22 & 9223372036854775807L) | ((_21 & 1L) << 63);
		this._5 = (this._5 & 9223372036854775807L) | ((_4 & 1L) << 63);
		this._14 = (this._14 & 9223372036854775807L) | ((_13 & 1L) << 63);
		this._23 = (this._23 & 9223372036854775807L) | ((_22 & 1L) << 63);
		this._8 = (this._8 & 9223372036854775807L) | ((_7 & 1L) << 63);
		this._17 = (this._17 & 9223372036854775807L) | ((_16 & 1L) << 63);
		this._26 = (this._26 & 9223372036854775807L) | ((_25 & 1L) << 63);
		this._2 = (this._2 & 9223372036854775807L) | ((_1 & 1L) << 63);
		this._11 = (this._11 & 9223372036854775807L) | ((_10 & 1L) << 63);
		this._20 = (this._20 & 9223372036854775807L) | ((_19 & 1L) << 63);
		this._0 = this._0 & 9221119687151026167L;
		this._2 = this._2 & -576601524159907841L;
		this._4 = this._4 & -36037595259994241L;
		this._6 = this._6 & 9221119687151026167L;
		this._9 = this._9 & 9221119687151026167L;
		this._11 = this._11 & -576601524159907841L;
		this._13 = this._13 & -36037595259994241L;
		this._15 = this._15 & 9221119687151026167L;
		this._18 = this._18 & 9221119687151026167L;
		this._20 = this._20 & -576601524159907841L;
		this._22 = this._22 & -36037595259994241L;
		this._24 = this._24 & 9221119687151026167L;
		this._7 = this._7 & -36037595259994241L;
		this._16 = this._16 & -36037595259994241L;
		this._25 = this._25 & -36037595259994241L;
		this._5 = this._5 & -576601524159907841L;
		this._14 = this._14 & -576601524159907841L;
		this._23 = this._23 & -576601524159907841L;
		this._3 = this._3 & 9221119687151026167L;
	}
	protected void offsetPX1_1() {
		this._12 = this._12 & 9221119687151026167L;
		this._21 = this._21 & 9221119687151026167L;
		this._1 = this._1 & -36037595259994241L;
		this._10 = this._10 & -36037595259994241L;
		this._19 = this._19 & -36037595259994241L;
		this._8 = this._8 & -576601524159907841L;
		this._17 = this._17 & -576601524159907841L;
		this._26 = this._26 & -576601524159907841L;
	}
	protected void offsetNX4() {
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _5 = this._5;
		long _14 = this._14;
		long _23 = this._23;
		long _8 = this._8;
		long _17 = this._17;
		long _26 = this._26;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNX4_0(_4, _13, _22, _5, _14, _23, _8, _17, _26, _2, _11, _20);
		this.offsetNX4_1();
	}
	protected void offsetNX4_0(long _4, long _13, long _22, long _5, long _14, long _23, long _8, long _17, long _26, long _2, long _11, long _20) {
		this._0 = (this._0 & 67570491112489215L) | ((this._0 & 1148698348912316400L) << 4);
		this._2 = (this._2 & -1148698348912316401L) | ((this._2 & 71793646807019775L) << 4);
		this._4 = (this._4 & 1081127857799827215L) | ((this._4 & 1085351013494357775L) << 4);
		this._6 = (this._6 & 67570491112489215L) | ((this._6 & 1148698348912316400L) << 4);
		this._9 = (this._9 & 67570491112489215L) | ((this._9 & 1148698348912316400L) << 4);
		this._11 = (this._11 & -1148698348912316401L) | ((this._11 & 71793646807019775L) << 4);
		this._13 = (this._13 & 1081127857799827215L) | ((this._13 & 1085351013494357775L) << 4);
		this._15 = (this._15 & 67570491112489215L) | ((this._15 & 1148698348912316400L) << 4);
		this._18 = (this._18 & 67570491112489215L) | ((this._18 & 1148698348912316400L) << 4);
		this._20 = (this._20 & -1148698348912316401L) | ((this._20 & 71793646807019775L) << 4);
		this._22 = (this._22 & 1081127857799827215L) | ((this._22 & 1085351013494357775L) << 4);
		this._24 = (this._24 & 67570491112489215L) | ((this._24 & 1148698348912316400L) << 4);
		this._6 = (this._6 & -16L) | ((this._7 & -1152921504606846976L) >> 60);
		this._15 = (this._15 & -16L) | ((this._16 & -1152921504606846976L) >> 60);
		this._24 = (this._24 & -16L) | ((this._25 & -1152921504606846976L) >> 60);
		this._7 = (this._7 & 1081127857799827215L) | ((this._7 & 1085351013494357775L) << 4);
		this._16 = (this._16 & 1081127857799827215L) | ((this._16 & 1085351013494357775L) << 4);
		this._25 = (this._25 & 1081127857799827215L) | ((this._25 & 1085351013494357775L) << 4);
		this._5 = (this._5 & -1148698348912316401L) | ((this._5 & 71793646807019775L) << 4);
		this._14 = (this._14 & -1148698348912316401L) | ((this._14 & 71793646807019775L) << 4);
		this._23 = (this._23 & -1148698348912316401L) | ((this._23 & 71793646807019775L) << 4);
		this._3 = (this._3 & 67570491112489215L) | ((this._3 & 1148698348912316400L) << 4);
		this._12 = (this._12 & 67570491112489215L) | ((this._12 & 1148698348912316400L) << 4);
		this._21 = (this._21 & 67570491112489215L) | ((this._21 & 1148698348912316400L) << 4);
		this._0 = (this._0 & -16L) | ((this._1 & -1152921504606846976L) >> 60);
		this._9 = (this._9 & -16L) | ((this._10 & -1152921504606846976L) >> 60);
		this._18 = (this._18 & -16L) | ((this._19 & -1152921504606846976L) >> 60);
		this._1 = (this._1 & 1081127857799827215L) | ((this._1 & 1085351013494357775L) << 4);
		this._10 = (this._10 & 1081127857799827215L) | ((this._10 & 1085351013494357775L) << 4);
		this._19 = (this._19 & 1081127857799827215L) | ((this._19 & 1085351013494357775L) << 4);
		this._8 = (this._8 & -1148698348912316401L) | ((this._8 & 71793646807019775L) << 4);
		this._17 = (this._17 & -1148698348912316401L) | ((this._17 & 71793646807019775L) << 4);
		this._26 = (this._26 & -1148698348912316401L) | ((this._26 & 71793646807019775L) << 4);
		this._3 = (this._3 & -16L) | ((_4 & -1152921504606846976L) >> 60);
		this._12 = (this._12 & -16L) | ((_13 & -1152921504606846976L) >> 60);
		this._21 = (this._21 & -16L) | ((_22 & -1152921504606846976L) >> 60);
		this._4 = (this._4 & -16L) | ((_5 & -1152921504606846976L) >> 60);
		this._13 = (this._13 & -16L) | ((_14 & -1152921504606846976L) >> 60);
		this._22 = (this._22 & -16L) | ((_23 & -1152921504606846976L) >> 60);
		this._7 = (this._7 & -16L) | ((_8 & -1152921504606846976L) >> 60);
		this._16 = (this._16 & -16L) | ((_17 & -1152921504606846976L) >> 60);
		this._25 = (this._25 & -16L) | ((_26 & -1152921504606846976L) >> 60);
		this._1 = (this._1 & -16L) | ((_2 & -1152921504606846976L) >> 60);
		this._10 = (this._10 & -16L) | ((_11 & -1152921504606846976L) >> 60);
		this._19 = (this._19 & -16L) | ((_20 & -1152921504606846976L) >> 60);
		this._0 = this._0 & -67570491112489201L;
		this._2 = this._2 & 1148698348912316400L;
		this._4 = this._4 & -1081127857799827201L;
		this._6 = this._6 & -67570491112489201L;
		this._9 = this._9 & -67570491112489201L;
		this._11 = this._11 & 1148698348912316400L;
		this._13 = this._13 & -1081127857799827201L;
		this._15 = this._15 & -67570491112489201L;
		this._18 = this._18 & -67570491112489201L;
		this._20 = this._20 & 1148698348912316400L;
		this._22 = this._22 & -1081127857799827201L;
		this._24 = this._24 & -67570491112489201L;
		this._7 = this._7 & -1081127857799827201L;
		this._16 = this._16 & -1081127857799827201L;
		this._25 = this._25 & -1081127857799827201L;
		this._5 = this._5 & 1148698348912316400L;
		this._14 = this._14 & 1148698348912316400L;
		this._23 = this._23 & 1148698348912316400L;
		this._3 = this._3 & -67570491112489201L;
	}
	protected void offsetNX4_1() {
		this._12 = this._12 & -67570491112489201L;
		this._21 = this._21 & -67570491112489201L;
		this._1 = this._1 & -1081127857799827201L;
		this._10 = this._10 & -1081127857799827201L;
		this._19 = this._19 & -1081127857799827201L;
		this._8 = this._8 & 1148698348912316400L;
		this._17 = this._17 & 1148698348912316400L;
		this._26 = this._26 & 1148698348912316400L;
	}
	protected void offsetNX2() {
		long _7 = this._7;
		long _16 = this._16;
		long _25 = this._25;
		long _1 = this._1;
		long _10 = this._10;
		long _19 = this._19;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _5 = this._5;
		long _14 = this._14;
		long _23 = this._23;
		long _8 = this._8;
		long _17 = this._17;
		long _26 = this._26;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNX2_0(_7, _16, _25, _1, _10, _19, _4, _13, _22, _5, _14, _23, _8, _17, _26, _2, _11, _20);
		this.offsetNX2_1();
	}
	protected void offsetNX2_0(long _7, long _16, long _25, long _1, long _10, long _19, long _4, long _13, long _22, long _5, long _14, long _23, long _8, long _17, long _26, long _2, long _11, long _20) {
		this._0 = (this._0 & 13514098222497843L) | ((this._0 & 4608307493871763443L) << 2);
		this._2 = (this._2 & 3459609144959447043L) | ((this._2 & 3746783732187526143L) << 2);
		this._4 = (this._4 & 216225571559965443L) | ((this._4 & 4557629625537396543L) << 2);
		this._6 = (this._6 & 13514098222497843L) | ((this._6 & 4608307493871763443L) << 2);
		this._9 = (this._9 & 13514098222497843L) | ((this._9 & 4608307493871763443L) << 2);
		this._11 = (this._11 & 3459609144959447043L) | ((this._11 & 3746783732187526143L) << 2);
		this._13 = (this._13 & 216225571559965443L) | ((this._13 & 4557629625537396543L) << 2);
		this._15 = (this._15 & 13514098222497843L) | ((this._15 & 4608307493871763443L) << 2);
		this._18 = (this._18 & 13514098222497843L) | ((this._18 & 4608307493871763443L) << 2);
		this._20 = (this._20 & 3459609144959447043L) | ((this._20 & 3746783732187526143L) << 2);
		this._22 = (this._22 & 216225571559965443L) | ((this._22 & 4557629625537396543L) << 2);
		this._24 = (this._24 & 13514098222497843L) | ((this._24 & 4608307493871763443L) << 2);
		this._7 = (this._7 & 216225571559965443L) | ((this._7 & 4557629625537396543L) << 2);
		this._16 = (this._16 & 216225571559965443L) | ((this._16 & 4557629625537396543L) << 2);
		this._25 = (this._25 & 216225571559965443L) | ((this._25 & 4557629625537396543L) << 2);
		this._5 = (this._5 & 3459609144959447043L) | ((this._5 & 3746783732187526143L) << 2);
		this._14 = (this._14 & 3459609144959447043L) | ((this._14 & 3746783732187526143L) << 2);
		this._23 = (this._23 & 3459609144959447043L) | ((this._23 & 3746783732187526143L) << 2);
		this._3 = (this._3 & 13514098222497843L) | ((this._3 & 4608307493871763443L) << 2);
		this._12 = (this._12 & 13514098222497843L) | ((this._12 & 4608307493871763443L) << 2);
		this._21 = (this._21 & 13514098222497843L) | ((this._21 & 4608307493871763443L) << 2);
		this._1 = (this._1 & 216225571559965443L) | ((this._1 & 4557629625537396543L) << 2);
		this._10 = (this._10 & 216225571559965443L) | ((this._10 & 4557629625537396543L) << 2);
		this._19 = (this._19 & 216225571559965443L) | ((this._19 & 4557629625537396543L) << 2);
		this._8 = (this._8 & 3459609144959447043L) | ((this._8 & 3746783732187526143L) << 2);
		this._17 = (this._17 & 3459609144959447043L) | ((this._17 & 3746783732187526143L) << 2);
		this._26 = (this._26 & 3459609144959447043L) | ((this._26 & 3746783732187526143L) << 2);
		this._6 = (this._6 & -4L) | ((_7 & -4611686018427387904L) >> 62);
		this._15 = (this._15 & -4L) | ((_16 & -4611686018427387904L) >> 62);
		this._24 = (this._24 & -4L) | ((_25 & -4611686018427387904L) >> 62);
		this._0 = (this._0 & -4L) | ((_1 & -4611686018427387904L) >> 62);
		this._9 = (this._9 & -4L) | ((_10 & -4611686018427387904L) >> 62);
		this._18 = (this._18 & -4L) | ((_19 & -4611686018427387904L) >> 62);
		this._3 = (this._3 & -4L) | ((_4 & -4611686018427387904L) >> 62);
		this._12 = (this._12 & -4L) | ((_13 & -4611686018427387904L) >> 62);
		this._21 = (this._21 & -4L) | ((_22 & -4611686018427387904L) >> 62);
		this._4 = (this._4 & -4L) | ((_5 & -4611686018427387904L) >> 62);
		this._13 = (this._13 & -4L) | ((_14 & -4611686018427387904L) >> 62);
		this._22 = (this._22 & -4L) | ((_23 & -4611686018427387904L) >> 62);
		this._7 = (this._7 & -4L) | ((_8 & -4611686018427387904L) >> 62);
		this._16 = (this._16 & -4L) | ((_17 & -4611686018427387904L) >> 62);
		this._25 = (this._25 & -4L) | ((_26 & -4611686018427387904L) >> 62);
		this._1 = (this._1 & -4L) | ((_2 & -4611686018427387904L) >> 62);
		this._10 = (this._10 & -4L) | ((_11 & -4611686018427387904L) >> 62);
		this._19 = (this._19 & -4L) | ((_20 & -4611686018427387904L) >> 62);
		this._0 = this._0 & -13514098222497841L;
		this._2 = this._2 & -3459609144959447044L;
		this._4 = this._4 & -216225571559965441L;
		this._6 = this._6 & -13514098222497841L;
		this._9 = this._9 & -13514098222497841L;
		this._11 = this._11 & -3459609144959447044L;
		this._13 = this._13 & -216225571559965441L;
		this._15 = this._15 & -13514098222497841L;
		this._18 = this._18 & -13514098222497841L;
		this._20 = this._20 & -3459609144959447044L;
		this._22 = this._22 & -216225571559965441L;
		this._24 = this._24 & -13514098222497841L;
		this._7 = this._7 & -216225571559965441L;
		this._16 = this._16 & -216225571559965441L;
		this._25 = this._25 & -216225571559965441L;
		this._5 = this._5 & -3459609144959447044L;
		this._14 = this._14 & -3459609144959447044L;
		this._23 = this._23 & -3459609144959447044L;
		this._3 = this._3 & -13514098222497841L;
	}
	protected void offsetNX2_1() {
		this._12 = this._12 & -13514098222497841L;
		this._21 = this._21 & -13514098222497841L;
		this._1 = this._1 & -216225571559965441L;
		this._10 = this._10 & -216225571559965441L;
		this._19 = this._19 & -216225571559965441L;
		this._8 = this._8 & -3459609144959447044L;
		this._17 = this._17 & -3459609144959447044L;
		this._26 = this._26 & -3459609144959447044L;
	}
	protected void offsetNX1() {
		long _7 = this._7;
		long _16 = this._16;
		long _25 = this._25;
		long _1 = this._1;
		long _10 = this._10;
		long _19 = this._19;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _5 = this._5;
		long _14 = this._14;
		long _23 = this._23;
		long _8 = this._8;
		long _17 = this._17;
		long _26 = this._26;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNX1_0(_7, _16, _25, _1, _10, _19, _4, _13, _22, _5, _14, _23, _8, _17, _26, _2, _11, _20);
		this.offsetNX1_1();
	}
	protected void offsetNX1_0(long _7, long _16, long _25, long _1, long _10, long _19, long _4, long _13, long _22, long _5, long _14, long _23, long _8, long _17, long _26, long _2, long _11, long _20) {
		this._0 = (this._0 & 4504699407499281L) | ((this._0 & 9221119687151026167L) << 1);
		this._2 = (this._2 & 1153203048319815681L) | ((this._2 & 8646770512694867967L) << 1);
		this._4 = (this._4 & 72075190519988481L) | ((this._4 & 9187334441594781567L) << 1);
		this._6 = (this._6 & 4504699407499281L) | ((this._6 & 9221119687151026167L) << 1);
		this._9 = (this._9 & 4504699407499281L) | ((this._9 & 9221119687151026167L) << 1);
		this._11 = (this._11 & 1153203048319815681L) | ((this._11 & 8646770512694867967L) << 1);
		this._13 = (this._13 & 72075190519988481L) | ((this._13 & 9187334441594781567L) << 1);
		this._15 = (this._15 & 4504699407499281L) | ((this._15 & 9221119687151026167L) << 1);
		this._18 = (this._18 & 4504699407499281L) | ((this._18 & 9221119687151026167L) << 1);
		this._20 = (this._20 & 1153203048319815681L) | ((this._20 & 8646770512694867967L) << 1);
		this._22 = (this._22 & 72075190519988481L) | ((this._22 & 9187334441594781567L) << 1);
		this._24 = (this._24 & 4504699407499281L) | ((this._24 & 9221119687151026167L) << 1);
		this._7 = (this._7 & 72075190519988481L) | ((this._7 & 9187334441594781567L) << 1);
		this._16 = (this._16 & 72075190519988481L) | ((this._16 & 9187334441594781567L) << 1);
		this._25 = (this._25 & 72075190519988481L) | ((this._25 & 9187334441594781567L) << 1);
		this._5 = (this._5 & 1153203048319815681L) | ((this._5 & 8646770512694867967L) << 1);
		this._14 = (this._14 & 1153203048319815681L) | ((this._14 & 8646770512694867967L) << 1);
		this._23 = (this._23 & 1153203048319815681L) | ((this._23 & 8646770512694867967L) << 1);
		this._3 = (this._3 & 4504699407499281L) | ((this._3 & 9221119687151026167L) << 1);
		this._12 = (this._12 & 4504699407499281L) | ((this._12 & 9221119687151026167L) << 1);
		this._21 = (this._21 & 4504699407499281L) | ((this._21 & 9221119687151026167L) << 1);
		this._1 = (this._1 & 72075190519988481L) | ((this._1 & 9187334441594781567L) << 1);
		this._10 = (this._10 & 72075190519988481L) | ((this._10 & 9187334441594781567L) << 1);
		this._19 = (this._19 & 72075190519988481L) | ((this._19 & 9187334441594781567L) << 1);
		this._8 = (this._8 & 1153203048319815681L) | ((this._8 & 8646770512694867967L) << 1);
		this._17 = (this._17 & 1153203048319815681L) | ((this._17 & 8646770512694867967L) << 1);
		this._26 = (this._26 & 1153203048319815681L) | ((this._26 & 8646770512694867967L) << 1);
		this._6 = (this._6 & -2L) | ((_7 & -9223372036854775808L) >> 63);
		this._15 = (this._15 & -2L) | ((_16 & -9223372036854775808L) >> 63);
		this._24 = (this._24 & -2L) | ((_25 & -9223372036854775808L) >> 63);
		this._0 = (this._0 & -2L) | ((_1 & -9223372036854775808L) >> 63);
		this._9 = (this._9 & -2L) | ((_10 & -9223372036854775808L) >> 63);
		this._18 = (this._18 & -2L) | ((_19 & -9223372036854775808L) >> 63);
		this._3 = (this._3 & -2L) | ((_4 & -9223372036854775808L) >> 63);
		this._12 = (this._12 & -2L) | ((_13 & -9223372036854775808L) >> 63);
		this._21 = (this._21 & -2L) | ((_22 & -9223372036854775808L) >> 63);
		this._4 = (this._4 & -2L) | ((_5 & -9223372036854775808L) >> 63);
		this._13 = (this._13 & -2L) | ((_14 & -9223372036854775808L) >> 63);
		this._22 = (this._22 & -2L) | ((_23 & -9223372036854775808L) >> 63);
		this._7 = (this._7 & -2L) | ((_8 & -9223372036854775808L) >> 63);
		this._16 = (this._16 & -2L) | ((_17 & -9223372036854775808L) >> 63);
		this._25 = (this._25 & -2L) | ((_26 & -9223372036854775808L) >> 63);
		this._1 = (this._1 & -2L) | ((_2 & -9223372036854775808L) >> 63);
		this._10 = (this._10 & -2L) | ((_11 & -9223372036854775808L) >> 63);
		this._19 = (this._19 & -2L) | ((_20 & -9223372036854775808L) >> 63);
		this._0 = this._0 & -4504699407499281L;
		this._2 = this._2 & -1153203048319815682L;
		this._4 = this._4 & -72075190519988481L;
		this._6 = this._6 & -4504699407499281L;
		this._9 = this._9 & -4504699407499281L;
		this._11 = this._11 & -1153203048319815682L;
		this._13 = this._13 & -72075190519988481L;
		this._15 = this._15 & -4504699407499281L;
		this._18 = this._18 & -4504699407499281L;
		this._20 = this._20 & -1153203048319815682L;
		this._22 = this._22 & -72075190519988481L;
		this._24 = this._24 & -4504699407499281L;
		this._7 = this._7 & -72075190519988481L;
		this._16 = this._16 & -72075190519988481L;
		this._25 = this._25 & -72075190519988481L;
		this._5 = this._5 & -1153203048319815682L;
		this._14 = this._14 & -1153203048319815682L;
		this._23 = this._23 & -1153203048319815682L;
		this._3 = this._3 & -4504699407499281L;
	}
	protected void offsetNX1_1() {
		this._12 = this._12 & -4504699407499281L;
		this._21 = this._21 & -4504699407499281L;
		this._1 = this._1 & -72075190519988481L;
		this._10 = this._10 & -72075190519988481L;
		this._19 = this._19 & -72075190519988481L;
		this._8 = this._8 & -1153203048319815682L;
		this._17 = this._17 & -1153203048319815682L;
		this._26 = this._26 & -1153203048319815682L;
	}

	public void offsetY(int amount) {
		amount = Math.max(-HEIGHT, Math.min(HEIGHT, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {
		long _20 = this._20;
		long _11 = this._11;
		long _2 = this._2;
		long _22 = this._22;
		long _13 = this._13;
		long _4 = this._4;
		long _24 = this._24;
		long _15 = this._15;
		long _6 = this._6;
		this.offsetPY4_0(_20, _11, _2, _22, _13, _4, _24, _15, _6);
	}
	protected void offsetPY4_0(long _20, long _11, long _2, long _22, long _13, long _4, long _24, long _15, long _6) {
		this._26 = (this._26 & -65536L) | ((this._26 & -281474976710656L) >> 48);
		this._24 = (this._24 & 65535L) | ((this._23 & 281474976710655L) << 16);
		this._22 = (this._22 & 4294967295L) | ((this._21 & 281474976645120L) << 16);
		this._20 = (this._20 & 281474976710655L) | ((this._19 & 281470681743360L) << 16);
		this._17 = (this._17 & -65536L) | ((this._17 & -281474976710656L) >> 48);
		this._15 = (this._15 & 65535L) | ((this._14 & 281474976710655L) << 16);
		this._13 = (this._13 & 4294967295L) | ((this._12 & 281474976645120L) << 16);
		this._11 = (this._11 & 281474976710655L) | ((this._10 & 281470681743360L) << 16);
		this._8 = (this._8 & -65536L) | ((this._8 & -281474976710656L) >> 48);
		this._6 = (this._6 & 65535L) | ((this._5 & 281474976710655L) << 16);
		this._4 = (this._4 & 4294967295L) | ((this._3 & 281474976645120L) << 16);
		this._2 = (this._2 & 281474976710655L) | ((this._1 & 281470681743360L) << 16);
		this._26 = (this._26 & 65535L) | ((this._25 & 281474976710655L) << 16);
		this._19 = (this._19 & -65536L) | ((this._19 & -281474976710656L) >> 48);
		this._17 = (this._17 & 65535L) | ((this._16 & 281474976710655L) << 16);
		this._10 = (this._10 & -65536L) | ((this._10 & -281474976710656L) >> 48);
		this._8 = (this._8 & 65535L) | ((this._7 & 281474976710655L) << 16);
		this._1 = (this._1 & -65536L) | ((this._1 & -281474976710656L) >> 48);
		this._21 = (this._21 & -65536L) | ((this._21 & -281474976710656L) >> 48);
		this._19 = (this._19 & 65535L) | ((this._18 & 281474976710655L) << 16);
		this._12 = (this._12 & -65536L) | ((this._12 & -281474976710656L) >> 48);
		this._10 = (this._10 & 65535L) | ((this._9 & 281474976710655L) << 16);
		this._3 = (this._3 & -65536L) | ((this._3 & -281474976710656L) >> 48);
		this._1 = (this._1 & 65535L) | ((this._0 & 281474976710655L) << 16);
		this._23 = (this._23 & -65536L) | ((this._23 & -281474976710656L) >> 48);
		this._21 = (this._21 & 65535L) | ((_20 & 281474976710655L) << 16);
		this._14 = (this._14 & -65536L) | ((this._14 & -281474976710656L) >> 48);
		this._12 = (this._12 & 65535L) | ((_11 & 281474976710655L) << 16);
		this._5 = (this._5 & -65536L) | ((this._5 & -281474976710656L) >> 48);
		this._3 = (this._3 & 65535L) | ((_2 & 281474976710655L) << 16);
		this._25 = (this._25 & -65536L) | ((this._25 & -281474976710656L) >> 48);
		this._23 = (this._23 & -281474976645121L) | ((_22 & 4294967295L) << 16);
		this._16 = (this._16 & -65536L) | ((this._16 & -281474976710656L) >> 48);
		this._14 = (this._14 & -281474976645121L) | ((_13 & 4294967295L) << 16);
		this._7 = (this._7 & -65536L) | ((this._7 & -281474976710656L) >> 48);
		this._5 = (this._5 & -281474976645121L) | ((_4 & 4294967295L) << 16);
		this._25 = (this._25 & -4294901761L) | ((_24 & 65535L) << 16);
		this._18 = (this._18 & -65536L) | ((this._18 & -281474976710656L) >> 48);
		this._16 = (this._16 & -4294901761L) | ((_15 & 65535L) << 16);
		this._9 = (this._9 & -65536L) | ((this._9 & -281474976710656L) >> 48);
		this._7 = (this._7 & -4294901761L) | ((_6 & 65535L) << 16);
		this._0 = (this._0 & -65536L) | ((this._0 & -281474976710656L) >> 48);
		this._25 = this._25 & 4294967295L;
		this._23 = this._23 & 281474976710655L;
		this._20 = this._20 & -281474976710656L;
		this._18 = this._18 & 65535L;
		this._16 = this._16 & 4294967295L;
		this._14 = this._14 & 281474976710655L;
		this._11 = this._11 & -281474976710656L;
		this._9 = this._9 & 65535L;
		this._7 = this._7 & 4294967295L;
		this._5 = this._5 & 281474976710655L;
		this._2 = this._2 & -281474976710656L;
		this._0 = this._0 & 65535L;
		this._22 = this._22 & -4294967296L;
		this._13 = this._13 & -4294967296L;
		this._4 = this._4 & -4294967296L;
		this._24 = this._24 & -65536L;
		this._15 = this._15 & -65536L;
		this._6 = this._6 & -65536L;
	}
	protected void offsetPY2() {
		long _20 = this._20;
		long _11 = this._11;
		long _2 = this._2;
		long _22 = this._22;
		long _13 = this._13;
		long _4 = this._4;
		long _24 = this._24;
		long _15 = this._15;
		long _6 = this._6;
		this.offsetPY2_0(_20, _11, _2, _22, _13, _4, _24, _15, _6);
		this.offsetPY2_1();
	}
	protected void offsetPY2_0(long _20, long _11, long _2, long _22, long _13, long _4, long _24, long _15, long _6) {
		this._26 = (this._26 & -1099511627776L) | ((this._26 & -16777216L) >> 24);
		this._24 = (this._24 & -1099511562241L) | ((this._24 & -1099511627776L) >> 24);
		this._22 = (this._22 & -1095216660736L) | ((this._22 & -72057589759737856L) >> 24);
		this._20 = (this._20 & 281474976710655L) | ((this._19 & 16776960L) << 40);
		this._17 = (this._17 & -1099511627776L) | ((this._17 & -16777216L) >> 24);
		this._15 = (this._15 & -1099511562241L) | ((this._15 & -1099511627776L) >> 24);
		this._13 = (this._13 & -1095216660736L) | ((this._13 & -72057589759737856L) >> 24);
		this._11 = (this._11 & 281474976710655L) | ((this._10 & 16776960L) << 40);
		this._8 = (this._8 & -1099511627776L) | ((this._8 & -16777216L) >> 24);
		this._6 = (this._6 & -1099511562241L) | ((this._6 & -1099511627776L) >> 24);
		this._4 = (this._4 & -1095216660736L) | ((this._4 & -72057589759737856L) >> 24);
		this._2 = (this._2 & 281474976710655L) | ((this._1 & 16776960L) << 40);
		this._22 = (this._22 & 1099511627775L) | ((this._21 & 16777215L) << 40);
		this._13 = (this._13 & 1099511627775L) | ((this._12 & 16777215L) << 40);
		this._4 = (this._4 & 1099511627775L) | ((this._3 & 16777215L) << 40);
		this._24 = (this._24 & 1099511627775L) | ((this._23 & 16777215L) << 40);
		this._19 = (this._19 & -1099511627776L) | ((this._19 & -16777216L) >> 24);
		this._15 = (this._15 & 1099511627775L) | ((this._14 & 16777215L) << 40);
		this._10 = (this._10 & -1099511627776L) | ((this._10 & -16777216L) >> 24);
		this._6 = (this._6 & 1099511627775L) | ((this._5 & 16777215L) << 40);
		this._1 = (this._1 & -1099511627776L) | ((this._1 & -16777216L) >> 24);
		this._21 = (this._21 & -1099511627776L) | ((this._21 & -16777216L) >> 24);
		this._12 = (this._12 & -1099511627776L) | ((this._12 & -16777216L) >> 24);
		this._3 = (this._3 & -1099511627776L) | ((this._3 & -16777216L) >> 24);
		this._26 = (this._26 & 1099511627775L) | ((this._25 & 16777215L) << 40);
		this._23 = (this._23 & -1099511627776L) | ((this._23 & -16777216L) >> 24);
		this._17 = (this._17 & 1099511627775L) | ((this._16 & 16777215L) << 40);
		this._14 = (this._14 & -1099511627776L) | ((this._14 & -16777216L) >> 24);
		this._8 = (this._8 & 1099511627775L) | ((this._7 & 16777215L) << 40);
		this._5 = (this._5 & -1099511627776L) | ((this._5 & -16777216L) >> 24);
		this._19 = (this._19 & 1099511627775L) | ((this._18 & 16777215L) << 40);
		this._10 = (this._10 & 1099511627775L) | ((this._9 & 16777215L) << 40);
		this._1 = (this._1 & 1099511627775L) | ((this._0 & 16777215L) << 40);
		this._25 = (this._25 & -1099511627776L) | ((this._25 & -16777216L) >> 24);
		this._21 = (this._21 & 1099511627775L) | ((_20 & 16777215L) << 40);
		this._16 = (this._16 & -1099511627776L) | ((this._16 & -16777216L) >> 24);
		this._12 = (this._12 & 1099511627775L) | ((_11 & 16777215L) << 40);
		this._7 = (this._7 & -1099511627776L) | ((this._7 & -16777216L) >> 24);
		this._3 = (this._3 & 1099511627775L) | ((_2 & 16777215L) << 40);
		this._18 = (this._18 & -1099511627776L) | ((this._18 & -16777216L) >> 24);
		this._9 = (this._9 & -1099511627776L) | ((this._9 & -16777216L) >> 24);
		this._0 = (this._0 & -1099511627776L) | ((this._0 & -16777216L) >> 24);
		this._23 = (this._23 & 1099511627775L) | ((_22 & 16777215L) << 40);
		this._20 = (this._20 & -16777216L) | ((_20 & 281474959933440L) >> 24);
		this._14 = (this._14 & 1099511627775L) | ((_13 & 16777215L) << 40);
		this._11 = (this._11 & -16777216L) | ((_11 & 281474959933440L) >> 24);
		this._5 = (this._5 & 1099511627775L) | ((_4 & 16777215L) << 40);
		this._2 = (this._2 & -16777216L) | ((_2 & 281474959933440L) >> 24);
		this._25 = (this._25 & -72056494526300161L) | ((_24 & 65535L) << 40);
		this._16 = (this._16 & -72056494526300161L) | ((_15 & 65535L) << 40);
		this._7 = (this._7 & -72056494526300161L) | ((_6 & 65535L) << 40);
		this._25 = this._25 & 72057594037927935L;
		this._22 = this._22 & -4294967041L;
		this._20 = this._20 & -281474959933441L;
		this._18 = this._18 & 1099511627775L;
		this._16 = this._16 & 72057594037927935L;
		this._13 = this._13 & -4294967041L;
		this._11 = this._11 & -281474959933441L;
		this._9 = this._9 & 1099511627775L;
		this._7 = this._7 & 72057594037927935L;
		this._4 = this._4 & -4294967041L;
		this._2 = this._2 & -281474959933441L;
		this._0 = this._0 & 1099511627775L;
		this._24 = this._24 & -65536L;
	}
	protected void offsetPY2_1() {
		this._15 = this._15 & -65536L;
		this._6 = this._6 & -65536L;
	}
	protected void offsetPY1() {
		long _20 = this._20;
		long _11 = this._11;
		long _2 = this._2;
		long _22 = this._22;
		long _13 = this._13;
		long _4 = this._4;
		long _24 = this._24;
		long _15 = this._15;
		long _6 = this._6;
		this.offsetPY1_0(_20, _11, _2, _22, _13, _4, _24, _15, _6);
	}
	protected void offsetPY1_0(long _20, long _11, long _2, long _22, long _13, long _4, long _24, long _15, long _6) {
		this._26 = (this._26 & -4503599627370496L) | ((this._26 & -4096L) >> 12);
		this._24 = (this._24 & -4503599627304976L) | ((this._24 & -268374016L) >> 12);
		this._22 = (this._22 & -4503595333451776L) | ((this._22 & -17587891081216L) >> 12);
		this._20 = (this._20 & -4222193370136576L) | ((this._20 & -1152640029630140416L) >> 12);
		this._17 = (this._17 & -4503599627370496L) | ((this._17 & -4096L) >> 12);
		this._15 = (this._15 & -4503599627304976L) | ((this._15 & -268374016L) >> 12);
		this._13 = (this._13 & -4503595333451776L) | ((this._13 & -17587891081216L) >> 12);
		this._11 = (this._11 & -4222193370136576L) | ((this._11 & -1152640029630140416L) >> 12);
		this._8 = (this._8 & -4503599627370496L) | ((this._8 & -4096L) >> 12);
		this._6 = (this._6 & -4503599627304976L) | ((this._6 & -268374016L) >> 12);
		this._4 = (this._4 & -4503595333451776L) | ((this._4 & -17587891081216L) >> 12);
		this._2 = (this._2 & -4222193370136576L) | ((this._2 & -1152640029630140416L) >> 12);
		this._20 = (this._20 & 4503599627370495L) | ((this._19 & 4095L) << 52);
		this._11 = (this._11 & 4503599627370495L) | ((this._10 & 4095L) << 52);
		this._2 = (this._2 & 4503599627370495L) | ((this._1 & 4095L) << 52);
		this._22 = (this._22 & 4503599627370495L) | ((this._21 & 4095L) << 52);
		this._19 = (this._19 & -4503599627370496L) | ((this._19 & -4096L) >> 12);
		this._13 = (this._13 & 4503599627370495L) | ((this._12 & 4095L) << 52);
		this._10 = (this._10 & -4503599627370496L) | ((this._10 & -4096L) >> 12);
		this._4 = (this._4 & 4503599627370495L) | ((this._3 & 4095L) << 52);
		this._1 = (this._1 & -4503599627370496L) | ((this._1 & -4096L) >> 12);
		this._24 = (this._24 & 4503599627370495L) | ((this._23 & 4095L) << 52);
		this._21 = (this._21 & -4503599627370496L) | ((this._21 & -4096L) >> 12);
		this._15 = (this._15 & 4503599627370495L) | ((this._14 & 4095L) << 52);
		this._12 = (this._12 & -4503599627370496L) | ((this._12 & -4096L) >> 12);
		this._6 = (this._6 & 4503599627370495L) | ((this._5 & 4095L) << 52);
		this._3 = (this._3 & -4503599627370496L) | ((this._3 & -4096L) >> 12);
		this._23 = (this._23 & -4503599627370496L) | ((this._23 & -4096L) >> 12);
		this._14 = (this._14 & -4503599627370496L) | ((this._14 & -4096L) >> 12);
		this._5 = (this._5 & -4503599627370496L) | ((this._5 & -4096L) >> 12);
		this._26 = (this._26 & 4503599627370495L) | ((this._25 & 4095L) << 52);
		this._17 = (this._17 & 4503599627370495L) | ((this._16 & 4095L) << 52);
		this._8 = (this._8 & 4503599627370495L) | ((this._7 & 4095L) << 52);
		this._25 = (this._25 & -4503599627370496L) | ((this._25 & -4096L) >> 12);
		this._19 = (this._19 & 4503599627370495L) | ((this._18 & 4095L) << 52);
		this._16 = (this._16 & -4503599627370496L) | ((this._16 & -4096L) >> 12);
		this._10 = (this._10 & 4503599627370495L) | ((this._9 & 4095L) << 52);
		this._7 = (this._7 & -4503599627370496L) | ((this._7 & -4096L) >> 12);
		this._1 = (this._1 & 4503599627370495L) | ((this._0 & 4095L) << 52);
		this._21 = (this._21 & 4503599627370495L) | ((_20 & 4095L) << 52);
		this._18 = (this._18 & -4503599627370496L) | ((this._18 & -4096L) >> 12);
		this._12 = (this._12 & 4503599627370495L) | ((_11 & 4095L) << 52);
		this._9 = (this._9 & -4503599627370496L) | ((this._9 & -4096L) >> 12);
		this._3 = (this._3 & 4503599627370495L) | ((_2 & 4095L) << 52);
		this._0 = (this._0 & -4503599627370496L) | ((this._0 & -4096L) >> 12);
		this._23 = (this._23 & 4503599627370495L) | ((_22 & 4095L) << 52);
		this._14 = (this._14 & 4503599627370495L) | ((_13 & 4095L) << 52);
		this._5 = (this._5 & 4503599627370495L) | ((_4 & 4095L) << 52);
		this._25 = (this._25 & 4503599627370495L) | ((_24 & 4095L) << 52);
		this._16 = (this._16 & 4503599627370495L) | ((_15 & 4095L) << 52);
		this._7 = (this._7 & 4503599627370495L) | ((_6 & 4095L) << 52);
		this._24 = this._24 & -65521L;
		this._22 = this._22 & -4293918721L;
		this._20 = this._20 & -281406257233921L;
		this._18 = this._18 & 4503599627370495L;
		this._15 = this._15 & -65521L;
		this._13 = this._13 & -4293918721L;
		this._11 = this._11 & -281406257233921L;
		this._9 = this._9 & 4503599627370495L;
		this._6 = this._6 & -65521L;
		this._4 = this._4 & -4293918721L;
		this._2 = this._2 & -281406257233921L;
		this._0 = this._0 & 4503599627370495L;
	}
	protected void offsetNY4() {
		long _6 = this._6;
		long _15 = this._15;
		long _24 = this._24;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNY4_0(_6, _15, _24, _4, _13, _22, _2, _11, _20);
	}
	protected void offsetNY4_0(long _6, long _15, long _24, long _4, long _13, long _22, long _2, long _11, long _20) {
		this._0 = (this._0 & 281474976710655L) | ((this._0 & 65535L) << 48);
		this._2 = (this._2 & -281474976710656L) | ((this._3 & -65536L) >> 16);
		this._4 = (this._4 & -4294967296L) | ((this._5 & 281474976645120L) >> 16);
		this._6 = (this._6 & -65536L) | ((this._7 & 4294901760L) >> 16);
		this._9 = (this._9 & 281474976710655L) | ((this._9 & 65535L) << 48);
		this._11 = (this._11 & -281474976710656L) | ((this._12 & -65536L) >> 16);
		this._13 = (this._13 & -4294967296L) | ((this._14 & 281474976645120L) >> 16);
		this._15 = (this._15 & -65536L) | ((this._16 & 4294901760L) >> 16);
		this._18 = (this._18 & 281474976710655L) | ((this._18 & 65535L) << 48);
		this._20 = (this._20 & -281474976710656L) | ((this._21 & -65536L) >> 16);
		this._22 = (this._22 & -4294967296L) | ((this._23 & 281474976645120L) >> 16);
		this._24 = (this._24 & -65536L) | ((this._25 & 4294901760L) >> 16);
		this._0 = (this._0 & -281474976710656L) | ((this._1 & -65536L) >> 16);
		this._7 = (this._7 & 281474976710655L) | ((this._7 & 65535L) << 48);
		this._9 = (this._9 & -281474976710656L) | ((this._10 & -65536L) >> 16);
		this._16 = (this._16 & 281474976710655L) | ((this._16 & 65535L) << 48);
		this._18 = (this._18 & -281474976710656L) | ((this._19 & -65536L) >> 16);
		this._25 = (this._25 & 281474976710655L) | ((this._25 & 65535L) << 48);
		this._5 = (this._5 & 281474976710655L) | ((this._5 & 65535L) << 48);
		this._7 = (this._7 & -281474976710656L) | ((this._8 & -65536L) >> 16);
		this._14 = (this._14 & 281474976710655L) | ((this._14 & 65535L) << 48);
		this._16 = (this._16 & -281474976710656L) | ((this._17 & -65536L) >> 16);
		this._23 = (this._23 & 281474976710655L) | ((this._23 & 65535L) << 48);
		this._25 = (this._25 & -281474976710656L) | ((this._26 & -65536L) >> 16);
		this._3 = (this._3 & 281474976710655L) | ((this._3 & 65535L) << 48);
		this._5 = (this._5 & -281474976710656L) | ((_6 & -65536L) >> 16);
		this._12 = (this._12 & 281474976710655L) | ((this._12 & 65535L) << 48);
		this._14 = (this._14 & -281474976710656L) | ((_15 & -65536L) >> 16);
		this._21 = (this._21 & 281474976710655L) | ((this._21 & 65535L) << 48);
		this._23 = (this._23 & -281474976710656L) | ((_24 & -65536L) >> 16);
		this._1 = (this._1 & 281474976710655L) | ((this._1 & 65535L) << 48);
		this._3 = (this._3 & -281474976645121L) | ((_4 & -4294967296L) >> 16);
		this._10 = (this._10 & 281474976710655L) | ((this._10 & 65535L) << 48);
		this._12 = (this._12 & -281474976645121L) | ((_13 & -4294967296L) >> 16);
		this._19 = (this._19 & 281474976710655L) | ((this._19 & 65535L) << 48);
		this._21 = (this._21 & -281474976645121L) | ((_22 & -4294967296L) >> 16);
		this._1 = (this._1 & -281470681743361L) | ((_2 & -281474976710656L) >> 16);
		this._8 = (this._8 & 281474976710655L) | ((this._8 & 65535L) << 48);
		this._10 = (this._10 & -281470681743361L) | ((_11 & -281474976710656L) >> 16);
		this._17 = (this._17 & 281474976710655L) | ((this._17 & 65535L) << 48);
		this._19 = (this._19 & -281470681743361L) | ((_20 & -281474976710656L) >> 16);
		this._26 = (this._26 & 281474976710655L) | ((this._26 & 65535L) << 48);
		this._1 = this._1 & -4294967296L;
		this._3 = this._3 & -65536L;
		this._6 = this._6 & 65535L;
		this._8 = this._8 & -281474976710656L;
		this._10 = this._10 & -4294967296L;
		this._12 = this._12 & -65536L;
		this._15 = this._15 & 65535L;
		this._17 = this._17 & -281474976710656L;
		this._19 = this._19 & -4294967296L;
		this._21 = this._21 & -65536L;
		this._24 = this._24 & 65535L;
		this._26 = this._26 & -281474976710656L;
		this._4 = this._4 & 4294967295L;
		this._13 = this._13 & 4294967295L;
		this._22 = this._22 & 4294967295L;
		this._2 = this._2 & 281474976710655L;
		this._11 = this._11 & 281474976710655L;
		this._20 = this._20 & 281474976710655L;
	}
	protected void offsetNY2() {
		long _6 = this._6;
		long _15 = this._15;
		long _24 = this._24;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNY2_0(_6, _15, _24, _4, _13, _22, _2, _11, _20);
		this.offsetNY2_1();
	}
	protected void offsetNY2_0(long _6, long _15, long _24, long _4, long _13, long _22, long _2, long _11, long _20) {
		this._0 = (this._0 & 16777215L) | ((this._0 & 1099511627775L) << 24);
		this._2 = (this._2 & -281474959933441L) | ((this._2 & 16777215L) << 24);
		this._4 = (this._4 & 72057589759737855L) | ((this._4 & 1095216660735L) << 24);
		this._6 = (this._6 & -65536L) | ((this._7 & 72056494526300160L) >> 40);
		this._9 = (this._9 & 16777215L) | ((this._9 & 1099511627775L) << 24);
		this._11 = (this._11 & -281474959933441L) | ((this._11 & 16777215L) << 24);
		this._13 = (this._13 & 72057589759737855L) | ((this._13 & 1095216660735L) << 24);
		this._15 = (this._15 & -65536L) | ((this._16 & 72056494526300160L) >> 40);
		this._18 = (this._18 & 16777215L) | ((this._18 & 1099511627775L) << 24);
		this._20 = (this._20 & -281474959933441L) | ((this._20 & 16777215L) << 24);
		this._22 = (this._22 & 72057589759737855L) | ((this._22 & 1095216660735L) << 24);
		this._24 = (this._24 & -65536L) | ((this._25 & 72056494526300160L) >> 40);
		this._4 = (this._4 & -16777216L) | ((this._5 & -1099511627776L) >> 40);
		this._13 = (this._13 & -16777216L) | ((this._14 & -1099511627776L) >> 40);
		this._22 = (this._22 & -16777216L) | ((this._23 & -1099511627776L) >> 40);
		this._2 = (this._2 & -16777216L) | ((this._3 & -1099511627776L) >> 40);
		this._7 = (this._7 & 16777215L) | ((this._7 & 1099511627775L) << 24);
		this._11 = (this._11 & -16777216L) | ((this._12 & -1099511627776L) >> 40);
		this._16 = (this._16 & 16777215L) | ((this._16 & 1099511627775L) << 24);
		this._20 = (this._20 & -16777216L) | ((this._21 & -1099511627776L) >> 40);
		this._25 = (this._25 & 16777215L) | ((this._25 & 1099511627775L) << 24);
		this._5 = (this._5 & 16777215L) | ((this._5 & 1099511627775L) << 24);
		this._14 = (this._14 & 16777215L) | ((this._14 & 1099511627775L) << 24);
		this._23 = (this._23 & 16777215L) | ((this._23 & 1099511627775L) << 24);
		this._0 = (this._0 & -16777216L) | ((this._1 & -1099511627776L) >> 40);
		this._3 = (this._3 & 16777215L) | ((this._3 & 1099511627775L) << 24);
		this._9 = (this._9 & -16777216L) | ((this._10 & -1099511627776L) >> 40);
		this._12 = (this._12 & 16777215L) | ((this._12 & 1099511627775L) << 24);
		this._18 = (this._18 & -16777216L) | ((this._19 & -1099511627776L) >> 40);
		this._21 = (this._21 & 16777215L) | ((this._21 & 1099511627775L) << 24);
		this._7 = (this._7 & -16777216L) | ((this._8 & -1099511627776L) >> 40);
		this._16 = (this._16 & -16777216L) | ((this._17 & -1099511627776L) >> 40);
		this._25 = (this._25 & -16777216L) | ((this._26 & -1099511627776L) >> 40);
		this._1 = (this._1 & 16777215L) | ((this._1 & 1099511627775L) << 24);
		this._5 = (this._5 & -16777216L) | ((_6 & -1099511627776L) >> 40);
		this._10 = (this._10 & 16777215L) | ((this._10 & 1099511627775L) << 24);
		this._14 = (this._14 & -16777216L) | ((_15 & -1099511627776L) >> 40);
		this._19 = (this._19 & 16777215L) | ((this._19 & 1099511627775L) << 24);
		this._23 = (this._23 & -16777216L) | ((_24 & -1099511627776L) >> 40);
		this._8 = (this._8 & 16777215L) | ((this._8 & 1099511627775L) << 24);
		this._17 = (this._17 & 16777215L) | ((this._17 & 1099511627775L) << 24);
		this._26 = (this._26 & 16777215L) | ((this._26 & 1099511627775L) << 24);
		this._3 = (this._3 & -16777216L) | ((_4 & -1099511627776L) >> 40);
		this._6 = (this._6 & 1099511627775L) | ((_6 & 1099511562240L) << 24);
		this._12 = (this._12 & -16777216L) | ((_13 & -1099511627776L) >> 40);
		this._15 = (this._15 & 1099511627775L) | ((_15 & 1099511562240L) << 24);
		this._21 = (this._21 & -16777216L) | ((_22 & -1099511627776L) >> 40);
		this._24 = (this._24 & 1099511627775L) | ((_24 & 1099511562240L) << 24);
		this._1 = (this._1 & -16776961L) | ((_2 & -281474976710656L) >> 40);
		this._10 = (this._10 & -16776961L) | ((_11 & -281474976710656L) >> 40);
		this._19 = (this._19 & -16776961L) | ((_20 & -281474976710656L) >> 40);
		this._1 = this._1 & -256L;
		this._4 = this._4 & -72057589742960641L;
		this._6 = this._6 & -1099511562241L;
		this._8 = this._8 & -16777216L;
		this._10 = this._10 & -256L;
		this._13 = this._13 & -72057589742960641L;
		this._15 = this._15 & -1099511562241L;
		this._17 = this._17 & -16777216L;
		this._19 = this._19 & -256L;
		this._22 = this._22 & -72057589742960641L;
		this._24 = this._24 & -1099511562241L;
		this._26 = this._26 & -16777216L;
		this._2 = this._2 & 281474976710655L;
	}
	protected void offsetNY2_1() {
		this._11 = this._11 & 281474976710655L;
		this._20 = this._20 & 281474976710655L;
	}
	protected void offsetNY1() {
		long _6 = this._6;
		long _15 = this._15;
		long _24 = this._24;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _2 = this._2;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNY1_0(_6, _15, _24, _4, _13, _22, _2, _11, _20);
	}
	protected void offsetNY1_0(long _6, long _15, long _24, long _4, long _13, long _22, long _2, long _11, long _20) {
		this._0 = (this._0 & 4095L) | ((this._0 & 4503599627370495L) << 12);
		this._2 = (this._2 & 1152640029630140415L) | ((this._2 & 4222193370136575L) << 12);
		this._4 = (this._4 & 17587891081215L) | ((this._4 & 4503595333451775L) << 12);
		this._6 = (this._6 & 268374015L) | ((this._6 & 4503599627304975L) << 12);
		this._9 = (this._9 & 4095L) | ((this._9 & 4503599627370495L) << 12);
		this._11 = (this._11 & 1152640029630140415L) | ((this._11 & 4222193370136575L) << 12);
		this._13 = (this._13 & 17587891081215L) | ((this._13 & 4503595333451775L) << 12);
		this._15 = (this._15 & 268374015L) | ((this._15 & 4503599627304975L) << 12);
		this._18 = (this._18 & 4095L) | ((this._18 & 4503599627370495L) << 12);
		this._20 = (this._20 & 1152640029630140415L) | ((this._20 & 4222193370136575L) << 12);
		this._22 = (this._22 & 17587891081215L) | ((this._22 & 4503595333451775L) << 12);
		this._24 = (this._24 & 268374015L) | ((this._24 & 4503599627304975L) << 12);
		this._6 = (this._6 & -4096L) | ((this._7 & -4503599627370496L) >> 52);
		this._15 = (this._15 & -4096L) | ((this._16 & -4503599627370496L) >> 52);
		this._24 = (this._24 & -4096L) | ((this._25 & -4503599627370496L) >> 52);
		this._4 = (this._4 & -4096L) | ((this._5 & -4503599627370496L) >> 52);
		this._7 = (this._7 & 4095L) | ((this._7 & 4503599627370495L) << 12);
		this._13 = (this._13 & -4096L) | ((this._14 & -4503599627370496L) >> 52);
		this._16 = (this._16 & 4095L) | ((this._16 & 4503599627370495L) << 12);
		this._22 = (this._22 & -4096L) | ((this._23 & -4503599627370496L) >> 52);
		this._25 = (this._25 & 4095L) | ((this._25 & 4503599627370495L) << 12);
		this._2 = (this._2 & -4096L) | ((this._3 & -4503599627370496L) >> 52);
		this._5 = (this._5 & 4095L) | ((this._5 & 4503599627370495L) << 12);
		this._11 = (this._11 & -4096L) | ((this._12 & -4503599627370496L) >> 52);
		this._14 = (this._14 & 4095L) | ((this._14 & 4503599627370495L) << 12);
		this._20 = (this._20 & -4096L) | ((this._21 & -4503599627370496L) >> 52);
		this._23 = (this._23 & 4095L) | ((this._23 & 4503599627370495L) << 12);
		this._3 = (this._3 & 4095L) | ((this._3 & 4503599627370495L) << 12);
		this._12 = (this._12 & 4095L) | ((this._12 & 4503599627370495L) << 12);
		this._21 = (this._21 & 4095L) | ((this._21 & 4503599627370495L) << 12);
		this._0 = (this._0 & -4096L) | ((this._1 & -4503599627370496L) >> 52);
		this._9 = (this._9 & -4096L) | ((this._10 & -4503599627370496L) >> 52);
		this._18 = (this._18 & -4096L) | ((this._19 & -4503599627370496L) >> 52);
		this._1 = (this._1 & 4095L) | ((this._1 & 4503599627370495L) << 12);
		this._7 = (this._7 & -4096L) | ((this._8 & -4503599627370496L) >> 52);
		this._10 = (this._10 & 4095L) | ((this._10 & 4503599627370495L) << 12);
		this._16 = (this._16 & -4096L) | ((this._17 & -4503599627370496L) >> 52);
		this._19 = (this._19 & 4095L) | ((this._19 & 4503599627370495L) << 12);
		this._25 = (this._25 & -4096L) | ((this._26 & -4503599627370496L) >> 52);
		this._5 = (this._5 & -4096L) | ((_6 & -4503599627370496L) >> 52);
		this._8 = (this._8 & 4095L) | ((this._8 & 4503599627370495L) << 12);
		this._14 = (this._14 & -4096L) | ((_15 & -4503599627370496L) >> 52);
		this._17 = (this._17 & 4095L) | ((this._17 & 4503599627370495L) << 12);
		this._23 = (this._23 & -4096L) | ((_24 & -4503599627370496L) >> 52);
		this._26 = (this._26 & 4095L) | ((this._26 & 4503599627370495L) << 12);
		this._3 = (this._3 & -4096L) | ((_4 & -4503599627370496L) >> 52);
		this._12 = (this._12 & -4096L) | ((_13 & -4503599627370496L) >> 52);
		this._21 = (this._21 & -4096L) | ((_22 & -4503599627370496L) >> 52);
		this._1 = (this._1 & -4096L) | ((_2 & -4503599627370496L) >> 52);
		this._10 = (this._10 & -4096L) | ((_11 & -4503599627370496L) >> 52);
		this._19 = (this._19 & -4096L) | ((_20 & -4503599627370496L) >> 52);
		this._2 = this._2 & -1152640029630136321L;
		this._4 = this._4 & -17587891077121L;
		this._6 = this._6 & -268369921L;
		this._8 = this._8 & -4096L;
		this._11 = this._11 & -1152640029630136321L;
		this._13 = this._13 & -17587891077121L;
		this._15 = this._15 & -268369921L;
		this._17 = this._17 & -4096L;
		this._20 = this._20 & -1152640029630136321L;
		this._22 = this._22 & -17587891077121L;
		this._24 = this._24 & -268369921L;
		this._26 = this._26 & -4096L;
	}

	public void offsetZ(int amount) {
		amount = Math.max(-DEPTH, Math.min(DEPTH, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {

		this.offsetPZ4_0();
	}
	protected void offsetPZ4_0() {
		this._26 = this._17;
		this._24 = this._15;
		this._22 = this._13;
		this._20 = this._11;
		this._17 = this._8;
		this._15 = this._6;
		this._13 = this._4;
		this._11 = this._2;
		this._19 = this._10;
		this._10 = this._1;
		this._21 = this._12;
		this._12 = this._3;
		this._23 = this._14;
		this._14 = this._5;
		this._25 = this._16;
		this._16 = this._7;
		this._18 = this._9;
		this._9 = this._0;
		this._8 = 0;
		this._6 = 0;
		this._4 = 0;
		this._2 = 0;
		this._1 = 0;
		this._3 = 0;
		this._5 = 0;
		this._7 = 0;
		this._0 = 0;
	}
	protected void offsetPZ2() {
		long _15 = this._15;
		long _6 = this._6;
		long _17 = this._17;
		long _8 = this._8;
		long _19 = this._19;
		long _10 = this._10;
		long _21 = this._21;
		long _12 = this._12;
		long _14 = this._14;
		long _5 = this._5;
		long _20 = this._20;
		long _16 = this._16;
		long _11 = this._11;
		long _7 = this._7;
		long _18 = this._18;
		long _13 = this._13;
		long _9 = this._9;
		this.offsetPZ2_0(_15, _6, _17, _8, _19, _10, _21, _12, _14, _5, _20, _16, _11, _7, _18, _13, _9);
	}
	protected void offsetPZ2_0(long _15, long _6, long _17, long _8, long _19, long _10, long _21, long _12, long _14, long _5, long _20, long _16, long _11, long _7, long _18, long _13, long _9) {
		this._26 = (this._26 & -4294967296L) | ((this._22 & -4294967296L) >> 32);
		this._24 = (this._24 & -4294967296L) | ((this._20 & -4294967296L) >> 32);
		this._22 = (this._22 & 4294967295L) | ((this._17 & 4294967295L) << 32);
		this._20 = (this._20 & 4294967295L) | ((this._15 & 4294967295L) << 32);
		this._17 = (this._17 & -4294967296L) | ((this._13 & -4294967296L) >> 32);
		this._15 = (this._15 & -4294967296L) | ((this._11 & -4294967296L) >> 32);
		this._13 = (this._13 & 4294967295L) | ((this._8 & 4294967295L) << 32);
		this._11 = (this._11 & 4294967295L) | ((this._6 & 4294967295L) << 32);
		this._8 = (this._8 & -4294967296L) | ((this._4 & -4294967296L) >> 32);
		this._6 = (this._6 & -4294967296L) | ((this._2 & -4294967296L) >> 32);
		this._24 = (this._24 & 4294967295L) | ((this._19 & 4294967295L) << 32);
		this._19 = (this._19 & -4294967296L) | ((_15 & -4294967296L) >> 32);
		this._15 = (this._15 & 4294967295L) | ((this._10 & 4294967295L) << 32);
		this._10 = (this._10 & -4294967296L) | ((_6 & -4294967296L) >> 32);
		this._6 = (this._6 & 4294967295L) | ((this._1 & 4294967295L) << 32);
		this._26 = (this._26 & 4294967295L) | ((this._21 & 4294967295L) << 32);
		this._21 = (this._21 & -4294967296L) | ((_17 & -4294967296L) >> 32);
		this._17 = (this._17 & 4294967295L) | ((this._12 & 4294967295L) << 32);
		this._12 = (this._12 & -4294967296L) | ((_8 & -4294967296L) >> 32);
		this._8 = (this._8 & 4294967295L) | ((this._3 & 4294967295L) << 32);
		this._23 = (this._23 & -4294967296L) | ((_19 & -4294967296L) >> 32);
		this._19 = (this._19 & 4294967295L) | ((this._14 & 4294967295L) << 32);
		this._14 = (this._14 & -4294967296L) | ((_10 & -4294967296L) >> 32);
		this._10 = (this._10 & 4294967295L) | ((this._5 & 4294967295L) << 32);
		this._5 = (this._5 & -4294967296L) | ((this._1 & -4294967296L) >> 32);
		this._25 = (this._25 & -4294967296L) | ((_21 & -4294967296L) >> 32);
		this._21 = (this._21 & 4294967295L) | ((this._16 & 4294967295L) << 32);
		this._16 = (this._16 & -4294967296L) | ((_12 & -4294967296L) >> 32);
		this._12 = (this._12 & 4294967295L) | ((this._7 & 4294967295L) << 32);
		this._7 = (this._7 & -4294967296L) | ((this._3 & -4294967296L) >> 32);
		this._23 = (this._23 & 4294967295L) | ((this._18 & 4294967295L) << 32);
		this._18 = (this._18 & -4294967296L) | ((_14 & -4294967296L) >> 32);
		this._14 = (this._14 & 4294967295L) | ((this._9 & 4294967295L) << 32);
		this._9 = (this._9 & -4294967296L) | ((_5 & -4294967296L) >> 32);
		this._5 = (this._5 & 4294967295L) | ((this._0 & 4294967295L) << 32);
		this._25 = (this._25 & 4294967295L) | ((_20 & 4294967295L) << 32);
		this._20 = (this._20 & -4294967296L) | ((_16 & -4294967296L) >> 32);
		this._16 = (this._16 & 4294967295L) | ((_11 & 4294967295L) << 32);
		this._11 = (this._11 & -4294967296L) | ((_7 & -4294967296L) >> 32);
		this._7 = (this._7 & 4294967295L) | ((this._2 & 4294967295L) << 32);
		this._22 = (this._22 & -4294967296L) | ((_18 & -4294967296L) >> 32);
		this._18 = (this._18 & 4294967295L) | ((_13 & 4294967295L) << 32);
		this._13 = (this._13 & -4294967296L) | ((_9 & -4294967296L) >> 32);
		this._9 = (this._9 & 4294967295L) | ((this._4 & 4294967295L) << 32);
		this._4 = (this._4 & -4294967296L) | ((this._0 & -4294967296L) >> 32);
		this._4 = this._4 & 4294967295L;
		this._2 = 0;
		this._1 = 0;
		this._3 = 0;
		this._0 = 0;
	}
	protected void offsetPZ1() {
		long _17 = this._17;
		long _8 = this._8;
		long _19 = this._19;
		long _10 = this._10;
		long _21 = this._21;
		long _12 = this._12;
		long _3 = this._3;
		long _23 = this._23;
		long _14 = this._14;
		long _5 = this._5;
		long _16 = this._16;
		long _7 = this._7;
		long _20 = this._20;
		long _18 = this._18;
		long _11 = this._11;
		long _9 = this._9;
		long _22 = this._22;
		long _13 = this._13;
		long _4 = this._4;
		long _15 = this._15;
		long _6 = this._6;
		this.offsetPZ1_0(_17, _8, _19, _10, _21, _12, _3, _23, _14, _5, _16, _7, _20, _18, _11, _9, _22, _13, _4, _15, _6);
	}
	protected void offsetPZ1_0(long _17, long _8, long _19, long _10, long _21, long _12, long _3, long _23, long _14, long _5, long _16, long _7, long _20, long _18, long _11, long _9, long _22, long _13, long _4, long _15, long _6) {
		this._26 = (this._26 & -281474976710656L) | ((this._24 & -65536L) >> 16);
		this._24 = (this._24 & -281474976710656L) | ((this._22 & -65536L) >> 16);
		this._22 = (this._22 & -281474976710656L) | ((this._20 & -65536L) >> 16);
		this._20 = (this._20 & 281474976710655L) | ((this._17 & 65535L) << 48);
		this._17 = (this._17 & -281474976710656L) | ((this._15 & -65536L) >> 16);
		this._15 = (this._15 & -281474976710656L) | ((this._13 & -65536L) >> 16);
		this._13 = (this._13 & -281474976710656L) | ((this._11 & -65536L) >> 16);
		this._11 = (this._11 & 281474976710655L) | ((this._8 & 65535L) << 48);
		this._8 = (this._8 & -281474976710656L) | ((this._6 & -65536L) >> 16);
		this._6 = (this._6 & -281474976710656L) | ((this._4 & -65536L) >> 16);
		this._4 = (this._4 & -281474976710656L) | ((this._2 & -65536L) >> 16);
		this._22 = (this._22 & 281474976710655L) | ((this._19 & 65535L) << 48);
		this._19 = (this._19 & -281474976710656L) | ((_17 & -65536L) >> 16);
		this._13 = (this._13 & 281474976710655L) | ((this._10 & 65535L) << 48);
		this._10 = (this._10 & -281474976710656L) | ((_8 & -65536L) >> 16);
		this._4 = (this._4 & 281474976710655L) | ((this._1 & 65535L) << 48);
		this._24 = (this._24 & 281474976710655L) | ((this._21 & 65535L) << 48);
		this._21 = (this._21 & -281474976710656L) | ((_19 & -65536L) >> 16);
		this._15 = (this._15 & 281474976710655L) | ((this._12 & 65535L) << 48);
		this._12 = (this._12 & -281474976710656L) | ((_10 & -65536L) >> 16);
		this._6 = (this._6 & 281474976710655L) | ((this._3 & 65535L) << 48);
		this._3 = (this._3 & -281474976710656L) | ((this._1 & -65536L) >> 16);
		this._26 = (this._26 & 281474976710655L) | ((this._23 & 65535L) << 48);
		this._23 = (this._23 & -281474976710656L) | ((_21 & -65536L) >> 16);
		this._17 = (this._17 & 281474976710655L) | ((this._14 & 65535L) << 48);
		this._14 = (this._14 & -281474976710656L) | ((_12 & -65536L) >> 16);
		this._8 = (this._8 & 281474976710655L) | ((this._5 & 65535L) << 48);
		this._5 = (this._5 & -281474976710656L) | ((_3 & -65536L) >> 16);
		this._25 = (this._25 & -281474976710656L) | ((_23 & -65536L) >> 16);
		this._19 = (this._19 & 281474976710655L) | ((this._16 & 65535L) << 48);
		this._16 = (this._16 & -281474976710656L) | ((_14 & -65536L) >> 16);
		this._10 = (this._10 & 281474976710655L) | ((this._7 & 65535L) << 48);
		this._7 = (this._7 & -281474976710656L) | ((_5 & -65536L) >> 16);
		this._21 = (this._21 & 281474976710655L) | ((this._18 & 65535L) << 48);
		this._18 = (this._18 & -281474976710656L) | ((_16 & -65536L) >> 16);
		this._12 = (this._12 & 281474976710655L) | ((this._9 & 65535L) << 48);
		this._9 = (this._9 & -281474976710656L) | ((_7 & -65536L) >> 16);
		this._3 = (this._3 & 281474976710655L) | ((this._0 & 65535L) << 48);
		this._23 = (this._23 & 281474976710655L) | ((_20 & 65535L) << 48);
		this._20 = (this._20 & -281474976710656L) | ((_18 & -65536L) >> 16);
		this._14 = (this._14 & 281474976710655L) | ((_11 & 65535L) << 48);
		this._11 = (this._11 & -281474976710656L) | ((_9 & -65536L) >> 16);
		this._5 = (this._5 & 281474976710655L) | ((this._2 & 65535L) << 48);
		this._2 = (this._2 & -281474976710656L) | ((this._0 & -65536L) >> 16);
		this._25 = (this._25 & 281474976710655L) | ((_22 & 65535L) << 48);
		this._16 = (this._16 & 281474976710655L) | ((_13 & 65535L) << 48);
		this._7 = (this._7 & 281474976710655L) | ((_4 & 65535L) << 48);
		this._18 = (this._18 & 281474976710655L) | ((_15 & 65535L) << 48);
		this._9 = (this._9 & 281474976710655L) | ((_6 & 65535L) << 48);
		this._2 = this._2 & 281474976710655L;
		this._1 = 0;
		this._0 = 0;
	}
	protected void offsetNZ4() {

		this.offsetNZ4_0();
	}
	protected void offsetNZ4_0() {
		this._0 = this._9;
		this._2 = this._11;
		this._4 = this._13;
		this._6 = this._15;
		this._9 = this._18;
		this._11 = this._20;
		this._13 = this._22;
		this._15 = this._24;
		this._7 = this._16;
		this._16 = this._25;
		this._5 = this._14;
		this._14 = this._23;
		this._3 = this._12;
		this._12 = this._21;
		this._1 = this._10;
		this._10 = this._19;
		this._8 = this._17;
		this._17 = this._26;
		this._18 = 0;
		this._20 = 0;
		this._22 = 0;
		this._24 = 0;
		this._25 = 0;
		this._23 = 0;
		this._21 = 0;
		this._19 = 0;
		this._26 = 0;
	}
	protected void offsetNZ2() {
		long _11 = this._11;
		long _20 = this._20;
		long _9 = this._9;
		long _18 = this._18;
		long _7 = this._7;
		long _16 = this._16;
		long _5 = this._5;
		long _14 = this._14;
		long _12 = this._12;
		long _21 = this._21;
		long _6 = this._6;
		long _10 = this._10;
		long _15 = this._15;
		long _19 = this._19;
		long _8 = this._8;
		long _13 = this._13;
		long _17 = this._17;
		this.offsetNZ2_0(_11, _20, _9, _18, _7, _16, _5, _14, _12, _21, _6, _10, _15, _19, _8, _13, _17);
	}
	protected void offsetNZ2_0(long _11, long _20, long _9, long _18, long _7, long _16, long _5, long _14, long _12, long _21, long _6, long _10, long _15, long _19, long _8, long _13, long _17) {
		this._0 = (this._0 & 4294967295L) | ((this._4 & 4294967295L) << 32);
		this._2 = (this._2 & 4294967295L) | ((this._6 & 4294967295L) << 32);
		this._4 = (this._4 & -4294967296L) | ((this._9 & -4294967296L) >> 32);
		this._6 = (this._6 & -4294967296L) | ((this._11 & -4294967296L) >> 32);
		this._9 = (this._9 & 4294967295L) | ((this._13 & 4294967295L) << 32);
		this._11 = (this._11 & 4294967295L) | ((this._15 & 4294967295L) << 32);
		this._13 = (this._13 & -4294967296L) | ((this._18 & -4294967296L) >> 32);
		this._15 = (this._15 & -4294967296L) | ((this._20 & -4294967296L) >> 32);
		this._18 = (this._18 & 4294967295L) | ((this._22 & 4294967295L) << 32);
		this._20 = (this._20 & 4294967295L) | ((this._24 & 4294967295L) << 32);
		this._2 = (this._2 & -4294967296L) | ((this._7 & -4294967296L) >> 32);
		this._7 = (this._7 & 4294967295L) | ((_11 & 4294967295L) << 32);
		this._11 = (this._11 & -4294967296L) | ((this._16 & -4294967296L) >> 32);
		this._16 = (this._16 & 4294967295L) | ((_20 & 4294967295L) << 32);
		this._20 = (this._20 & -4294967296L) | ((this._25 & -4294967296L) >> 32);
		this._0 = (this._0 & -4294967296L) | ((this._5 & -4294967296L) >> 32);
		this._5 = (this._5 & 4294967295L) | ((_9 & 4294967295L) << 32);
		this._9 = (this._9 & -4294967296L) | ((this._14 & -4294967296L) >> 32);
		this._14 = (this._14 & 4294967295L) | ((_18 & 4294967295L) << 32);
		this._18 = (this._18 & -4294967296L) | ((this._23 & -4294967296L) >> 32);
		this._3 = (this._3 & 4294967295L) | ((_7 & 4294967295L) << 32);
		this._7 = (this._7 & -4294967296L) | ((this._12 & -4294967296L) >> 32);
		this._12 = (this._12 & 4294967295L) | ((_16 & 4294967295L) << 32);
		this._16 = (this._16 & -4294967296L) | ((this._21 & -4294967296L) >> 32);
		this._21 = (this._21 & 4294967295L) | ((this._25 & 4294967295L) << 32);
		this._1 = (this._1 & 4294967295L) | ((_5 & 4294967295L) << 32);
		this._5 = (this._5 & -4294967296L) | ((this._10 & -4294967296L) >> 32);
		this._10 = (this._10 & 4294967295L) | ((_14 & 4294967295L) << 32);
		this._14 = (this._14 & -4294967296L) | ((this._19 & -4294967296L) >> 32);
		this._19 = (this._19 & 4294967295L) | ((this._23 & 4294967295L) << 32);
		this._3 = (this._3 & -4294967296L) | ((this._8 & -4294967296L) >> 32);
		this._8 = (this._8 & 4294967295L) | ((_12 & 4294967295L) << 32);
		this._12 = (this._12 & -4294967296L) | ((this._17 & -4294967296L) >> 32);
		this._17 = (this._17 & 4294967295L) | ((_21 & 4294967295L) << 32);
		this._21 = (this._21 & -4294967296L) | ((this._26 & -4294967296L) >> 32);
		this._1 = (this._1 & -4294967296L) | ((_6 & -4294967296L) >> 32);
		this._6 = (this._6 & 4294967295L) | ((_10 & 4294967295L) << 32);
		this._10 = (this._10 & -4294967296L) | ((_15 & -4294967296L) >> 32);
		this._15 = (this._15 & 4294967295L) | ((_19 & 4294967295L) << 32);
		this._19 = (this._19 & -4294967296L) | ((this._24 & -4294967296L) >> 32);
		this._4 = (this._4 & 4294967295L) | ((_8 & 4294967295L) << 32);
		this._8 = (this._8 & -4294967296L) | ((_13 & -4294967296L) >> 32);
		this._13 = (this._13 & 4294967295L) | ((_17 & 4294967295L) << 32);
		this._17 = (this._17 & -4294967296L) | ((this._22 & -4294967296L) >> 32);
		this._22 = (this._22 & 4294967295L) | ((this._26 & 4294967295L) << 32);
		this._22 = this._22 & -4294967296L;
		this._24 = 0;
		this._25 = 0;
		this._23 = 0;
		this._26 = 0;
	}
	protected void offsetNZ1() {
		long _9 = this._9;
		long _18 = this._18;
		long _7 = this._7;
		long _16 = this._16;
		long _5 = this._5;
		long _14 = this._14;
		long _23 = this._23;
		long _3 = this._3;
		long _12 = this._12;
		long _21 = this._21;
		long _10 = this._10;
		long _19 = this._19;
		long _6 = this._6;
		long _8 = this._8;
		long _15 = this._15;
		long _17 = this._17;
		long _4 = this._4;
		long _13 = this._13;
		long _22 = this._22;
		long _11 = this._11;
		long _20 = this._20;
		this.offsetNZ1_0(_9, _18, _7, _16, _5, _14, _23, _3, _12, _21, _10, _19, _6, _8, _15, _17, _4, _13, _22, _11, _20);
	}
	protected void offsetNZ1_0(long _9, long _18, long _7, long _16, long _5, long _14, long _23, long _3, long _12, long _21, long _10, long _19, long _6, long _8, long _15, long _17, long _4, long _13, long _22, long _11, long _20) {
		this._0 = (this._0 & 65535L) | ((this._2 & 281474976710655L) << 16);
		this._2 = (this._2 & 65535L) | ((this._4 & 281474976710655L) << 16);
		this._4 = (this._4 & 65535L) | ((this._6 & 281474976710655L) << 16);
		this._6 = (this._6 & -65536L) | ((this._9 & -281474976710656L) >> 48);
		this._9 = (this._9 & 65535L) | ((this._11 & 281474976710655L) << 16);
		this._11 = (this._11 & 65535L) | ((this._13 & 281474976710655L) << 16);
		this._13 = (this._13 & 65535L) | ((this._15 & 281474976710655L) << 16);
		this._15 = (this._15 & -65536L) | ((this._18 & -281474976710656L) >> 48);
		this._18 = (this._18 & 65535L) | ((this._20 & 281474976710655L) << 16);
		this._20 = (this._20 & 65535L) | ((this._22 & 281474976710655L) << 16);
		this._22 = (this._22 & 65535L) | ((this._24 & 281474976710655L) << 16);
		this._4 = (this._4 & -65536L) | ((this._7 & -281474976710656L) >> 48);
		this._7 = (this._7 & 65535L) | ((_9 & 281474976710655L) << 16);
		this._13 = (this._13 & -65536L) | ((this._16 & -281474976710656L) >> 48);
		this._16 = (this._16 & 65535L) | ((_18 & 281474976710655L) << 16);
		this._22 = (this._22 & -65536L) | ((this._25 & -281474976710656L) >> 48);
		this._2 = (this._2 & -65536L) | ((this._5 & -281474976710656L) >> 48);
		this._5 = (this._5 & 65535L) | ((_7 & 281474976710655L) << 16);
		this._11 = (this._11 & -65536L) | ((this._14 & -281474976710656L) >> 48);
		this._14 = (this._14 & 65535L) | ((_16 & 281474976710655L) << 16);
		this._20 = (this._20 & -65536L) | ((this._23 & -281474976710656L) >> 48);
		this._23 = (this._23 & 65535L) | ((this._25 & 281474976710655L) << 16);
		this._0 = (this._0 & -65536L) | ((this._3 & -281474976710656L) >> 48);
		this._3 = (this._3 & 65535L) | ((_5 & 281474976710655L) << 16);
		this._9 = (this._9 & -65536L) | ((this._12 & -281474976710656L) >> 48);
		this._12 = (this._12 & 65535L) | ((_14 & 281474976710655L) << 16);
		this._18 = (this._18 & -65536L) | ((this._21 & -281474976710656L) >> 48);
		this._21 = (this._21 & 65535L) | ((_23 & 281474976710655L) << 16);
		this._1 = (this._1 & 65535L) | ((_3 & 281474976710655L) << 16);
		this._7 = (this._7 & -65536L) | ((this._10 & -281474976710656L) >> 48);
		this._10 = (this._10 & 65535L) | ((_12 & 281474976710655L) << 16);
		this._16 = (this._16 & -65536L) | ((this._19 & -281474976710656L) >> 48);
		this._19 = (this._19 & 65535L) | ((_21 & 281474976710655L) << 16);
		this._5 = (this._5 & -65536L) | ((this._8 & -281474976710656L) >> 48);
		this._8 = (this._8 & 65535L) | ((_10 & 281474976710655L) << 16);
		this._14 = (this._14 & -65536L) | ((this._17 & -281474976710656L) >> 48);
		this._17 = (this._17 & 65535L) | ((_19 & 281474976710655L) << 16);
		this._23 = (this._23 & -65536L) | ((this._26 & -281474976710656L) >> 48);
		this._3 = (this._3 & -65536L) | ((_6 & -281474976710656L) >> 48);
		this._6 = (this._6 & 65535L) | ((_8 & 281474976710655L) << 16);
		this._12 = (this._12 & -65536L) | ((_15 & -281474976710656L) >> 48);
		this._15 = (this._15 & 65535L) | ((_17 & 281474976710655L) << 16);
		this._21 = (this._21 & -65536L) | ((this._24 & -281474976710656L) >> 48);
		this._24 = (this._24 & 65535L) | ((this._26 & 281474976710655L) << 16);
		this._1 = (this._1 & -65536L) | ((_4 & -281474976710656L) >> 48);
		this._10 = (this._10 & -65536L) | ((_13 & -281474976710656L) >> 48);
		this._19 = (this._19 & -65536L) | ((_22 & -281474976710656L) >> 48);
		this._8 = (this._8 & -65536L) | ((_11 & -281474976710656L) >> 48);
		this._17 = (this._17 & -65536L) | ((_20 & -281474976710656L) >> 48);
		this._24 = this._24 & -65536L;
		this._25 = 0;
		this._26 = 0;
	}

	public boolean isIntersecting(BitField that0) {
		if(!(that0 instanceof BitField12x12x12))
			return super.isIntersecting(that0);
		var that = (BitField12x12x12) that0;
		if(this.isIntersecting_0(that)) return true;
		if(this.isIntersecting_1(that)) return true;
		return false;
	}
	protected boolean isIntersecting_0(BitField12x12x12 that) {
		if((this._0 & that._0) != 0) return true;
		if((this._1 & that._1) != 0) return true;
		if((this._2 & that._2) != 0) return true;
		if((this._3 & that._3) != 0) return true;
		if((this._4 & that._4) != 0) return true;
		if((this._5 & that._5) != 0) return true;
		if((this._6 & that._6) != 0) return true;
		if((this._7 & that._7) != 0) return true;
		if((this._8 & that._8) != 0) return true;
		if((this._9 & that._9) != 0) return true;
		if((this._10 & that._10) != 0) return true;
		if((this._11 & that._11) != 0) return true;
		if((this._12 & that._12) != 0) return true;
		if((this._13 & that._13) != 0) return true;
		if((this._14 & that._14) != 0) return true;
		if((this._15 & that._15) != 0) return true;
		return false;
	}
	protected boolean isIntersecting_1(BitField12x12x12 that) {
		if((this._16 & that._16) != 0) return true;
		if((this._17 & that._17) != 0) return true;
		if((this._18 & that._18) != 0) return true;
		if((this._19 & that._19) != 0) return true;
		if((this._20 & that._20) != 0) return true;
		if((this._21 & that._21) != 0) return true;
		if((this._22 & that._22) != 0) return true;
		if((this._23 & that._23) != 0) return true;
		if((this._24 & that._24) != 0) return true;
		if((this._25 & that._25) != 0) return true;
		if((this._26 & that._26) != 0) return true;
		return false;
	}

	public void complement() {
		this.complement_0();
		this.complement_1();
	}
	protected void complement_0() {
		this._0 = ~this._0;
		this._1 = ~this._1;
		this._2 = ~this._2;
		this._3 = ~this._3;
		this._4 = ~this._4;
		this._5 = ~this._5;
		this._6 = ~this._6;
		this._7 = ~this._7;
		this._8 = ~this._8;
		this._9 = ~this._9;
		this._10 = ~this._10;
		this._11 = ~this._11;
		this._12 = ~this._12;
		this._13 = ~this._13;
		this._14 = ~this._14;
		this._15 = ~this._15;
	}
	protected void complement_1() {
		this._16 = ~this._16;
		this._17 = ~this._17;
		this._18 = ~this._18;
		this._19 = ~this._19;
		this._20 = ~this._20;
		this._21 = ~this._21;
		this._22 = ~this._22;
		this._23 = ~this._23;
		this._24 = ~this._24;
		this._25 = ~this._25;
		this._26 = ~this._26;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField12x12x12)) {
			super.union(that0);
			return;
		}
		var that = (BitField12x12x12) that0;
		this.union_0(that);
		this.union_1(that);
	}
	protected void union_0(BitField12x12x12 that) {
		this._0 |= that._0;
		this._1 |= that._1;
		this._2 |= that._2;
		this._3 |= that._3;
		this._4 |= that._4;
		this._5 |= that._5;
		this._6 |= that._6;
		this._7 |= that._7;
		this._8 |= that._8;
		this._9 |= that._9;
		this._10 |= that._10;
		this._11 |= that._11;
		this._12 |= that._12;
		this._13 |= that._13;
		this._14 |= that._14;
		this._15 |= that._15;
	}
	protected void union_1(BitField12x12x12 that) {
		this._16 |= that._16;
		this._17 |= that._17;
		this._18 |= that._18;
		this._19 |= that._19;
		this._20 |= that._20;
		this._21 |= that._21;
		this._22 |= that._22;
		this._23 |= that._23;
		this._24 |= that._24;
		this._25 |= that._25;
		this._26 |= that._26;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField12x12x12)) {
			super.union(that0);
			return;
		}
		var that = (BitField12x12x12) that0;
		this.intersect_0(that);
		this.intersect_1(that);
	}
	protected void intersect_0(BitField12x12x12 that) {
		this._0 &= that._0;
		this._1 &= that._1;
		this._2 &= that._2;
		this._3 &= that._3;
		this._4 &= that._4;
		this._5 &= that._5;
		this._6 &= that._6;
		this._7 &= that._7;
		this._8 &= that._8;
		this._9 &= that._9;
		this._10 &= that._10;
		this._11 &= that._11;
		this._12 &= that._12;
		this._13 &= that._13;
		this._14 &= that._14;
		this._15 &= that._15;
	}
	protected void intersect_1(BitField12x12x12 that) {
		this._16 &= that._16;
		this._17 &= that._17;
		this._18 &= that._18;
		this._19 &= that._19;
		this._20 &= that._20;
		this._21 &= that._21;
		this._22 &= that._22;
		this._23 &= that._23;
		this._24 &= that._24;
		this._25 &= that._25;
		this._26 &= that._26;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField12x12x12)) {
			super.union(that0);
			return;
		}
		var that = (BitField12x12x12) that0;
		this.exclusive_0(that);
		this.exclusive_1(that);
	}
	protected void exclusive_0(BitField12x12x12 that) {
		this._0 ^= that._0;
		this._1 ^= that._1;
		this._2 ^= that._2;
		this._3 ^= that._3;
		this._4 ^= that._4;
		this._5 ^= that._5;
		this._6 ^= that._6;
		this._7 ^= that._7;
		this._8 ^= that._8;
		this._9 ^= that._9;
		this._10 ^= that._10;
		this._11 ^= that._11;
		this._12 ^= that._12;
		this._13 ^= that._13;
		this._14 ^= that._14;
		this._15 ^= that._15;
	}
	protected void exclusive_1(BitField12x12x12 that) {
		this._16 ^= that._16;
		this._17 ^= that._17;
		this._18 ^= that._18;
		this._19 ^= that._19;
		this._20 ^= that._20;
		this._21 ^= that._21;
		this._22 ^= that._22;
		this._23 ^= that._23;
		this._24 ^= that._24;
		this._25 ^= that._25;
		this._26 ^= that._26;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField12x12x12)) {
			super.union(that0);
			return;
		}
		var that = (BitField12x12x12) that0;
		this.subtract_0(that);
		this.subtract_1(that);
	}
	protected void subtract_0(BitField12x12x12 that) {
		this._0 &= ~that._0;
		this._1 &= ~that._1;
		this._2 &= ~that._2;
		this._3 &= ~that._3;
		this._4 &= ~that._4;
		this._5 &= ~that._5;
		this._6 &= ~that._6;
		this._7 &= ~that._7;
		this._8 &= ~that._8;
		this._9 &= ~that._9;
		this._10 &= ~that._10;
		this._11 &= ~that._11;
		this._12 &= ~that._12;
		this._13 &= ~that._13;
		this._14 &= ~that._14;
		this._15 &= ~that._15;
	}
	protected void subtract_1(BitField12x12x12 that) {
		this._16 &= ~that._16;
		this._17 &= ~that._17;
		this._18 &= ~that._18;
		this._19 &= ~that._19;
		this._20 &= ~that._20;
		this._21 &= ~that._21;
		this._22 &= ~that._22;
		this._23 &= ~that._23;
		this._24 &= ~that._24;
		this._25 &= ~that._25;
		this._26 &= ~that._26;
	}


}
