
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045;

public class BitField8x8x1 implements BitField {
	public static final int WIDTH = 8;
	public static final int HEIGHT = 8;
	public static final int DEPTH = 1;
	protected long _0;

	public int getWidth() {
		return WIDTH;
	}
	public int getHeight() {
		return HEIGHT;
	}
	public int getDepth() {
		return DEPTH;
	}

	public boolean getValue(int x, int y, int z) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) return this.getValue0(position);
		assert false;
		return false;
	}
	protected boolean getValue0(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 64) return (this._0 & mask) != 0;
		assert false;
		return false;
	}

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue0(position, v); return; }
		assert false;
	}
	protected void setValue0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		assert false;
	}

	public void set(BitField that0) {
		if(!(that0 instanceof BitField8x8x1)) {
			BitField.super.set(that0);
			return;
		}
		var that = (BitField8x8x1) that0;
		this.set0(that);
	}
	protected void set0(BitField8x8x1 that) {
		this._0 = that._0;
	}

	public BitField8x8x1 clone() {
		var result = new BitField8x8x1();
		result.set(this);
		return result;
	}

	public void offsetX(int amount) {
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {
		this.offsetPX4_0();
	}
	protected void offsetPX4_0() {
		this._0 = (this._0 & -1085102592571150096L) | (this._0 & -1085102592571150096L >> 4);
	}
	protected void offsetPX2() {
		this.offsetPX2_0();
	}
	protected void offsetPX2_0() {
		this._0 = (this._0 & -4557430888798830400L) | (this._0 & -217020518514230020L >> 2);
	}
	protected void offsetPX1() {
		this.offsetPX1_0();
	}
	protected void offsetPX1_0() {
		this._0 = (this._0 & -9187201950435737472L) | (this._0 & -72340172838076674L >> 1);
	}
	protected void offsetNX4() {
		this.offsetNX4_0();
	}
	protected void offsetNX4_0() {
		this._0 = (this._0 & 1085102592571150095L) | (this._0 & 1085102592571150095L << 4);
	}
	protected void offsetNX2() {
		this.offsetNX2_0();
	}
	protected void offsetNX2_0() {
		this._0 = (this._0 & 217020518514230019L) | (this._0 & 4557430888798830399L << 2);
	}
	protected void offsetNX1() {
		this.offsetNX1_0();
	}
	protected void offsetNX1_0() {
		this._0 = (this._0 & 72340172838076673L) | (this._0 & 9187201950435737471L << 1);
	}

	public void offsetY(int amount) {
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {
		this.offsetPY4_0();
	}
	protected void offsetPY4_0() {
		this._0 = (this._0 & -4294967296L) | (this._0 & -4294967296L >> 32);
	}
	protected void offsetPY2() {
		this.offsetPY2_0();
	}
	protected void offsetPY2_0() {
		this._0 = (this._0 & -281474976710656L) | (this._0 & -65536L >> 16);
	}
	protected void offsetPY1() {
		this.offsetPY1_0();
	}
	protected void offsetPY1_0() {
		this._0 = (this._0 & -72057594037927936L) | (this._0 & -256L >> 8);
	}
	protected void offsetNY4() {
		this.offsetNY4_0();
	}
	protected void offsetNY4_0() {
		this._0 = (this._0 & 4294967295L) | (this._0 & 4294967295L << 32);
	}
	protected void offsetNY2() {
		this.offsetNY2_0();
	}
	protected void offsetNY2_0() {
		this._0 = (this._0 & 65535L) | (this._0 & 281474976710655L << 16);
	}
	protected void offsetNY1() {
		this.offsetNY1_0();
	}
	protected void offsetNY1_0() {
		this._0 = (this._0 & 255L) | (this._0 & 72057594037927935L << 8);
	}

	public void offsetZ(int amount) {
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {

	}

	protected void offsetPZ2() {

	}

	protected void offsetPZ1() {

	}

	protected void offsetNZ4() {

	}

	protected void offsetNZ2() {

	}

	protected void offsetNZ1() {

	}


	public boolean isIntersecting(BitField that0) {
		if(!(that0 instanceof BitField8x8x1))
			return BitField.super.isIntersecting(that0);
		var that = (BitField8x8x1) that0;
		if(this.isIntersecting0(that)) return true;
		return false;
	}
	protected boolean isIntersecting0(BitField8x8x1 that) {
		if((this._0 & that._0) != 0) return true;
		return false;
	}

	public void complement() {
		this.complement0();
	}
	protected void complement0() {
		this._0 = ~this._0;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField8x8x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x1) that0;
		this.union0(that);
	}
	protected void union0(BitField8x8x1 that) {
		this._0 |= that._0;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField8x8x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x1) that0;
		this.intersect0(that);
	}
	protected void intersect0(BitField8x8x1 that) {
		this._0 &= that._0;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField8x8x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x1) that0;
		this.exclusive0(that);
	}
	protected void exclusive0(BitField8x8x1 that) {
		this._0 ^= that._0;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField8x8x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x1) that0;
		this.subtract0(that);
	}
	protected void subtract0(BitField8x8x1 that) {
		this._0 &= ~that._0;
	}


}
