
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045;

public class BitField32x32x1 implements BitField {
	public static final int WIDTH = 32;
	public static final int HEIGHT = 32;
	public static final int DEPTH = 1;
	protected long _0;
	protected long _1;
	protected long _2;
	protected long _3;
	protected long _4;
	protected long _5;
	protected long _6;
	protected long _7;
	protected long _8;
	protected long _9;
	protected long _10;
	protected long _11;
	protected long _12;
	protected long _13;
	protected long _14;
	protected long _15;

	public int getWidth() {
		return WIDTH;
	}
	public int getHeight() {
		return HEIGHT;
	}
	public int getDepth() {
		return DEPTH;
	}

	public boolean getValue(int x, int y, int z) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) return this.getValue0(position);
		assert false;
		return false;
	}
	protected boolean getValue0(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 64) return (this._0 & mask) != 0;
		if(position < 128) return (this._1 & mask) != 0;
		if(position < 192) return (this._2 & mask) != 0;
		if(position < 256) return (this._3 & mask) != 0;
		if(position < 320) return (this._4 & mask) != 0;
		if(position < 384) return (this._5 & mask) != 0;
		if(position < 448) return (this._6 & mask) != 0;
		if(position < 512) return (this._7 & mask) != 0;
		if(position < 576) return (this._8 & mask) != 0;
		if(position < 640) return (this._9 & mask) != 0;
		if(position < 704) return (this._10 & mask) != 0;
		if(position < 768) return (this._11 & mask) != 0;
		if(position < 832) return (this._12 & mask) != 0;
		if(position < 896) return (this._13 & mask) != 0;
		if(position < 960) return (this._14 & mask) != 0;
		if(position < 1024) return (this._15 & mask) != 0;
		assert false;
		return false;
	}

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue0(position, v); return; }
		assert false;
	}
	protected void setValue0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		if(position < 128) { this._1 = (this._1 & mask) | value; return; }
		if(position < 192) { this._2 = (this._2 & mask) | value; return; }
		if(position < 256) { this._3 = (this._3 & mask) | value; return; }
		if(position < 320) { this._4 = (this._4 & mask) | value; return; }
		if(position < 384) { this._5 = (this._5 & mask) | value; return; }
		if(position < 448) { this._6 = (this._6 & mask) | value; return; }
		if(position < 512) { this._7 = (this._7 & mask) | value; return; }
		if(position < 576) { this._8 = (this._8 & mask) | value; return; }
		if(position < 640) { this._9 = (this._9 & mask) | value; return; }
		if(position < 704) { this._10 = (this._10 & mask) | value; return; }
		if(position < 768) { this._11 = (this._11 & mask) | value; return; }
		if(position < 832) { this._12 = (this._12 & mask) | value; return; }
		if(position < 896) { this._13 = (this._13 & mask) | value; return; }
		if(position < 960) { this._14 = (this._14 & mask) | value; return; }
		if(position < 1024) { this._15 = (this._15 & mask) | value; return; }
		assert false;
	}

	public void offsetX(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {
		this.offsetPX4A();
		this.offsetPX4B();
	}
	protected void offsetPX4A() {
		this._0 = (this._0 & -268435456L) | ((this._0 >> 4) & 268435455L);
		this._0 = (this._0 & -1152921500311879681L) | ((this._0 >> 4) & 1152921500311879680L);
		this._1 = (this._1 & -268435456L) | ((this._1 >> 4) & 268435455L);
		this._1 = (this._1 & -1152921500311879681L) | ((this._1 >> 4) & 1152921500311879680L);
		this._2 = (this._2 & -268435456L) | ((this._2 >> 4) & 268435455L);
		this._2 = (this._2 & -1152921500311879681L) | ((this._2 >> 4) & 1152921500311879680L);
		this._3 = (this._3 & -268435456L) | ((this._3 >> 4) & 268435455L);
		this._3 = (this._3 & -1152921500311879681L) | ((this._3 >> 4) & 1152921500311879680L);
		this._4 = (this._4 & -268435456L) | ((this._4 >> 4) & 268435455L);
		this._4 = (this._4 & -1152921500311879681L) | ((this._4 >> 4) & 1152921500311879680L);
		this._5 = (this._5 & -268435456L) | ((this._5 >> 4) & 268435455L);
		this._5 = (this._5 & -1152921500311879681L) | ((this._5 >> 4) & 1152921500311879680L);
		this._6 = (this._6 & -268435456L) | ((this._6 >> 4) & 268435455L);
		this._6 = (this._6 & -1152921500311879681L) | ((this._6 >> 4) & 1152921500311879680L);
		this._7 = (this._7 & -268435456L) | ((this._7 >> 4) & 268435455L);
		this._7 = (this._7 & -1152921500311879681L) | ((this._7 >> 4) & 1152921500311879680L);
	}
	protected void offsetPX4B() {
		this._8 = (this._8 & -268435456L) | ((this._8 >> 4) & 268435455L);
		this._8 = (this._8 & -1152921500311879681L) | ((this._8 >> 4) & 1152921500311879680L);
		this._9 = (this._9 & -268435456L) | ((this._9 >> 4) & 268435455L);
		this._9 = (this._9 & -1152921500311879681L) | ((this._9 >> 4) & 1152921500311879680L);
		this._10 = (this._10 & -268435456L) | ((this._10 >> 4) & 268435455L);
		this._10 = (this._10 & -1152921500311879681L) | ((this._10 >> 4) & 1152921500311879680L);
		this._11 = (this._11 & -268435456L) | ((this._11 >> 4) & 268435455L);
		this._11 = (this._11 & -1152921500311879681L) | ((this._11 >> 4) & 1152921500311879680L);
		this._12 = (this._12 & -268435456L) | ((this._12 >> 4) & 268435455L);
		this._12 = (this._12 & -1152921500311879681L) | ((this._12 >> 4) & 1152921500311879680L);
		this._13 = (this._13 & -268435456L) | ((this._13 >> 4) & 268435455L);
		this._13 = (this._13 & -1152921500311879681L) | ((this._13 >> 4) & 1152921500311879680L);
		this._14 = (this._14 & -268435456L) | ((this._14 >> 4) & 268435455L);
		this._14 = (this._14 & -1152921500311879681L) | ((this._14 >> 4) & 1152921500311879680L);
		this._15 = (this._15 & -268435456L) | ((this._15 >> 4) & 268435455L);
		this._15 = (this._15 & -1152921500311879681L) | ((this._15 >> 4) & 1152921500311879680L);
	}
	protected void offsetPX2() {
		this.offsetPX2A();
		this.offsetPX2B();
	}
	protected void offsetPX2A() {
		this._0 = (this._0 & -1073741824L) | ((this._0 >> 2) & 1073741823L);
		this._0 = (this._0 & -4611686014132420609L) | ((this._0 >> 2) & 4611686014132420608L);
		this._1 = (this._1 & -1073741824L) | ((this._1 >> 2) & 1073741823L);
		this._1 = (this._1 & -4611686014132420609L) | ((this._1 >> 2) & 4611686014132420608L);
		this._2 = (this._2 & -1073741824L) | ((this._2 >> 2) & 1073741823L);
		this._2 = (this._2 & -4611686014132420609L) | ((this._2 >> 2) & 4611686014132420608L);
		this._3 = (this._3 & -1073741824L) | ((this._3 >> 2) & 1073741823L);
		this._3 = (this._3 & -4611686014132420609L) | ((this._3 >> 2) & 4611686014132420608L);
		this._4 = (this._4 & -1073741824L) | ((this._4 >> 2) & 1073741823L);
		this._4 = (this._4 & -4611686014132420609L) | ((this._4 >> 2) & 4611686014132420608L);
		this._5 = (this._5 & -1073741824L) | ((this._5 >> 2) & 1073741823L);
		this._5 = (this._5 & -4611686014132420609L) | ((this._5 >> 2) & 4611686014132420608L);
		this._6 = (this._6 & -1073741824L) | ((this._6 >> 2) & 1073741823L);
		this._6 = (this._6 & -4611686014132420609L) | ((this._6 >> 2) & 4611686014132420608L);
		this._7 = (this._7 & -1073741824L) | ((this._7 >> 2) & 1073741823L);
		this._7 = (this._7 & -4611686014132420609L) | ((this._7 >> 2) & 4611686014132420608L);
	}
	protected void offsetPX2B() {
		this._8 = (this._8 & -1073741824L) | ((this._8 >> 2) & 1073741823L);
		this._8 = (this._8 & -4611686014132420609L) | ((this._8 >> 2) & 4611686014132420608L);
		this._9 = (this._9 & -1073741824L) | ((this._9 >> 2) & 1073741823L);
		this._9 = (this._9 & -4611686014132420609L) | ((this._9 >> 2) & 4611686014132420608L);
		this._10 = (this._10 & -1073741824L) | ((this._10 >> 2) & 1073741823L);
		this._10 = (this._10 & -4611686014132420609L) | ((this._10 >> 2) & 4611686014132420608L);
		this._11 = (this._11 & -1073741824L) | ((this._11 >> 2) & 1073741823L);
		this._11 = (this._11 & -4611686014132420609L) | ((this._11 >> 2) & 4611686014132420608L);
		this._12 = (this._12 & -1073741824L) | ((this._12 >> 2) & 1073741823L);
		this._12 = (this._12 & -4611686014132420609L) | ((this._12 >> 2) & 4611686014132420608L);
		this._13 = (this._13 & -1073741824L) | ((this._13 >> 2) & 1073741823L);
		this._13 = (this._13 & -4611686014132420609L) | ((this._13 >> 2) & 4611686014132420608L);
		this._14 = (this._14 & -1073741824L) | ((this._14 >> 2) & 1073741823L);
		this._14 = (this._14 & -4611686014132420609L) | ((this._14 >> 2) & 4611686014132420608L);
		this._15 = (this._15 & -1073741824L) | ((this._15 >> 2) & 1073741823L);
		this._15 = (this._15 & -4611686014132420609L) | ((this._15 >> 2) & 4611686014132420608L);
	}
	protected void offsetPX1() {
		this.offsetPX1A();
		this.offsetPX1B();
	}
	protected void offsetPX1A() {
		this._0 = (this._0 & -2147483648L) | ((this._0 >> 1) & 2147483647L);
		this._0 = (this._0 & -9223372032559808513L) | ((this._0 >> 1) & 9223372032559808512L);
		this._1 = (this._1 & -2147483648L) | ((this._1 >> 1) & 2147483647L);
		this._1 = (this._1 & -9223372032559808513L) | ((this._1 >> 1) & 9223372032559808512L);
		this._2 = (this._2 & -2147483648L) | ((this._2 >> 1) & 2147483647L);
		this._2 = (this._2 & -9223372032559808513L) | ((this._2 >> 1) & 9223372032559808512L);
		this._3 = (this._3 & -2147483648L) | ((this._3 >> 1) & 2147483647L);
		this._3 = (this._3 & -9223372032559808513L) | ((this._3 >> 1) & 9223372032559808512L);
		this._4 = (this._4 & -2147483648L) | ((this._4 >> 1) & 2147483647L);
		this._4 = (this._4 & -9223372032559808513L) | ((this._4 >> 1) & 9223372032559808512L);
		this._5 = (this._5 & -2147483648L) | ((this._5 >> 1) & 2147483647L);
		this._5 = (this._5 & -9223372032559808513L) | ((this._5 >> 1) & 9223372032559808512L);
		this._6 = (this._6 & -2147483648L) | ((this._6 >> 1) & 2147483647L);
		this._6 = (this._6 & -9223372032559808513L) | ((this._6 >> 1) & 9223372032559808512L);
		this._7 = (this._7 & -2147483648L) | ((this._7 >> 1) & 2147483647L);
		this._7 = (this._7 & -9223372032559808513L) | ((this._7 >> 1) & 9223372032559808512L);
	}
	protected void offsetPX1B() {
		this._8 = (this._8 & -2147483648L) | ((this._8 >> 1) & 2147483647L);
		this._8 = (this._8 & -9223372032559808513L) | ((this._8 >> 1) & 9223372032559808512L);
		this._9 = (this._9 & -2147483648L) | ((this._9 >> 1) & 2147483647L);
		this._9 = (this._9 & -9223372032559808513L) | ((this._9 >> 1) & 9223372032559808512L);
		this._10 = (this._10 & -2147483648L) | ((this._10 >> 1) & 2147483647L);
		this._10 = (this._10 & -9223372032559808513L) | ((this._10 >> 1) & 9223372032559808512L);
		this._11 = (this._11 & -2147483648L) | ((this._11 >> 1) & 2147483647L);
		this._11 = (this._11 & -9223372032559808513L) | ((this._11 >> 1) & 9223372032559808512L);
		this._12 = (this._12 & -2147483648L) | ((this._12 >> 1) & 2147483647L);
		this._12 = (this._12 & -9223372032559808513L) | ((this._12 >> 1) & 9223372032559808512L);
		this._13 = (this._13 & -2147483648L) | ((this._13 >> 1) & 2147483647L);
		this._13 = (this._13 & -9223372032559808513L) | ((this._13 >> 1) & 9223372032559808512L);
		this._14 = (this._14 & -2147483648L) | ((this._14 >> 1) & 2147483647L);
		this._14 = (this._14 & -9223372032559808513L) | ((this._14 >> 1) & 9223372032559808512L);
		this._15 = (this._15 & -2147483648L) | ((this._15 >> 1) & 2147483647L);
		this._15 = (this._15 & -9223372032559808513L) | ((this._15 >> 1) & 9223372032559808512L);
	}
	protected void offsetNX4() {
		this.offsetNX4A();
		this.offsetNX4B();
	}
	protected void offsetNX4A() {
		this._0 = (this._0 & -4294967281L) | ((this._0 << 4) & 4294967280L);
		this._0 = (this._0 & 68719476735L) | ((this._0 << 4) & -68719476736L);
		this._1 = (this._1 & -4294967281L) | ((this._1 << 4) & 4294967280L);
		this._1 = (this._1 & 68719476735L) | ((this._1 << 4) & -68719476736L);
		this._2 = (this._2 & -4294967281L) | ((this._2 << 4) & 4294967280L);
		this._2 = (this._2 & 68719476735L) | ((this._2 << 4) & -68719476736L);
		this._3 = (this._3 & -4294967281L) | ((this._3 << 4) & 4294967280L);
		this._3 = (this._3 & 68719476735L) | ((this._3 << 4) & -68719476736L);
		this._4 = (this._4 & -4294967281L) | ((this._4 << 4) & 4294967280L);
		this._4 = (this._4 & 68719476735L) | ((this._4 << 4) & -68719476736L);
		this._5 = (this._5 & -4294967281L) | ((this._5 << 4) & 4294967280L);
		this._5 = (this._5 & 68719476735L) | ((this._5 << 4) & -68719476736L);
		this._6 = (this._6 & -4294967281L) | ((this._6 << 4) & 4294967280L);
		this._6 = (this._6 & 68719476735L) | ((this._6 << 4) & -68719476736L);
		this._7 = (this._7 & -4294967281L) | ((this._7 << 4) & 4294967280L);
		this._7 = (this._7 & 68719476735L) | ((this._7 << 4) & -68719476736L);
	}
	protected void offsetNX4B() {
		this._8 = (this._8 & -4294967281L) | ((this._8 << 4) & 4294967280L);
		this._8 = (this._8 & 68719476735L) | ((this._8 << 4) & -68719476736L);
		this._9 = (this._9 & -4294967281L) | ((this._9 << 4) & 4294967280L);
		this._9 = (this._9 & 68719476735L) | ((this._9 << 4) & -68719476736L);
		this._10 = (this._10 & -4294967281L) | ((this._10 << 4) & 4294967280L);
		this._10 = (this._10 & 68719476735L) | ((this._10 << 4) & -68719476736L);
		this._11 = (this._11 & -4294967281L) | ((this._11 << 4) & 4294967280L);
		this._11 = (this._11 & 68719476735L) | ((this._11 << 4) & -68719476736L);
		this._12 = (this._12 & -4294967281L) | ((this._12 << 4) & 4294967280L);
		this._12 = (this._12 & 68719476735L) | ((this._12 << 4) & -68719476736L);
		this._13 = (this._13 & -4294967281L) | ((this._13 << 4) & 4294967280L);
		this._13 = (this._13 & 68719476735L) | ((this._13 << 4) & -68719476736L);
		this._14 = (this._14 & -4294967281L) | ((this._14 << 4) & 4294967280L);
		this._14 = (this._14 & 68719476735L) | ((this._14 << 4) & -68719476736L);
		this._15 = (this._15 & -4294967281L) | ((this._15 << 4) & 4294967280L);
		this._15 = (this._15 & 68719476735L) | ((this._15 << 4) & -68719476736L);
	}
	protected void offsetNX2() {
		this.offsetNX2A();
		this.offsetNX2B();
	}
	protected void offsetNX2A() {
		this._0 = (this._0 & -4294967293L) | ((this._0 << 2) & 4294967292L);
		this._0 = (this._0 & 17179869183L) | ((this._0 << 2) & -17179869184L);
		this._1 = (this._1 & -4294967293L) | ((this._1 << 2) & 4294967292L);
		this._1 = (this._1 & 17179869183L) | ((this._1 << 2) & -17179869184L);
		this._2 = (this._2 & -4294967293L) | ((this._2 << 2) & 4294967292L);
		this._2 = (this._2 & 17179869183L) | ((this._2 << 2) & -17179869184L);
		this._3 = (this._3 & -4294967293L) | ((this._3 << 2) & 4294967292L);
		this._3 = (this._3 & 17179869183L) | ((this._3 << 2) & -17179869184L);
		this._4 = (this._4 & -4294967293L) | ((this._4 << 2) & 4294967292L);
		this._4 = (this._4 & 17179869183L) | ((this._4 << 2) & -17179869184L);
		this._5 = (this._5 & -4294967293L) | ((this._5 << 2) & 4294967292L);
		this._5 = (this._5 & 17179869183L) | ((this._5 << 2) & -17179869184L);
		this._6 = (this._6 & -4294967293L) | ((this._6 << 2) & 4294967292L);
		this._6 = (this._6 & 17179869183L) | ((this._6 << 2) & -17179869184L);
		this._7 = (this._7 & -4294967293L) | ((this._7 << 2) & 4294967292L);
		this._7 = (this._7 & 17179869183L) | ((this._7 << 2) & -17179869184L);
	}
	protected void offsetNX2B() {
		this._8 = (this._8 & -4294967293L) | ((this._8 << 2) & 4294967292L);
		this._8 = (this._8 & 17179869183L) | ((this._8 << 2) & -17179869184L);
		this._9 = (this._9 & -4294967293L) | ((this._9 << 2) & 4294967292L);
		this._9 = (this._9 & 17179869183L) | ((this._9 << 2) & -17179869184L);
		this._10 = (this._10 & -4294967293L) | ((this._10 << 2) & 4294967292L);
		this._10 = (this._10 & 17179869183L) | ((this._10 << 2) & -17179869184L);
		this._11 = (this._11 & -4294967293L) | ((this._11 << 2) & 4294967292L);
		this._11 = (this._11 & 17179869183L) | ((this._11 << 2) & -17179869184L);
		this._12 = (this._12 & -4294967293L) | ((this._12 << 2) & 4294967292L);
		this._12 = (this._12 & 17179869183L) | ((this._12 << 2) & -17179869184L);
		this._13 = (this._13 & -4294967293L) | ((this._13 << 2) & 4294967292L);
		this._13 = (this._13 & 17179869183L) | ((this._13 << 2) & -17179869184L);
		this._14 = (this._14 & -4294967293L) | ((this._14 << 2) & 4294967292L);
		this._14 = (this._14 & 17179869183L) | ((this._14 << 2) & -17179869184L);
		this._15 = (this._15 & -4294967293L) | ((this._15 << 2) & 4294967292L);
		this._15 = (this._15 & 17179869183L) | ((this._15 << 2) & -17179869184L);
	}
	protected void offsetNX1() {
		this.offsetNX1A();
		this.offsetNX1B();
	}
	protected void offsetNX1A() {
		this._0 = (this._0 & -4294967295L) | ((this._0 << 1) & 4294967294L);
		this._0 = (this._0 & 8589934591L) | ((this._0 << 1) & -8589934592L);
		this._1 = (this._1 & -4294967295L) | ((this._1 << 1) & 4294967294L);
		this._1 = (this._1 & 8589934591L) | ((this._1 << 1) & -8589934592L);
		this._2 = (this._2 & -4294967295L) | ((this._2 << 1) & 4294967294L);
		this._2 = (this._2 & 8589934591L) | ((this._2 << 1) & -8589934592L);
		this._3 = (this._3 & -4294967295L) | ((this._3 << 1) & 4294967294L);
		this._3 = (this._3 & 8589934591L) | ((this._3 << 1) & -8589934592L);
		this._4 = (this._4 & -4294967295L) | ((this._4 << 1) & 4294967294L);
		this._4 = (this._4 & 8589934591L) | ((this._4 << 1) & -8589934592L);
		this._5 = (this._5 & -4294967295L) | ((this._5 << 1) & 4294967294L);
		this._5 = (this._5 & 8589934591L) | ((this._5 << 1) & -8589934592L);
		this._6 = (this._6 & -4294967295L) | ((this._6 << 1) & 4294967294L);
		this._6 = (this._6 & 8589934591L) | ((this._6 << 1) & -8589934592L);
		this._7 = (this._7 & -4294967295L) | ((this._7 << 1) & 4294967294L);
		this._7 = (this._7 & 8589934591L) | ((this._7 << 1) & -8589934592L);
	}
	protected void offsetNX1B() {
		this._8 = (this._8 & -4294967295L) | ((this._8 << 1) & 4294967294L);
		this._8 = (this._8 & 8589934591L) | ((this._8 << 1) & -8589934592L);
		this._9 = (this._9 & -4294967295L) | ((this._9 << 1) & 4294967294L);
		this._9 = (this._9 & 8589934591L) | ((this._9 << 1) & -8589934592L);
		this._10 = (this._10 & -4294967295L) | ((this._10 << 1) & 4294967294L);
		this._10 = (this._10 & 8589934591L) | ((this._10 << 1) & -8589934592L);
		this._11 = (this._11 & -4294967295L) | ((this._11 << 1) & 4294967294L);
		this._11 = (this._11 & 8589934591L) | ((this._11 << 1) & -8589934592L);
		this._12 = (this._12 & -4294967295L) | ((this._12 << 1) & 4294967294L);
		this._12 = (this._12 & 8589934591L) | ((this._12 << 1) & -8589934592L);
		this._13 = (this._13 & -4294967295L) | ((this._13 << 1) & 4294967294L);
		this._13 = (this._13 & 8589934591L) | ((this._13 << 1) & -8589934592L);
		this._14 = (this._14 & -4294967295L) | ((this._14 << 1) & 4294967294L);
		this._14 = (this._14 & 8589934591L) | ((this._14 << 1) & -8589934592L);
		this._15 = (this._15 & -4294967295L) | ((this._15 << 1) & 4294967294L);
		this._15 = (this._15 & 8589934591L) | ((this._15 << 1) & -8589934592L);
	}

	public void offsetY(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {
		this.offsetPY4A();
	}
	protected void offsetPY4A() {
		this._2 = (this._2 & 0L) | (this._0 & -1L);
		this._3 = (this._3 & 0L) | (this._1 & -1L);
		this._4 = (this._4 & 0L) | (this._2 & -1L);
		this._5 = (this._5 & 0L) | (this._3 & -1L);
		this._6 = (this._6 & 0L) | (this._4 & -1L);
		this._7 = (this._7 & 0L) | (this._5 & -1L);
		this._8 = (this._8 & 0L) | (this._6 & -1L);
		this._9 = (this._9 & 0L) | (this._7 & -1L);
		this._10 = (this._10 & 0L) | (this._8 & -1L);
		this._11 = (this._11 & 0L) | (this._9 & -1L);
		this._12 = (this._12 & 0L) | (this._10 & -1L);
		this._13 = (this._13 & 0L) | (this._11 & -1L);
		this._14 = (this._14 & 0L) | (this._12 & -1L);
		this._15 = (this._15 & 0L) | (this._13 & -1L);
	}
	protected void offsetPY2() {
		this.offsetPY2A();
	}
	protected void offsetPY2A() {
		this._1 = (this._1 & 0L) | (this._0 & -1L);
		this._2 = (this._2 & 0L) | (this._1 & -1L);
		this._3 = (this._3 & 0L) | (this._2 & -1L);
		this._4 = (this._4 & 0L) | (this._3 & -1L);
		this._5 = (this._5 & 0L) | (this._4 & -1L);
		this._6 = (this._6 & 0L) | (this._5 & -1L);
		this._7 = (this._7 & 0L) | (this._6 & -1L);
		this._8 = (this._8 & 0L) | (this._7 & -1L);
		this._9 = (this._9 & 0L) | (this._8 & -1L);
		this._10 = (this._10 & 0L) | (this._9 & -1L);
		this._11 = (this._11 & 0L) | (this._10 & -1L);
		this._12 = (this._12 & 0L) | (this._11 & -1L);
		this._13 = (this._13 & 0L) | (this._12 & -1L);
		this._14 = (this._14 & 0L) | (this._13 & -1L);
		this._15 = (this._15 & 0L) | (this._14 & -1L);
	}
	protected void offsetPY1() {
		this.offsetPY1A();
		this.offsetPY1B();
	}
	protected void offsetPY1A() {
		this._1 = (this._1 & -4294967296L) | ((this._0 >> 32) & 4294967295L);
		this._1 = (this._1 & 4294967295L) | ((this._1 << 32) & -4294967296L);
		this._2 = (this._2 & -4294967296L) | ((this._1 >> 32) & 4294967295L);
		this._2 = (this._2 & 4294967295L) | ((this._2 << 32) & -4294967296L);
		this._3 = (this._3 & -4294967296L) | ((this._2 >> 32) & 4294967295L);
		this._3 = (this._3 & 4294967295L) | ((this._3 << 32) & -4294967296L);
		this._4 = (this._4 & -4294967296L) | ((this._3 >> 32) & 4294967295L);
		this._4 = (this._4 & 4294967295L) | ((this._4 << 32) & -4294967296L);
		this._5 = (this._5 & -4294967296L) | ((this._4 >> 32) & 4294967295L);
		this._5 = (this._5 & 4294967295L) | ((this._5 << 32) & -4294967296L);
		this._6 = (this._6 & -4294967296L) | ((this._5 >> 32) & 4294967295L);
		this._6 = (this._6 & 4294967295L) | ((this._6 << 32) & -4294967296L);
		this._7 = (this._7 & -4294967296L) | ((this._6 >> 32) & 4294967295L);
		this._7 = (this._7 & 4294967295L) | ((this._7 << 32) & -4294967296L);
		this._8 = (this._8 & -4294967296L) | ((this._7 >> 32) & 4294967295L);
		this._8 = (this._8 & 4294967295L) | ((this._8 << 32) & -4294967296L);
	}
	protected void offsetPY1B() {
		this._9 = (this._9 & -4294967296L) | ((this._8 >> 32) & 4294967295L);
		this._9 = (this._9 & 4294967295L) | ((this._9 << 32) & -4294967296L);
		this._10 = (this._10 & -4294967296L) | ((this._9 >> 32) & 4294967295L);
		this._10 = (this._10 & 4294967295L) | ((this._10 << 32) & -4294967296L);
		this._11 = (this._11 & -4294967296L) | ((this._10 >> 32) & 4294967295L);
		this._11 = (this._11 & 4294967295L) | ((this._11 << 32) & -4294967296L);
		this._12 = (this._12 & -4294967296L) | ((this._11 >> 32) & 4294967295L);
		this._12 = (this._12 & 4294967295L) | ((this._12 << 32) & -4294967296L);
		this._13 = (this._13 & -4294967296L) | ((this._12 >> 32) & 4294967295L);
		this._13 = (this._13 & 4294967295L) | ((this._13 << 32) & -4294967296L);
		this._14 = (this._14 & -4294967296L) | ((this._13 >> 32) & 4294967295L);
		this._14 = (this._14 & 4294967295L) | ((this._14 << 32) & -4294967296L);
		this._15 = (this._15 & -4294967296L) | ((this._14 >> 32) & 4294967295L);
	}
	protected void offsetNY4() {
		this.offsetNY4A();
	}
	protected void offsetNY4A() {
		this._0 = (this._0 & 0L) | (this._2 & -1L);
		this._1 = (this._1 & 0L) | (this._3 & -1L);
		this._2 = (this._2 & 0L) | (this._4 & -1L);
		this._3 = (this._3 & 0L) | (this._5 & -1L);
		this._4 = (this._4 & 0L) | (this._6 & -1L);
		this._5 = (this._5 & 0L) | (this._7 & -1L);
		this._6 = (this._6 & 0L) | (this._8 & -1L);
		this._7 = (this._7 & 0L) | (this._9 & -1L);
		this._8 = (this._8 & 0L) | (this._10 & -1L);
		this._9 = (this._9 & 0L) | (this._11 & -1L);
		this._10 = (this._10 & 0L) | (this._12 & -1L);
		this._11 = (this._11 & 0L) | (this._13 & -1L);
		this._12 = (this._12 & 0L) | (this._14 & -1L);
		this._13 = (this._13 & 0L) | (this._15 & -1L);
	}
	protected void offsetNY2() {
		this.offsetNY2A();
	}
	protected void offsetNY2A() {
		this._0 = (this._0 & 0L) | (this._1 & -1L);
		this._1 = (this._1 & 0L) | (this._2 & -1L);
		this._2 = (this._2 & 0L) | (this._3 & -1L);
		this._3 = (this._3 & 0L) | (this._4 & -1L);
		this._4 = (this._4 & 0L) | (this._5 & -1L);
		this._5 = (this._5 & 0L) | (this._6 & -1L);
		this._6 = (this._6 & 0L) | (this._7 & -1L);
		this._7 = (this._7 & 0L) | (this._8 & -1L);
		this._8 = (this._8 & 0L) | (this._9 & -1L);
		this._9 = (this._9 & 0L) | (this._10 & -1L);
		this._10 = (this._10 & 0L) | (this._11 & -1L);
		this._11 = (this._11 & 0L) | (this._12 & -1L);
		this._12 = (this._12 & 0L) | (this._13 & -1L);
		this._13 = (this._13 & 0L) | (this._14 & -1L);
		this._14 = (this._14 & 0L) | (this._15 & -1L);
	}
	protected void offsetNY1() {
		this.offsetNY1A();
		this.offsetNY1B();
	}
	protected void offsetNY1A() {
		this._0 = (this._0 & 4294967295L) | ((this._1 << 32) & -4294967296L);
		this._1 = (this._1 & -4294967296L) | ((this._1 >> 32) & 4294967295L);
		this._1 = (this._1 & 4294967295L) | ((this._2 << 32) & -4294967296L);
		this._2 = (this._2 & -4294967296L) | ((this._2 >> 32) & 4294967295L);
		this._2 = (this._2 & 4294967295L) | ((this._3 << 32) & -4294967296L);
		this._3 = (this._3 & -4294967296L) | ((this._3 >> 32) & 4294967295L);
		this._3 = (this._3 & 4294967295L) | ((this._4 << 32) & -4294967296L);
		this._4 = (this._4 & -4294967296L) | ((this._4 >> 32) & 4294967295L);
		this._4 = (this._4 & 4294967295L) | ((this._5 << 32) & -4294967296L);
		this._5 = (this._5 & -4294967296L) | ((this._5 >> 32) & 4294967295L);
		this._5 = (this._5 & 4294967295L) | ((this._6 << 32) & -4294967296L);
		this._6 = (this._6 & -4294967296L) | ((this._6 >> 32) & 4294967295L);
		this._6 = (this._6 & 4294967295L) | ((this._7 << 32) & -4294967296L);
		this._7 = (this._7 & -4294967296L) | ((this._7 >> 32) & 4294967295L);
		this._7 = (this._7 & 4294967295L) | ((this._8 << 32) & -4294967296L);
		this._8 = (this._8 & -4294967296L) | ((this._8 >> 32) & 4294967295L);
	}
	protected void offsetNY1B() {
		this._8 = (this._8 & 4294967295L) | ((this._9 << 32) & -4294967296L);
		this._9 = (this._9 & -4294967296L) | ((this._9 >> 32) & 4294967295L);
		this._9 = (this._9 & 4294967295L) | ((this._10 << 32) & -4294967296L);
		this._10 = (this._10 & -4294967296L) | ((this._10 >> 32) & 4294967295L);
		this._10 = (this._10 & 4294967295L) | ((this._11 << 32) & -4294967296L);
		this._11 = (this._11 & -4294967296L) | ((this._11 >> 32) & 4294967295L);
		this._11 = (this._11 & 4294967295L) | ((this._12 << 32) & -4294967296L);
		this._12 = (this._12 & -4294967296L) | ((this._12 >> 32) & 4294967295L);
		this._12 = (this._12 & 4294967295L) | ((this._13 << 32) & -4294967296L);
		this._13 = (this._13 & -4294967296L) | ((this._13 >> 32) & 4294967295L);
		this._13 = (this._13 & 4294967295L) | ((this._14 << 32) & -4294967296L);
		this._14 = (this._14 & -4294967296L) | ((this._14 >> 32) & 4294967295L);
		this._14 = (this._14 & 4294967295L) | ((this._15 << 32) & -4294967296L);
	}

	public void offsetZ(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {

	}

	protected void offsetPZ2() {

	}

	protected void offsetPZ1() {

	}

	protected void offsetNZ4() {

	}

	protected void offsetNZ2() {

	}

	protected void offsetNZ1() {

	}


	public void complement() {
		this.complement0();
	}
	protected void complement0() {
		this._0 = ~this._0;
		this._1 = ~this._1;
		this._2 = ~this._2;
		this._3 = ~this._3;
		this._4 = ~this._4;
		this._5 = ~this._5;
		this._6 = ~this._6;
		this._7 = ~this._7;
		this._8 = ~this._8;
		this._9 = ~this._9;
		this._10 = ~this._10;
		this._11 = ~this._11;
		this._12 = ~this._12;
		this._13 = ~this._13;
		this._14 = ~this._14;
		this._15 = ~this._15;
	}

	public boolean isIntersecting(BitField that0) {
		if(!(that0 instanceof BitField32x32x1))
			return BitField.super.isIntersecting(that0);
		var that = (BitField32x32x1) that0;
		if(this.isIntersecting0(that)) return true;
		return false;
	}
	protected boolean isIntersecting0(BitField32x32x1 that) {
		if((this._0 & that._0) != 0) return true;
		if((this._1 & that._1) != 0) return true;
		if((this._2 & that._2) != 0) return true;
		if((this._3 & that._3) != 0) return true;
		if((this._4 & that._4) != 0) return true;
		if((this._5 & that._5) != 0) return true;
		if((this._6 & that._6) != 0) return true;
		if((this._7 & that._7) != 0) return true;
		if((this._8 & that._8) != 0) return true;
		if((this._9 & that._9) != 0) return true;
		if((this._10 & that._10) != 0) return true;
		if((this._11 & that._11) != 0) return true;
		if((this._12 & that._12) != 0) return true;
		if((this._13 & that._13) != 0) return true;
		if((this._14 & that._14) != 0) return true;
		if((this._15 & that._15) != 0) return true;
		return false;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField32x32x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField32x32x1) that0;
		this.union0(that);
	}
	protected void union0(BitField32x32x1 that) {
		this._0 |= that._0;
		this._1 |= that._1;
		this._2 |= that._2;
		this._3 |= that._3;
		this._4 |= that._4;
		this._5 |= that._5;
		this._6 |= that._6;
		this._7 |= that._7;
		this._8 |= that._8;
		this._9 |= that._9;
		this._10 |= that._10;
		this._11 |= that._11;
		this._12 |= that._12;
		this._13 |= that._13;
		this._14 |= that._14;
		this._15 |= that._15;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField32x32x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField32x32x1) that0;
		this.intersect0(that);
	}
	protected void intersect0(BitField32x32x1 that) {
		this._0 &= that._0;
		this._1 &= that._1;
		this._2 &= that._2;
		this._3 &= that._3;
		this._4 &= that._4;
		this._5 &= that._5;
		this._6 &= that._6;
		this._7 &= that._7;
		this._8 &= that._8;
		this._9 &= that._9;
		this._10 &= that._10;
		this._11 &= that._11;
		this._12 &= that._12;
		this._13 &= that._13;
		this._14 &= that._14;
		this._15 &= that._15;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField32x32x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField32x32x1) that0;
		this.exclusive0(that);
	}
	protected void exclusive0(BitField32x32x1 that) {
		this._0 ^= that._0;
		this._1 ^= that._1;
		this._2 ^= that._2;
		this._3 ^= that._3;
		this._4 ^= that._4;
		this._5 ^= that._5;
		this._6 ^= that._6;
		this._7 ^= that._7;
		this._8 ^= that._8;
		this._9 ^= that._9;
		this._10 ^= that._10;
		this._11 ^= that._11;
		this._12 ^= that._12;
		this._13 ^= that._13;
		this._14 ^= that._14;
		this._15 ^= that._15;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField32x32x1)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField32x32x1) that0;
		this.subtract0(that);
	}
	protected void subtract0(BitField32x32x1 that) {
		this._0 &= ~that._0;
		this._1 &= ~that._1;
		this._2 &= ~that._2;
		this._3 &= ~that._3;
		this._4 &= ~that._4;
		this._5 &= ~that._5;
		this._6 &= ~that._6;
		this._7 &= ~that._7;
		this._8 &= ~that._8;
		this._9 &= ~that._9;
		this._10 &= ~that._10;
		this._11 &= ~that._11;
		this._12 &= ~that._12;
		this._13 &= ~that._13;
		this._14 &= ~that._14;
		this._15 &= ~that._15;
	}
}
