
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045;

public class BitField8x8x8 implements BitField {
	public static final int WIDTH = 8;
	public static final int HEIGHT = 8;
	public static final int DEPTH = 8;
	protected long _0;
	protected long _1;
	protected long _2;
	protected long _3;
	protected long _4;
	protected long _5;
	protected long _6;
	protected long _7;

	public int getWidth() {
		return WIDTH;
	}
	public int getHeight() {
		return HEIGHT;
	}
	public int getDepth() {
		return DEPTH;
	}

	public boolean getValue(int x, int y, int z) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) return this.getValue0(position);
		assert false;
		return false;
	}
	protected boolean getValue0(int position) {
		long mask = 1L << (63 - position % 64);
		if(position < 64) return (this._0 & mask) != 0;
		if(position < 128) return (this._1 & mask) != 0;
		if(position < 192) return (this._2 & mask) != 0;
		if(position < 256) return (this._3 & mask) != 0;
		if(position < 320) return (this._4 & mask) != 0;
		if(position < 384) return (this._5 & mask) != 0;
		if(position < 448) return (this._6 & mask) != 0;
		if(position < 512) return (this._7 & mask) != 0;
		assert false;
		return false;
	}

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue0(position, v); return; }
		assert false;
	}
	protected void setValue0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		if(position < 128) { this._1 = (this._1 & mask) | value; return; }
		if(position < 192) { this._2 = (this._2 & mask) | value; return; }
		if(position < 256) { this._3 = (this._3 & mask) | value; return; }
		if(position < 320) { this._4 = (this._4 & mask) | value; return; }
		if(position < 384) { this._5 = (this._5 & mask) | value; return; }
		if(position < 448) { this._6 = (this._6 & mask) | value; return; }
		if(position < 512) { this._7 = (this._7 & mask) | value; return; }
		assert false;
	}

	public void offsetX(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {
		this.offsetPX4A();
		this.offsetPX4B();
		this.offsetPX4C();
		this.offsetPX4D();
	}
	protected void offsetPX4A() {
		this._0 = (this._0 & -16L) | ((this._0 >> 4) & 15L);
		this._0 = (this._0 & -3841L) | ((this._0 >> 4) & 3840L);
		this._0 = (this._0 & -983041L) | ((this._0 >> 4) & 983040L);
		this._0 = (this._0 & -251658241L) | ((this._0 >> 4) & 251658240L);
		this._0 = (this._0 & -64424509441L) | ((this._0 >> 4) & 64424509440L);
		this._0 = (this._0 & -16492674416641L) | ((this._0 >> 4) & 16492674416640L);
		this._0 = (this._0 & -4222124650659841L) | ((this._0 >> 4) & 4222124650659840L);
		this._0 = (this._0 & -1080863910568919041L) | ((this._0 >> 4) & 1080863910568919040L);
		this._1 = (this._1 & -16L) | ((this._1 >> 4) & 15L);
		this._1 = (this._1 & -3841L) | ((this._1 >> 4) & 3840L);
		this._1 = (this._1 & -983041L) | ((this._1 >> 4) & 983040L);
		this._1 = (this._1 & -251658241L) | ((this._1 >> 4) & 251658240L);
		this._1 = (this._1 & -64424509441L) | ((this._1 >> 4) & 64424509440L);
		this._1 = (this._1 & -16492674416641L) | ((this._1 >> 4) & 16492674416640L);
		this._1 = (this._1 & -4222124650659841L) | ((this._1 >> 4) & 4222124650659840L);
		this._1 = (this._1 & -1080863910568919041L) | ((this._1 >> 4) & 1080863910568919040L);
	}
	protected void offsetPX4B() {
		this._2 = (this._2 & -16L) | ((this._2 >> 4) & 15L);
		this._2 = (this._2 & -3841L) | ((this._2 >> 4) & 3840L);
		this._2 = (this._2 & -983041L) | ((this._2 >> 4) & 983040L);
		this._2 = (this._2 & -251658241L) | ((this._2 >> 4) & 251658240L);
		this._2 = (this._2 & -64424509441L) | ((this._2 >> 4) & 64424509440L);
		this._2 = (this._2 & -16492674416641L) | ((this._2 >> 4) & 16492674416640L);
		this._2 = (this._2 & -4222124650659841L) | ((this._2 >> 4) & 4222124650659840L);
		this._2 = (this._2 & -1080863910568919041L) | ((this._2 >> 4) & 1080863910568919040L);
		this._3 = (this._3 & -16L) | ((this._3 >> 4) & 15L);
		this._3 = (this._3 & -3841L) | ((this._3 >> 4) & 3840L);
		this._3 = (this._3 & -983041L) | ((this._3 >> 4) & 983040L);
		this._3 = (this._3 & -251658241L) | ((this._3 >> 4) & 251658240L);
		this._3 = (this._3 & -64424509441L) | ((this._3 >> 4) & 64424509440L);
		this._3 = (this._3 & -16492674416641L) | ((this._3 >> 4) & 16492674416640L);
		this._3 = (this._3 & -4222124650659841L) | ((this._3 >> 4) & 4222124650659840L);
		this._3 = (this._3 & -1080863910568919041L) | ((this._3 >> 4) & 1080863910568919040L);
	}
	protected void offsetPX4C() {
		this._4 = (this._4 & -16L) | ((this._4 >> 4) & 15L);
		this._4 = (this._4 & -3841L) | ((this._4 >> 4) & 3840L);
		this._4 = (this._4 & -983041L) | ((this._4 >> 4) & 983040L);
		this._4 = (this._4 & -251658241L) | ((this._4 >> 4) & 251658240L);
		this._4 = (this._4 & -64424509441L) | ((this._4 >> 4) & 64424509440L);
		this._4 = (this._4 & -16492674416641L) | ((this._4 >> 4) & 16492674416640L);
		this._4 = (this._4 & -4222124650659841L) | ((this._4 >> 4) & 4222124650659840L);
		this._4 = (this._4 & -1080863910568919041L) | ((this._4 >> 4) & 1080863910568919040L);
		this._5 = (this._5 & -16L) | ((this._5 >> 4) & 15L);
		this._5 = (this._5 & -3841L) | ((this._5 >> 4) & 3840L);
		this._5 = (this._5 & -983041L) | ((this._5 >> 4) & 983040L);
		this._5 = (this._5 & -251658241L) | ((this._5 >> 4) & 251658240L);
		this._5 = (this._5 & -64424509441L) | ((this._5 >> 4) & 64424509440L);
		this._5 = (this._5 & -16492674416641L) | ((this._5 >> 4) & 16492674416640L);
		this._5 = (this._5 & -4222124650659841L) | ((this._5 >> 4) & 4222124650659840L);
		this._5 = (this._5 & -1080863910568919041L) | ((this._5 >> 4) & 1080863910568919040L);
	}
	protected void offsetPX4D() {
		this._6 = (this._6 & -16L) | ((this._6 >> 4) & 15L);
		this._6 = (this._6 & -3841L) | ((this._6 >> 4) & 3840L);
		this._6 = (this._6 & -983041L) | ((this._6 >> 4) & 983040L);
		this._6 = (this._6 & -251658241L) | ((this._6 >> 4) & 251658240L);
		this._6 = (this._6 & -64424509441L) | ((this._6 >> 4) & 64424509440L);
		this._6 = (this._6 & -16492674416641L) | ((this._6 >> 4) & 16492674416640L);
		this._6 = (this._6 & -4222124650659841L) | ((this._6 >> 4) & 4222124650659840L);
		this._6 = (this._6 & -1080863910568919041L) | ((this._6 >> 4) & 1080863910568919040L);
		this._7 = (this._7 & -16L) | ((this._7 >> 4) & 15L);
		this._7 = (this._7 & -3841L) | ((this._7 >> 4) & 3840L);
		this._7 = (this._7 & -983041L) | ((this._7 >> 4) & 983040L);
		this._7 = (this._7 & -251658241L) | ((this._7 >> 4) & 251658240L);
		this._7 = (this._7 & -64424509441L) | ((this._7 >> 4) & 64424509440L);
		this._7 = (this._7 & -16492674416641L) | ((this._7 >> 4) & 16492674416640L);
		this._7 = (this._7 & -4222124650659841L) | ((this._7 >> 4) & 4222124650659840L);
		this._7 = (this._7 & -1080863910568919041L) | ((this._7 >> 4) & 1080863910568919040L);
	}
	protected void offsetPX2() {
		this.offsetPX2A();
		this.offsetPX2B();
		this.offsetPX2C();
		this.offsetPX2D();
	}
	protected void offsetPX2A() {
		this._0 = (this._0 & -64L) | ((this._0 >> 2) & 63L);
		this._0 = (this._0 & -16129L) | ((this._0 >> 2) & 16128L);
		this._0 = (this._0 & -4128769L) | ((this._0 >> 2) & 4128768L);
		this._0 = (this._0 & -1056964609L) | ((this._0 >> 2) & 1056964608L);
		this._0 = (this._0 & -270582939649L) | ((this._0 >> 2) & 270582939648L);
		this._0 = (this._0 & -69269232549889L) | ((this._0 >> 2) & 69269232549888L);
		this._0 = (this._0 & -17732923532771329L) | ((this._0 >> 2) & 17732923532771328L);
		this._0 = (this._0 & -4539628424389459969L) | ((this._0 >> 2) & 4539628424389459968L);
		this._1 = (this._1 & -64L) | ((this._1 >> 2) & 63L);
		this._1 = (this._1 & -16129L) | ((this._1 >> 2) & 16128L);
		this._1 = (this._1 & -4128769L) | ((this._1 >> 2) & 4128768L);
		this._1 = (this._1 & -1056964609L) | ((this._1 >> 2) & 1056964608L);
		this._1 = (this._1 & -270582939649L) | ((this._1 >> 2) & 270582939648L);
		this._1 = (this._1 & -69269232549889L) | ((this._1 >> 2) & 69269232549888L);
		this._1 = (this._1 & -17732923532771329L) | ((this._1 >> 2) & 17732923532771328L);
		this._1 = (this._1 & -4539628424389459969L) | ((this._1 >> 2) & 4539628424389459968L);
	}
	protected void offsetPX2B() {
		this._2 = (this._2 & -64L) | ((this._2 >> 2) & 63L);
		this._2 = (this._2 & -16129L) | ((this._2 >> 2) & 16128L);
		this._2 = (this._2 & -4128769L) | ((this._2 >> 2) & 4128768L);
		this._2 = (this._2 & -1056964609L) | ((this._2 >> 2) & 1056964608L);
		this._2 = (this._2 & -270582939649L) | ((this._2 >> 2) & 270582939648L);
		this._2 = (this._2 & -69269232549889L) | ((this._2 >> 2) & 69269232549888L);
		this._2 = (this._2 & -17732923532771329L) | ((this._2 >> 2) & 17732923532771328L);
		this._2 = (this._2 & -4539628424389459969L) | ((this._2 >> 2) & 4539628424389459968L);
		this._3 = (this._3 & -64L) | ((this._3 >> 2) & 63L);
		this._3 = (this._3 & -16129L) | ((this._3 >> 2) & 16128L);
		this._3 = (this._3 & -4128769L) | ((this._3 >> 2) & 4128768L);
		this._3 = (this._3 & -1056964609L) | ((this._3 >> 2) & 1056964608L);
		this._3 = (this._3 & -270582939649L) | ((this._3 >> 2) & 270582939648L);
		this._3 = (this._3 & -69269232549889L) | ((this._3 >> 2) & 69269232549888L);
		this._3 = (this._3 & -17732923532771329L) | ((this._3 >> 2) & 17732923532771328L);
		this._3 = (this._3 & -4539628424389459969L) | ((this._3 >> 2) & 4539628424389459968L);
	}
	protected void offsetPX2C() {
		this._4 = (this._4 & -64L) | ((this._4 >> 2) & 63L);
		this._4 = (this._4 & -16129L) | ((this._4 >> 2) & 16128L);
		this._4 = (this._4 & -4128769L) | ((this._4 >> 2) & 4128768L);
		this._4 = (this._4 & -1056964609L) | ((this._4 >> 2) & 1056964608L);
		this._4 = (this._4 & -270582939649L) | ((this._4 >> 2) & 270582939648L);
		this._4 = (this._4 & -69269232549889L) | ((this._4 >> 2) & 69269232549888L);
		this._4 = (this._4 & -17732923532771329L) | ((this._4 >> 2) & 17732923532771328L);
		this._4 = (this._4 & -4539628424389459969L) | ((this._4 >> 2) & 4539628424389459968L);
		this._5 = (this._5 & -64L) | ((this._5 >> 2) & 63L);
		this._5 = (this._5 & -16129L) | ((this._5 >> 2) & 16128L);
		this._5 = (this._5 & -4128769L) | ((this._5 >> 2) & 4128768L);
		this._5 = (this._5 & -1056964609L) | ((this._5 >> 2) & 1056964608L);
		this._5 = (this._5 & -270582939649L) | ((this._5 >> 2) & 270582939648L);
		this._5 = (this._5 & -69269232549889L) | ((this._5 >> 2) & 69269232549888L);
		this._5 = (this._5 & -17732923532771329L) | ((this._5 >> 2) & 17732923532771328L);
		this._5 = (this._5 & -4539628424389459969L) | ((this._5 >> 2) & 4539628424389459968L);
	}
	protected void offsetPX2D() {
		this._6 = (this._6 & -64L) | ((this._6 >> 2) & 63L);
		this._6 = (this._6 & -16129L) | ((this._6 >> 2) & 16128L);
		this._6 = (this._6 & -4128769L) | ((this._6 >> 2) & 4128768L);
		this._6 = (this._6 & -1056964609L) | ((this._6 >> 2) & 1056964608L);
		this._6 = (this._6 & -270582939649L) | ((this._6 >> 2) & 270582939648L);
		this._6 = (this._6 & -69269232549889L) | ((this._6 >> 2) & 69269232549888L);
		this._6 = (this._6 & -17732923532771329L) | ((this._6 >> 2) & 17732923532771328L);
		this._6 = (this._6 & -4539628424389459969L) | ((this._6 >> 2) & 4539628424389459968L);
		this._7 = (this._7 & -64L) | ((this._7 >> 2) & 63L);
		this._7 = (this._7 & -16129L) | ((this._7 >> 2) & 16128L);
		this._7 = (this._7 & -4128769L) | ((this._7 >> 2) & 4128768L);
		this._7 = (this._7 & -1056964609L) | ((this._7 >> 2) & 1056964608L);
		this._7 = (this._7 & -270582939649L) | ((this._7 >> 2) & 270582939648L);
		this._7 = (this._7 & -69269232549889L) | ((this._7 >> 2) & 69269232549888L);
		this._7 = (this._7 & -17732923532771329L) | ((this._7 >> 2) & 17732923532771328L);
		this._7 = (this._7 & -4539628424389459969L) | ((this._7 >> 2) & 4539628424389459968L);
	}
	protected void offsetPX1() {
		this.offsetPX1A();
		this.offsetPX1B();
		this.offsetPX1C();
		this.offsetPX1D();
	}
	protected void offsetPX1A() {
		this._0 = (this._0 & -128L) | ((this._0 >> 1) & 127L);
		this._0 = (this._0 & -32513L) | ((this._0 >> 1) & 32512L);
		this._0 = (this._0 & -8323073L) | ((this._0 >> 1) & 8323072L);
		this._0 = (this._0 & -2130706433L) | ((this._0 >> 1) & 2130706432L);
		this._0 = (this._0 & -545460846593L) | ((this._0 >> 1) & 545460846592L);
		this._0 = (this._0 & -139637976727553L) | ((this._0 >> 1) & 139637976727552L);
		this._0 = (this._0 & -35747322042253313L) | ((this._0 >> 1) & 35747322042253312L);
		this._0 = (this._0 & -9151314442816847873L) | ((this._0 >> 1) & 9151314442816847872L);
		this._1 = (this._1 & -128L) | ((this._1 >> 1) & 127L);
		this._1 = (this._1 & -32513L) | ((this._1 >> 1) & 32512L);
		this._1 = (this._1 & -8323073L) | ((this._1 >> 1) & 8323072L);
		this._1 = (this._1 & -2130706433L) | ((this._1 >> 1) & 2130706432L);
		this._1 = (this._1 & -545460846593L) | ((this._1 >> 1) & 545460846592L);
		this._1 = (this._1 & -139637976727553L) | ((this._1 >> 1) & 139637976727552L);
		this._1 = (this._1 & -35747322042253313L) | ((this._1 >> 1) & 35747322042253312L);
		this._1 = (this._1 & -9151314442816847873L) | ((this._1 >> 1) & 9151314442816847872L);
	}
	protected void offsetPX1B() {
		this._2 = (this._2 & -128L) | ((this._2 >> 1) & 127L);
		this._2 = (this._2 & -32513L) | ((this._2 >> 1) & 32512L);
		this._2 = (this._2 & -8323073L) | ((this._2 >> 1) & 8323072L);
		this._2 = (this._2 & -2130706433L) | ((this._2 >> 1) & 2130706432L);
		this._2 = (this._2 & -545460846593L) | ((this._2 >> 1) & 545460846592L);
		this._2 = (this._2 & -139637976727553L) | ((this._2 >> 1) & 139637976727552L);
		this._2 = (this._2 & -35747322042253313L) | ((this._2 >> 1) & 35747322042253312L);
		this._2 = (this._2 & -9151314442816847873L) | ((this._2 >> 1) & 9151314442816847872L);
		this._3 = (this._3 & -128L) | ((this._3 >> 1) & 127L);
		this._3 = (this._3 & -32513L) | ((this._3 >> 1) & 32512L);
		this._3 = (this._3 & -8323073L) | ((this._3 >> 1) & 8323072L);
		this._3 = (this._3 & -2130706433L) | ((this._3 >> 1) & 2130706432L);
		this._3 = (this._3 & -545460846593L) | ((this._3 >> 1) & 545460846592L);
		this._3 = (this._3 & -139637976727553L) | ((this._3 >> 1) & 139637976727552L);
		this._3 = (this._3 & -35747322042253313L) | ((this._3 >> 1) & 35747322042253312L);
		this._3 = (this._3 & -9151314442816847873L) | ((this._3 >> 1) & 9151314442816847872L);
	}
	protected void offsetPX1C() {
		this._4 = (this._4 & -128L) | ((this._4 >> 1) & 127L);
		this._4 = (this._4 & -32513L) | ((this._4 >> 1) & 32512L);
		this._4 = (this._4 & -8323073L) | ((this._4 >> 1) & 8323072L);
		this._4 = (this._4 & -2130706433L) | ((this._4 >> 1) & 2130706432L);
		this._4 = (this._4 & -545460846593L) | ((this._4 >> 1) & 545460846592L);
		this._4 = (this._4 & -139637976727553L) | ((this._4 >> 1) & 139637976727552L);
		this._4 = (this._4 & -35747322042253313L) | ((this._4 >> 1) & 35747322042253312L);
		this._4 = (this._4 & -9151314442816847873L) | ((this._4 >> 1) & 9151314442816847872L);
		this._5 = (this._5 & -128L) | ((this._5 >> 1) & 127L);
		this._5 = (this._5 & -32513L) | ((this._5 >> 1) & 32512L);
		this._5 = (this._5 & -8323073L) | ((this._5 >> 1) & 8323072L);
		this._5 = (this._5 & -2130706433L) | ((this._5 >> 1) & 2130706432L);
		this._5 = (this._5 & -545460846593L) | ((this._5 >> 1) & 545460846592L);
		this._5 = (this._5 & -139637976727553L) | ((this._5 >> 1) & 139637976727552L);
		this._5 = (this._5 & -35747322042253313L) | ((this._5 >> 1) & 35747322042253312L);
		this._5 = (this._5 & -9151314442816847873L) | ((this._5 >> 1) & 9151314442816847872L);
	}
	protected void offsetPX1D() {
		this._6 = (this._6 & -128L) | ((this._6 >> 1) & 127L);
		this._6 = (this._6 & -32513L) | ((this._6 >> 1) & 32512L);
		this._6 = (this._6 & -8323073L) | ((this._6 >> 1) & 8323072L);
		this._6 = (this._6 & -2130706433L) | ((this._6 >> 1) & 2130706432L);
		this._6 = (this._6 & -545460846593L) | ((this._6 >> 1) & 545460846592L);
		this._6 = (this._6 & -139637976727553L) | ((this._6 >> 1) & 139637976727552L);
		this._6 = (this._6 & -35747322042253313L) | ((this._6 >> 1) & 35747322042253312L);
		this._6 = (this._6 & -9151314442816847873L) | ((this._6 >> 1) & 9151314442816847872L);
		this._7 = (this._7 & -128L) | ((this._7 >> 1) & 127L);
		this._7 = (this._7 & -32513L) | ((this._7 >> 1) & 32512L);
		this._7 = (this._7 & -8323073L) | ((this._7 >> 1) & 8323072L);
		this._7 = (this._7 & -2130706433L) | ((this._7 >> 1) & 2130706432L);
		this._7 = (this._7 & -545460846593L) | ((this._7 >> 1) & 545460846592L);
		this._7 = (this._7 & -139637976727553L) | ((this._7 >> 1) & 139637976727552L);
		this._7 = (this._7 & -35747322042253313L) | ((this._7 >> 1) & 35747322042253312L);
		this._7 = (this._7 & -9151314442816847873L) | ((this._7 >> 1) & 9151314442816847872L);
	}
	protected void offsetNX4() {
		this.offsetNX4A();
		this.offsetNX4B();
		this.offsetNX4C();
		this.offsetNX4D();
	}
	protected void offsetNX4A() {
		this._0 = (this._0 & -241L) | ((this._0 << 4) & 240L);
		this._0 = (this._0 & -61441L) | ((this._0 << 4) & 61440L);
		this._0 = (this._0 & -15728641L) | ((this._0 << 4) & 15728640L);
		this._0 = (this._0 & -4026531841L) | ((this._0 << 4) & 4026531840L);
		this._0 = (this._0 & -1030792151041L) | ((this._0 << 4) & 1030792151040L);
		this._0 = (this._0 & -263882790666241L) | ((this._0 << 4) & 263882790666240L);
		this._0 = (this._0 & -67553994410557441L) | ((this._0 << 4) & 67553994410557440L);
		this._0 = (this._0 & 1152921504606846975L) | ((this._0 << 4) & -1152921504606846976L);
		this._1 = (this._1 & -241L) | ((this._1 << 4) & 240L);
		this._1 = (this._1 & -61441L) | ((this._1 << 4) & 61440L);
		this._1 = (this._1 & -15728641L) | ((this._1 << 4) & 15728640L);
		this._1 = (this._1 & -4026531841L) | ((this._1 << 4) & 4026531840L);
		this._1 = (this._1 & -1030792151041L) | ((this._1 << 4) & 1030792151040L);
		this._1 = (this._1 & -263882790666241L) | ((this._1 << 4) & 263882790666240L);
		this._1 = (this._1 & -67553994410557441L) | ((this._1 << 4) & 67553994410557440L);
		this._1 = (this._1 & 1152921504606846975L) | ((this._1 << 4) & -1152921504606846976L);
	}
	protected void offsetNX4B() {
		this._2 = (this._2 & -241L) | ((this._2 << 4) & 240L);
		this._2 = (this._2 & -61441L) | ((this._2 << 4) & 61440L);
		this._2 = (this._2 & -15728641L) | ((this._2 << 4) & 15728640L);
		this._2 = (this._2 & -4026531841L) | ((this._2 << 4) & 4026531840L);
		this._2 = (this._2 & -1030792151041L) | ((this._2 << 4) & 1030792151040L);
		this._2 = (this._2 & -263882790666241L) | ((this._2 << 4) & 263882790666240L);
		this._2 = (this._2 & -67553994410557441L) | ((this._2 << 4) & 67553994410557440L);
		this._2 = (this._2 & 1152921504606846975L) | ((this._2 << 4) & -1152921504606846976L);
		this._3 = (this._3 & -241L) | ((this._3 << 4) & 240L);
		this._3 = (this._3 & -61441L) | ((this._3 << 4) & 61440L);
		this._3 = (this._3 & -15728641L) | ((this._3 << 4) & 15728640L);
		this._3 = (this._3 & -4026531841L) | ((this._3 << 4) & 4026531840L);
		this._3 = (this._3 & -1030792151041L) | ((this._3 << 4) & 1030792151040L);
		this._3 = (this._3 & -263882790666241L) | ((this._3 << 4) & 263882790666240L);
		this._3 = (this._3 & -67553994410557441L) | ((this._3 << 4) & 67553994410557440L);
		this._3 = (this._3 & 1152921504606846975L) | ((this._3 << 4) & -1152921504606846976L);
	}
	protected void offsetNX4C() {
		this._4 = (this._4 & -241L) | ((this._4 << 4) & 240L);
		this._4 = (this._4 & -61441L) | ((this._4 << 4) & 61440L);
		this._4 = (this._4 & -15728641L) | ((this._4 << 4) & 15728640L);
		this._4 = (this._4 & -4026531841L) | ((this._4 << 4) & 4026531840L);
		this._4 = (this._4 & -1030792151041L) | ((this._4 << 4) & 1030792151040L);
		this._4 = (this._4 & -263882790666241L) | ((this._4 << 4) & 263882790666240L);
		this._4 = (this._4 & -67553994410557441L) | ((this._4 << 4) & 67553994410557440L);
		this._4 = (this._4 & 1152921504606846975L) | ((this._4 << 4) & -1152921504606846976L);
		this._5 = (this._5 & -241L) | ((this._5 << 4) & 240L);
		this._5 = (this._5 & -61441L) | ((this._5 << 4) & 61440L);
		this._5 = (this._5 & -15728641L) | ((this._5 << 4) & 15728640L);
		this._5 = (this._5 & -4026531841L) | ((this._5 << 4) & 4026531840L);
		this._5 = (this._5 & -1030792151041L) | ((this._5 << 4) & 1030792151040L);
		this._5 = (this._5 & -263882790666241L) | ((this._5 << 4) & 263882790666240L);
		this._5 = (this._5 & -67553994410557441L) | ((this._5 << 4) & 67553994410557440L);
		this._5 = (this._5 & 1152921504606846975L) | ((this._5 << 4) & -1152921504606846976L);
	}
	protected void offsetNX4D() {
		this._6 = (this._6 & -241L) | ((this._6 << 4) & 240L);
		this._6 = (this._6 & -61441L) | ((this._6 << 4) & 61440L);
		this._6 = (this._6 & -15728641L) | ((this._6 << 4) & 15728640L);
		this._6 = (this._6 & -4026531841L) | ((this._6 << 4) & 4026531840L);
		this._6 = (this._6 & -1030792151041L) | ((this._6 << 4) & 1030792151040L);
		this._6 = (this._6 & -263882790666241L) | ((this._6 << 4) & 263882790666240L);
		this._6 = (this._6 & -67553994410557441L) | ((this._6 << 4) & 67553994410557440L);
		this._6 = (this._6 & 1152921504606846975L) | ((this._6 << 4) & -1152921504606846976L);
		this._7 = (this._7 & -241L) | ((this._7 << 4) & 240L);
		this._7 = (this._7 & -61441L) | ((this._7 << 4) & 61440L);
		this._7 = (this._7 & -15728641L) | ((this._7 << 4) & 15728640L);
		this._7 = (this._7 & -4026531841L) | ((this._7 << 4) & 4026531840L);
		this._7 = (this._7 & -1030792151041L) | ((this._7 << 4) & 1030792151040L);
		this._7 = (this._7 & -263882790666241L) | ((this._7 << 4) & 263882790666240L);
		this._7 = (this._7 & -67553994410557441L) | ((this._7 << 4) & 67553994410557440L);
		this._7 = (this._7 & 1152921504606846975L) | ((this._7 << 4) & -1152921504606846976L);
	}
	protected void offsetNX2() {
		this.offsetNX2A();
		this.offsetNX2B();
		this.offsetNX2C();
		this.offsetNX2D();
	}
	protected void offsetNX2A() {
		this._0 = (this._0 & -253L) | ((this._0 << 2) & 252L);
		this._0 = (this._0 & -64513L) | ((this._0 << 2) & 64512L);
		this._0 = (this._0 & -16515073L) | ((this._0 << 2) & 16515072L);
		this._0 = (this._0 & -4227858433L) | ((this._0 << 2) & 4227858432L);
		this._0 = (this._0 & -1082331758593L) | ((this._0 << 2) & 1082331758592L);
		this._0 = (this._0 & -277076930199553L) | ((this._0 << 2) & 277076930199552L);
		this._0 = (this._0 & -70931694131085313L) | ((this._0 << 2) & 70931694131085312L);
		this._0 = (this._0 & 288230376151711743L) | ((this._0 << 2) & -288230376151711744L);
		this._1 = (this._1 & -253L) | ((this._1 << 2) & 252L);
		this._1 = (this._1 & -64513L) | ((this._1 << 2) & 64512L);
		this._1 = (this._1 & -16515073L) | ((this._1 << 2) & 16515072L);
		this._1 = (this._1 & -4227858433L) | ((this._1 << 2) & 4227858432L);
		this._1 = (this._1 & -1082331758593L) | ((this._1 << 2) & 1082331758592L);
		this._1 = (this._1 & -277076930199553L) | ((this._1 << 2) & 277076930199552L);
		this._1 = (this._1 & -70931694131085313L) | ((this._1 << 2) & 70931694131085312L);
		this._1 = (this._1 & 288230376151711743L) | ((this._1 << 2) & -288230376151711744L);
	}
	protected void offsetNX2B() {
		this._2 = (this._2 & -253L) | ((this._2 << 2) & 252L);
		this._2 = (this._2 & -64513L) | ((this._2 << 2) & 64512L);
		this._2 = (this._2 & -16515073L) | ((this._2 << 2) & 16515072L);
		this._2 = (this._2 & -4227858433L) | ((this._2 << 2) & 4227858432L);
		this._2 = (this._2 & -1082331758593L) | ((this._2 << 2) & 1082331758592L);
		this._2 = (this._2 & -277076930199553L) | ((this._2 << 2) & 277076930199552L);
		this._2 = (this._2 & -70931694131085313L) | ((this._2 << 2) & 70931694131085312L);
		this._2 = (this._2 & 288230376151711743L) | ((this._2 << 2) & -288230376151711744L);
		this._3 = (this._3 & -253L) | ((this._3 << 2) & 252L);
		this._3 = (this._3 & -64513L) | ((this._3 << 2) & 64512L);
		this._3 = (this._3 & -16515073L) | ((this._3 << 2) & 16515072L);
		this._3 = (this._3 & -4227858433L) | ((this._3 << 2) & 4227858432L);
		this._3 = (this._3 & -1082331758593L) | ((this._3 << 2) & 1082331758592L);
		this._3 = (this._3 & -277076930199553L) | ((this._3 << 2) & 277076930199552L);
		this._3 = (this._3 & -70931694131085313L) | ((this._3 << 2) & 70931694131085312L);
		this._3 = (this._3 & 288230376151711743L) | ((this._3 << 2) & -288230376151711744L);
	}
	protected void offsetNX2C() {
		this._4 = (this._4 & -253L) | ((this._4 << 2) & 252L);
		this._4 = (this._4 & -64513L) | ((this._4 << 2) & 64512L);
		this._4 = (this._4 & -16515073L) | ((this._4 << 2) & 16515072L);
		this._4 = (this._4 & -4227858433L) | ((this._4 << 2) & 4227858432L);
		this._4 = (this._4 & -1082331758593L) | ((this._4 << 2) & 1082331758592L);
		this._4 = (this._4 & -277076930199553L) | ((this._4 << 2) & 277076930199552L);
		this._4 = (this._4 & -70931694131085313L) | ((this._4 << 2) & 70931694131085312L);
		this._4 = (this._4 & 288230376151711743L) | ((this._4 << 2) & -288230376151711744L);
		this._5 = (this._5 & -253L) | ((this._5 << 2) & 252L);
		this._5 = (this._5 & -64513L) | ((this._5 << 2) & 64512L);
		this._5 = (this._5 & -16515073L) | ((this._5 << 2) & 16515072L);
		this._5 = (this._5 & -4227858433L) | ((this._5 << 2) & 4227858432L);
		this._5 = (this._5 & -1082331758593L) | ((this._5 << 2) & 1082331758592L);
		this._5 = (this._5 & -277076930199553L) | ((this._5 << 2) & 277076930199552L);
		this._5 = (this._5 & -70931694131085313L) | ((this._5 << 2) & 70931694131085312L);
		this._5 = (this._5 & 288230376151711743L) | ((this._5 << 2) & -288230376151711744L);
	}
	protected void offsetNX2D() {
		this._6 = (this._6 & -253L) | ((this._6 << 2) & 252L);
		this._6 = (this._6 & -64513L) | ((this._6 << 2) & 64512L);
		this._6 = (this._6 & -16515073L) | ((this._6 << 2) & 16515072L);
		this._6 = (this._6 & -4227858433L) | ((this._6 << 2) & 4227858432L);
		this._6 = (this._6 & -1082331758593L) | ((this._6 << 2) & 1082331758592L);
		this._6 = (this._6 & -277076930199553L) | ((this._6 << 2) & 277076930199552L);
		this._6 = (this._6 & -70931694131085313L) | ((this._6 << 2) & 70931694131085312L);
		this._6 = (this._6 & 288230376151711743L) | ((this._6 << 2) & -288230376151711744L);
		this._7 = (this._7 & -253L) | ((this._7 << 2) & 252L);
		this._7 = (this._7 & -64513L) | ((this._7 << 2) & 64512L);
		this._7 = (this._7 & -16515073L) | ((this._7 << 2) & 16515072L);
		this._7 = (this._7 & -4227858433L) | ((this._7 << 2) & 4227858432L);
		this._7 = (this._7 & -1082331758593L) | ((this._7 << 2) & 1082331758592L);
		this._7 = (this._7 & -277076930199553L) | ((this._7 << 2) & 277076930199552L);
		this._7 = (this._7 & -70931694131085313L) | ((this._7 << 2) & 70931694131085312L);
		this._7 = (this._7 & 288230376151711743L) | ((this._7 << 2) & -288230376151711744L);
	}
	protected void offsetNX1() {
		this.offsetNX1A();
		this.offsetNX1B();
		this.offsetNX1C();
		this.offsetNX1D();
	}
	protected void offsetNX1A() {
		this._0 = (this._0 & -255L) | ((this._0 << 1) & 254L);
		this._0 = (this._0 & -65025L) | ((this._0 << 1) & 65024L);
		this._0 = (this._0 & -16646145L) | ((this._0 << 1) & 16646144L);
		this._0 = (this._0 & -4261412865L) | ((this._0 << 1) & 4261412864L);
		this._0 = (this._0 & -1090921693185L) | ((this._0 << 1) & 1090921693184L);
		this._0 = (this._0 & -279275953455105L) | ((this._0 << 1) & 279275953455104L);
		this._0 = (this._0 & -71494644084506625L) | ((this._0 << 1) & 71494644084506624L);
		this._0 = (this._0 & 144115188075855871L) | ((this._0 << 1) & -144115188075855872L);
		this._1 = (this._1 & -255L) | ((this._1 << 1) & 254L);
		this._1 = (this._1 & -65025L) | ((this._1 << 1) & 65024L);
		this._1 = (this._1 & -16646145L) | ((this._1 << 1) & 16646144L);
		this._1 = (this._1 & -4261412865L) | ((this._1 << 1) & 4261412864L);
		this._1 = (this._1 & -1090921693185L) | ((this._1 << 1) & 1090921693184L);
		this._1 = (this._1 & -279275953455105L) | ((this._1 << 1) & 279275953455104L);
		this._1 = (this._1 & -71494644084506625L) | ((this._1 << 1) & 71494644084506624L);
		this._1 = (this._1 & 144115188075855871L) | ((this._1 << 1) & -144115188075855872L);
	}
	protected void offsetNX1B() {
		this._2 = (this._2 & -255L) | ((this._2 << 1) & 254L);
		this._2 = (this._2 & -65025L) | ((this._2 << 1) & 65024L);
		this._2 = (this._2 & -16646145L) | ((this._2 << 1) & 16646144L);
		this._2 = (this._2 & -4261412865L) | ((this._2 << 1) & 4261412864L);
		this._2 = (this._2 & -1090921693185L) | ((this._2 << 1) & 1090921693184L);
		this._2 = (this._2 & -279275953455105L) | ((this._2 << 1) & 279275953455104L);
		this._2 = (this._2 & -71494644084506625L) | ((this._2 << 1) & 71494644084506624L);
		this._2 = (this._2 & 144115188075855871L) | ((this._2 << 1) & -144115188075855872L);
		this._3 = (this._3 & -255L) | ((this._3 << 1) & 254L);
		this._3 = (this._3 & -65025L) | ((this._3 << 1) & 65024L);
		this._3 = (this._3 & -16646145L) | ((this._3 << 1) & 16646144L);
		this._3 = (this._3 & -4261412865L) | ((this._3 << 1) & 4261412864L);
		this._3 = (this._3 & -1090921693185L) | ((this._3 << 1) & 1090921693184L);
		this._3 = (this._3 & -279275953455105L) | ((this._3 << 1) & 279275953455104L);
		this._3 = (this._3 & -71494644084506625L) | ((this._3 << 1) & 71494644084506624L);
		this._3 = (this._3 & 144115188075855871L) | ((this._3 << 1) & -144115188075855872L);
	}
	protected void offsetNX1C() {
		this._4 = (this._4 & -255L) | ((this._4 << 1) & 254L);
		this._4 = (this._4 & -65025L) | ((this._4 << 1) & 65024L);
		this._4 = (this._4 & -16646145L) | ((this._4 << 1) & 16646144L);
		this._4 = (this._4 & -4261412865L) | ((this._4 << 1) & 4261412864L);
		this._4 = (this._4 & -1090921693185L) | ((this._4 << 1) & 1090921693184L);
		this._4 = (this._4 & -279275953455105L) | ((this._4 << 1) & 279275953455104L);
		this._4 = (this._4 & -71494644084506625L) | ((this._4 << 1) & 71494644084506624L);
		this._4 = (this._4 & 144115188075855871L) | ((this._4 << 1) & -144115188075855872L);
		this._5 = (this._5 & -255L) | ((this._5 << 1) & 254L);
		this._5 = (this._5 & -65025L) | ((this._5 << 1) & 65024L);
		this._5 = (this._5 & -16646145L) | ((this._5 << 1) & 16646144L);
		this._5 = (this._5 & -4261412865L) | ((this._5 << 1) & 4261412864L);
		this._5 = (this._5 & -1090921693185L) | ((this._5 << 1) & 1090921693184L);
		this._5 = (this._5 & -279275953455105L) | ((this._5 << 1) & 279275953455104L);
		this._5 = (this._5 & -71494644084506625L) | ((this._5 << 1) & 71494644084506624L);
		this._5 = (this._5 & 144115188075855871L) | ((this._5 << 1) & -144115188075855872L);
	}
	protected void offsetNX1D() {
		this._6 = (this._6 & -255L) | ((this._6 << 1) & 254L);
		this._6 = (this._6 & -65025L) | ((this._6 << 1) & 65024L);
		this._6 = (this._6 & -16646145L) | ((this._6 << 1) & 16646144L);
		this._6 = (this._6 & -4261412865L) | ((this._6 << 1) & 4261412864L);
		this._6 = (this._6 & -1090921693185L) | ((this._6 << 1) & 1090921693184L);
		this._6 = (this._6 & -279275953455105L) | ((this._6 << 1) & 279275953455104L);
		this._6 = (this._6 & -71494644084506625L) | ((this._6 << 1) & 71494644084506624L);
		this._6 = (this._6 & 144115188075855871L) | ((this._6 << 1) & -144115188075855872L);
		this._7 = (this._7 & -255L) | ((this._7 << 1) & 254L);
		this._7 = (this._7 & -65025L) | ((this._7 << 1) & 65024L);
		this._7 = (this._7 & -16646145L) | ((this._7 << 1) & 16646144L);
		this._7 = (this._7 & -4261412865L) | ((this._7 << 1) & 4261412864L);
		this._7 = (this._7 & -1090921693185L) | ((this._7 << 1) & 1090921693184L);
		this._7 = (this._7 & -279275953455105L) | ((this._7 << 1) & 279275953455104L);
		this._7 = (this._7 & -71494644084506625L) | ((this._7 << 1) & 71494644084506624L);
		this._7 = (this._7 & 144115188075855871L) | ((this._7 << 1) & -144115188075855872L);
	}

	public void offsetY(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {
		this.offsetPY4A();
	}
	protected void offsetPY4A() {
		this._0 = (this._0 & -4294967296L) | ((this._0 >> 32) & 4294967295L);
		this._1 = (this._1 & -4294967296L) | ((this._1 >> 32) & 4294967295L);
		this._2 = (this._2 & -4294967296L) | ((this._2 >> 32) & 4294967295L);
		this._3 = (this._3 & -4294967296L) | ((this._3 >> 32) & 4294967295L);
		this._4 = (this._4 & -4294967296L) | ((this._4 >> 32) & 4294967295L);
		this._5 = (this._5 & -4294967296L) | ((this._5 >> 32) & 4294967295L);
		this._6 = (this._6 & -4294967296L) | ((this._6 >> 32) & 4294967295L);
		this._7 = (this._7 & -4294967296L) | ((this._7 >> 32) & 4294967295L);
	}
	protected void offsetPY2() {
		this.offsetPY2A();
	}
	protected void offsetPY2A() {
		this._0 = (this._0 & -281474976710656L) | ((this._0 >> 16) & 281474976710655L);
		this._1 = (this._1 & -281474976710656L) | ((this._1 >> 16) & 281474976710655L);
		this._2 = (this._2 & -281474976710656L) | ((this._2 >> 16) & 281474976710655L);
		this._3 = (this._3 & -281474976710656L) | ((this._3 >> 16) & 281474976710655L);
		this._4 = (this._4 & -281474976710656L) | ((this._4 >> 16) & 281474976710655L);
		this._5 = (this._5 & -281474976710656L) | ((this._5 >> 16) & 281474976710655L);
		this._6 = (this._6 & -281474976710656L) | ((this._6 >> 16) & 281474976710655L);
		this._7 = (this._7 & -281474976710656L) | ((this._7 >> 16) & 281474976710655L);
	}
	protected void offsetPY1() {
		this.offsetPY1A();
	}
	protected void offsetPY1A() {
		this._0 = (this._0 & -72057594037927936L) | ((this._0 >> 8) & 72057594037927935L);
		this._1 = (this._1 & -72057594037927936L) | ((this._1 >> 8) & 72057594037927935L);
		this._2 = (this._2 & -72057594037927936L) | ((this._2 >> 8) & 72057594037927935L);
		this._3 = (this._3 & -72057594037927936L) | ((this._3 >> 8) & 72057594037927935L);
		this._4 = (this._4 & -72057594037927936L) | ((this._4 >> 8) & 72057594037927935L);
		this._5 = (this._5 & -72057594037927936L) | ((this._5 >> 8) & 72057594037927935L);
		this._6 = (this._6 & -72057594037927936L) | ((this._6 >> 8) & 72057594037927935L);
		this._7 = (this._7 & -72057594037927936L) | ((this._7 >> 8) & 72057594037927935L);
	}
	protected void offsetNY4() {
		this.offsetNY4A();
	}
	protected void offsetNY4A() {
		this._0 = (this._0 & 4294967295L) | ((this._0 << 32) & -4294967296L);
		this._1 = (this._1 & 4294967295L) | ((this._1 << 32) & -4294967296L);
		this._2 = (this._2 & 4294967295L) | ((this._2 << 32) & -4294967296L);
		this._3 = (this._3 & 4294967295L) | ((this._3 << 32) & -4294967296L);
		this._4 = (this._4 & 4294967295L) | ((this._4 << 32) & -4294967296L);
		this._5 = (this._5 & 4294967295L) | ((this._5 << 32) & -4294967296L);
		this._6 = (this._6 & 4294967295L) | ((this._6 << 32) & -4294967296L);
		this._7 = (this._7 & 4294967295L) | ((this._7 << 32) & -4294967296L);
	}
	protected void offsetNY2() {
		this.offsetNY2A();
	}
	protected void offsetNY2A() {
		this._0 = (this._0 & 65535L) | ((this._0 << 16) & -65536L);
		this._1 = (this._1 & 65535L) | ((this._1 << 16) & -65536L);
		this._2 = (this._2 & 65535L) | ((this._2 << 16) & -65536L);
		this._3 = (this._3 & 65535L) | ((this._3 << 16) & -65536L);
		this._4 = (this._4 & 65535L) | ((this._4 << 16) & -65536L);
		this._5 = (this._5 & 65535L) | ((this._5 << 16) & -65536L);
		this._6 = (this._6 & 65535L) | ((this._6 << 16) & -65536L);
		this._7 = (this._7 & 65535L) | ((this._7 << 16) & -65536L);
	}
	protected void offsetNY1() {
		this.offsetNY1A();
	}
	protected void offsetNY1A() {
		this._0 = (this._0 & 255L) | ((this._0 << 8) & -256L);
		this._1 = (this._1 & 255L) | ((this._1 << 8) & -256L);
		this._2 = (this._2 & 255L) | ((this._2 << 8) & -256L);
		this._3 = (this._3 & 255L) | ((this._3 << 8) & -256L);
		this._4 = (this._4 & 255L) | ((this._4 << 8) & -256L);
		this._5 = (this._5 & 255L) | ((this._5 << 8) & -256L);
		this._6 = (this._6 & 255L) | ((this._6 << 8) & -256L);
		this._7 = (this._7 & 255L) | ((this._7 << 8) & -256L);
	}

	public void offsetZ(int amount) {
		if(amount > 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {
		this.offsetPZ4A();
	}
	protected void offsetPZ4A() {
		this._4 = (this._4 & 0L) | (this._0 & -1L);
		this._5 = (this._5 & 0L) | (this._1 & -1L);
		this._6 = (this._6 & 0L) | (this._2 & -1L);
		this._7 = (this._7 & 0L) | (this._3 & -1L);
	}
	protected void offsetPZ2() {
		this.offsetPZ2A();
	}
	protected void offsetPZ2A() {
		this._2 = (this._2 & 0L) | (this._0 & -1L);
		this._3 = (this._3 & 0L) | (this._1 & -1L);
		this._4 = (this._4 & 0L) | (this._2 & -1L);
		this._5 = (this._5 & 0L) | (this._3 & -1L);
		this._6 = (this._6 & 0L) | (this._4 & -1L);
		this._7 = (this._7 & 0L) | (this._5 & -1L);
	}
	protected void offsetPZ1() {
		this.offsetPZ1A();
	}
	protected void offsetPZ1A() {
		this._1 = (this._1 & 0L) | (this._0 & -1L);
		this._2 = (this._2 & 0L) | (this._1 & -1L);
		this._3 = (this._3 & 0L) | (this._2 & -1L);
		this._4 = (this._4 & 0L) | (this._3 & -1L);
		this._5 = (this._5 & 0L) | (this._4 & -1L);
		this._6 = (this._6 & 0L) | (this._5 & -1L);
		this._7 = (this._7 & 0L) | (this._6 & -1L);
	}
	protected void offsetNZ4() {
		this.offsetNZ4A();
	}
	protected void offsetNZ4A() {
		this._0 = (this._0 & 0L) | (this._4 & -1L);
		this._1 = (this._1 & 0L) | (this._5 & -1L);
		this._2 = (this._2 & 0L) | (this._6 & -1L);
		this._3 = (this._3 & 0L) | (this._7 & -1L);
	}
	protected void offsetNZ2() {
		this.offsetNZ2A();
	}
	protected void offsetNZ2A() {
		this._0 = (this._0 & 0L) | (this._2 & -1L);
		this._1 = (this._1 & 0L) | (this._3 & -1L);
		this._2 = (this._2 & 0L) | (this._4 & -1L);
		this._3 = (this._3 & 0L) | (this._5 & -1L);
		this._4 = (this._4 & 0L) | (this._6 & -1L);
		this._5 = (this._5 & 0L) | (this._7 & -1L);
	}
	protected void offsetNZ1() {
		this.offsetNZ1A();
	}
	protected void offsetNZ1A() {
		this._0 = (this._0 & 0L) | (this._1 & -1L);
		this._1 = (this._1 & 0L) | (this._2 & -1L);
		this._2 = (this._2 & 0L) | (this._3 & -1L);
		this._3 = (this._3 & 0L) | (this._4 & -1L);
		this._4 = (this._4 & 0L) | (this._5 & -1L);
		this._5 = (this._5 & 0L) | (this._6 & -1L);
		this._6 = (this._6 & 0L) | (this._7 & -1L);
	}

	public void complement() {
		this.complement0();
	}
	protected void complement0() {
		this._0 = ~this._0;
		this._1 = ~this._1;
		this._2 = ~this._2;
		this._3 = ~this._3;
		this._4 = ~this._4;
		this._5 = ~this._5;
		this._6 = ~this._6;
		this._7 = ~this._7;
	}

	public boolean isIntersecting(BitField that0) {
		if(!(that0 instanceof BitField8x8x8))
			return BitField.super.isIntersecting(that0);
		var that = (BitField8x8x8) that0;
		if(this.isIntersecting0(that)) return true;
		return false;
	}
	protected boolean isIntersecting0(BitField8x8x8 that) {
		if((this._0 & that._0) != 0) return true;
		if((this._1 & that._1) != 0) return true;
		if((this._2 & that._2) != 0) return true;
		if((this._3 & that._3) != 0) return true;
		if((this._4 & that._4) != 0) return true;
		if((this._5 & that._5) != 0) return true;
		if((this._6 & that._6) != 0) return true;
		if((this._7 & that._7) != 0) return true;
		return false;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField8x8x8)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x8) that0;
		this.union0(that);
	}
	protected void union0(BitField8x8x8 that) {
		this._0 |= that._0;
		this._1 |= that._1;
		this._2 |= that._2;
		this._3 |= that._3;
		this._4 |= that._4;
		this._5 |= that._5;
		this._6 |= that._6;
		this._7 |= that._7;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField8x8x8)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x8) that0;
		this.intersect0(that);
	}
	protected void intersect0(BitField8x8x8 that) {
		this._0 &= that._0;
		this._1 &= that._1;
		this._2 &= that._2;
		this._3 &= that._3;
		this._4 &= that._4;
		this._5 &= that._5;
		this._6 &= that._6;
		this._7 &= that._7;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField8x8x8)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x8) that0;
		this.exclusive0(that);
	}
	protected void exclusive0(BitField8x8x8 that) {
		this._0 ^= that._0;
		this._1 ^= that._1;
		this._2 ^= that._2;
		this._3 ^= that._3;
		this._4 ^= that._4;
		this._5 ^= that._5;
		this._6 ^= that._6;
		this._7 ^= that._7;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField8x8x8)) {
			BitField.super.union(that0);
			return;
		}
		var that = (BitField8x8x8) that0;
		this.subtract0(that);
	}
	protected void subtract0(BitField8x8x8 that) {
		this._0 &= ~that._0;
		this._1 &= ~that._1;
		this._2 &= ~that._2;
		this._3 &= ~that._3;
		this._4 &= ~that._4;
		this._5 &= ~that._5;
		this._6 &= ~that._6;
		this._7 &= ~that._7;
	}
}
