
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField16x16x1Impl extends BitField16x16x1Impl implements ImmutableBitField {

	public ImmutableBitField16x16x1Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField16x16x1Impl toMutable() {
		var that = new MutableBitField16x16x1Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField16x16x1Impl clone() {
		var that = new ImmutableBitField16x16x1Impl();
		this.clone_0(that);
		return that;
	}
	protected void clone_0(ImmutableBitField16x16x1Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
	}
}
