
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField8x8x8Impl extends BitField8x8x8Impl implements ImmutableBitField {

	public ImmutableBitField8x8x8Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField8x8x8Impl toMutable() {
		var that = new MutableBitField8x8x8Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField8x8x8Impl clone() {
		var that = new ImmutableBitField8x8x8Impl();
		this.clone_0(that);
		return that;
	}
	protected void clone_0(ImmutableBitField8x8x8Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
		that._4 = this._4;
		that._5 = this._5;
		that._6 = this._6;
		that._7 = this._7;
	}
}
