
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField20x20x10Impl extends BitField20x20x10Impl implements ImmutableBitField {

	public ImmutableBitField20x20x10Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField20x20x10Impl toMutable() {
		var that = new MutableBitField20x20x10Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField20x20x10Impl clone() {
		var that = new ImmutableBitField20x20x10Impl();
		this.clone_0(that);
		this.clone_1(that);
		this.clone_2(that);
		this.clone_3(that);
		return that;
	}
	protected void clone_0(ImmutableBitField20x20x10Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
		that._4 = this._4;
		that._5 = this._5;
		that._6 = this._6;
		that._7 = this._7;
		that._8 = this._8;
		that._9 = this._9;
		that._10 = this._10;
		that._11 = this._11;
		that._12 = this._12;
		that._13 = this._13;
		that._14 = this._14;
		that._15 = this._15;
	}
	protected void clone_1(ImmutableBitField20x20x10Impl that) {
		that._16 = this._16;
		that._17 = this._17;
		that._18 = this._18;
		that._19 = this._19;
		that._20 = this._20;
		that._21 = this._21;
		that._22 = this._22;
		that._23 = this._23;
		that._24 = this._24;
		that._25 = this._25;
		that._26 = this._26;
		that._27 = this._27;
		that._28 = this._28;
		that._29 = this._29;
		that._30 = this._30;
		that._31 = this._31;
	}
	protected void clone_2(ImmutableBitField20x20x10Impl that) {
		that._32 = this._32;
		that._33 = this._33;
		that._34 = this._34;
		that._35 = this._35;
		that._36 = this._36;
		that._37 = this._37;
		that._38 = this._38;
		that._39 = this._39;
		that._40 = this._40;
		that._41 = this._41;
		that._42 = this._42;
		that._43 = this._43;
		that._44 = this._44;
		that._45 = this._45;
		that._46 = this._46;
		that._47 = this._47;
	}
	protected void clone_3(ImmutableBitField20x20x10Impl that) {
		that._48 = this._48;
		that._49 = this._49;
		that._50 = this._50;
		that._51 = this._51;
		that._52 = this._52;
		that._53 = this._53;
		that._54 = this._54;
		that._55 = this._55;
		that._56 = this._56;
		that._57 = this._57;
		that._58 = this._58;
		that._59 = this._59;
		that._60 = this._60;
		that._61 = this._61;
		that._62 = this._62;
	}
}
