
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField32x32x1Impl extends BitField32x32x1Impl implements ImmutableBitField {

	public ImmutableBitField32x32x1Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField32x32x1Impl toMutable() {
		var that = new MutableBitField32x32x1Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField32x32x1Impl clone() {
		var that = new ImmutableBitField32x32x1Impl();
		this.clone_0(that);
		return that;
	}
	protected void clone_0(ImmutableBitField32x32x1Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
		that._4 = this._4;
		that._5 = this._5;
		that._6 = this._6;
		that._7 = this._7;
		that._8 = this._8;
		that._9 = this._9;
		that._10 = this._10;
		that._11 = this._11;
		that._12 = this._12;
		that._13 = this._13;
		that._14 = this._14;
		that._15 = this._15;
	}
}
