
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField8x8x1Impl extends BitField8x8x1Impl implements ImmutableBitField {

	public ImmutableBitField8x8x1Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField8x8x1Impl toMutable() {
		var that = new MutableBitField8x8x1Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField8x8x1Impl clone() {
		var that = new ImmutableBitField8x8x1Impl();
		this.clone_0(that);
		return that;
	}
	protected void clone_0(ImmutableBitField8x8x1Impl that) {
		that._0 = this._0;
	}
}
