
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField12x12x12Impl extends BitField12x12x12Impl implements ImmutableBitField {

	public ImmutableBitField12x12x12Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField12x12x12Impl toMutable() {
		var that = new MutableBitField12x12x12Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField12x12x12Impl clone() {
		var that = new ImmutableBitField12x12x12Impl();
		this.clone_0(that);
		this.clone_1(that);
		return that;
	}
	protected void clone_0(ImmutableBitField12x12x12Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
		that._4 = this._4;
		that._5 = this._5;
		that._6 = this._6;
		that._7 = this._7;
		that._8 = this._8;
		that._9 = this._9;
		that._10 = this._10;
		that._11 = this._11;
		that._12 = this._12;
		that._13 = this._13;
		that._14 = this._14;
		that._15 = this._15;
	}
	protected void clone_1(ImmutableBitField12x12x12Impl that) {
		that._16 = this._16;
		that._17 = this._17;
		that._18 = this._18;
		that._19 = this._19;
		that._20 = this._20;
		that._21 = this._21;
		that._22 = this._22;
		that._23 = this._23;
		that._24 = this._24;
		that._25 = this._25;
		that._26 = this._26;
	}
}
