
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class ImmutableBitField20x20x1Impl extends BitField20x20x1Impl implements ImmutableBitField {

	public ImmutableBitField20x20x1Impl toImmutable() {
		return this.clone();
	}

	public MutableBitField20x20x1Impl toMutable() {
		var that = new MutableBitField20x20x1Impl();
		that.set(this);
		return that;
	}

	public ImmutableBitField20x20x1Impl clone() {
		var that = new ImmutableBitField20x20x1Impl();
		this.clone_0(that);
		return that;
	}
	protected void clone_0(ImmutableBitField20x20x1Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
		that._4 = this._4;
		that._5 = this._5;
		that._6 = this._6;
	}
}
