
// Do NOT edit this file. This file was generated.

package io.github.nadhifradityo.stima_tucil1_23045.bitfields;

public class MutableBitField16x16x1Impl extends BitField16x16x1Impl implements MutableBitField {

	public void setValue(int x, int y, int z, boolean v) {
		assert x >= 0 && x < WIDTH;
		assert y >= 0 && y < HEIGHT;
		assert z >= 0 && z < DEPTH;
		int position = z * (HEIGHT * WIDTH) + y * WIDTH + x;
		if(position < 1024) { this.setValue_0(position, v); return; }
		assert false;
	}
	protected void setValue_0(int position, boolean v) {
		long mask = ~(1L << (63 - position % 64));
		long value = v ? 1L << (63 - position % 64) : 0;
		if(position < 64) { this._0 = (this._0 & mask) | value; return; }
		if(position < 128) { this._1 = (this._1 & mask) | value; return; }
		if(position < 192) { this._2 = (this._2 & mask) | value; return; }
		if(position < 256) { this._3 = (this._3 & mask) | value; return; }
		assert false;
	}

	public void set(BitField that0) {
		if(!(that0 instanceof BitField16x16x1Impl)) {
			MutableBitField.super.set(that0);
			return;
		}
		var that = (BitField16x16x1Impl) that0;
		this.set_0(that);
	}
	protected void set_0(BitField16x16x1Impl that) {
		this._0 = that._0;
		this._1 = that._1;
		this._2 = that._2;
		this._3 = that._3;
	}

	public void clear() {
		this.clear_0();
	}
	protected void clear_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}

	public ImmutableBitField16x16x1Impl toImmutable() {
		var that = new ImmutableBitField16x16x1Impl();
		this.toImmutable_0(that);
		return that;
	}
	protected void toImmutable_0(ImmutableBitField16x16x1Impl that) {
		that._0 = this._0;
		that._1 = this._1;
		that._2 = this._2;
		that._3 = this._3;
	}

	public MutableBitField16x16x1Impl toMutable() {
		return this.clone();
	}

	public MutableBitField16x16x1Impl clone() {
		var result = new MutableBitField16x16x1Impl();
		result.set(this);
		return result;
	}

	public void offsetX(int amount) {
		amount = Math.max(-WIDTH, Math.min(WIDTH, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPX1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNX4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNX2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNX1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPX4() {

		this.offsetPX4_0();
	}
	protected void offsetPX4_0() {
		this._0 = (this._0 & -1152657617789587456L) | ((this._0 & -4222189076152336L) >> 4);
		this._1 = (this._1 & -1152657617789587456L) | ((this._1 & -4222189076152336L) >> 4);
		this._2 = (this._2 & -1152657617789587456L) | ((this._2 & -4222189076152336L) >> 4);
		this._3 = (this._3 & -1152657617789587456L) | ((this._3 & -4222189076152336L) >> 4);
		this._0 = this._0 & 1152657617789587455L;
		this._1 = this._1 & 1152657617789587455L;
		this._2 = this._2 & 1152657617789587455L;
		this._3 = this._3 & 1152657617789587455L;
	}
	protected void offsetPX2() {

		this.offsetPX2_0();
	}
	protected void offsetPX2_0() {
		this._0 = (this._0 & -4611474908973580288L) | ((this._0 & -844437815230468L) >> 2);
		this._1 = (this._1 & -4611474908973580288L) | ((this._1 & -844437815230468L) >> 2);
		this._2 = (this._2 & -4611474908973580288L) | ((this._2 & -844437815230468L) >> 2);
		this._3 = (this._3 & -4611474908973580288L) | ((this._3 & -844437815230468L) >> 2);
		this._0 = this._0 & 4611474908973580287L;
		this._1 = this._1 & 4611474908973580287L;
		this._2 = this._2 & 4611474908973580287L;
		this._3 = this._3 & 4611474908973580287L;
	}
	protected void offsetPX1() {

		this.offsetPX1_0();
	}
	protected void offsetPX1_0() {
		this._0 = (this._0 & -9223231297218904064L) | ((this._0 & -281479271743490L) >> 1);
		this._1 = (this._1 & -9223231297218904064L) | ((this._1 & -281479271743490L) >> 1);
		this._2 = (this._2 & -9223231297218904064L) | ((this._2 & -281479271743490L) >> 1);
		this._3 = (this._3 & -9223231297218904064L) | ((this._3 & -281479271743490L) >> 1);
		this._0 = this._0 & 9223231297218904063L;
		this._1 = this._1 & 9223231297218904063L;
		this._2 = this._2 & 9223231297218904063L;
		this._3 = this._3 & 9223231297218904063L;
	}
	protected void offsetNX4() {

		this.offsetNX4_0();
	}
	protected void offsetNX4_0() {
		this._0 = (this._0 & 4222189076152335L) | ((this._0 & 1152657617789587455L) << 4);
		this._1 = (this._1 & 4222189076152335L) | ((this._1 & 1152657617789587455L) << 4);
		this._2 = (this._2 & 4222189076152335L) | ((this._2 & 1152657617789587455L) << 4);
		this._3 = (this._3 & 4222189076152335L) | ((this._3 & 1152657617789587455L) << 4);
		this._0 = this._0 & -4222189076152336L;
		this._1 = this._1 & -4222189076152336L;
		this._2 = this._2 & -4222189076152336L;
		this._3 = this._3 & -4222189076152336L;
	}
	protected void offsetNX2() {

		this.offsetNX2_0();
	}
	protected void offsetNX2_0() {
		this._0 = (this._0 & 844437815230467L) | ((this._0 & 4611474908973580287L) << 2);
		this._1 = (this._1 & 844437815230467L) | ((this._1 & 4611474908973580287L) << 2);
		this._2 = (this._2 & 844437815230467L) | ((this._2 & 4611474908973580287L) << 2);
		this._3 = (this._3 & 844437815230467L) | ((this._3 & 4611474908973580287L) << 2);
		this._0 = this._0 & -844437815230468L;
		this._1 = this._1 & -844437815230468L;
		this._2 = this._2 & -844437815230468L;
		this._3 = this._3 & -844437815230468L;
	}
	protected void offsetNX1() {

		this.offsetNX1_0();
	}
	protected void offsetNX1_0() {
		this._0 = (this._0 & 281479271743489L) | ((this._0 & 9223231297218904063L) << 1);
		this._1 = (this._1 & 281479271743489L) | ((this._1 & 9223231297218904063L) << 1);
		this._2 = (this._2 & 281479271743489L) | ((this._2 & 9223231297218904063L) << 1);
		this._3 = (this._3 & 281479271743489L) | ((this._3 & 9223231297218904063L) << 1);
		this._0 = this._0 & -281479271743490L;
		this._1 = this._1 & -281479271743490L;
		this._2 = this._2 & -281479271743490L;
		this._3 = this._3 & -281479271743490L;
	}

	public void offsetY(int amount) {
		amount = Math.max(-HEIGHT, Math.min(HEIGHT, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPY1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNY4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNY2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNY1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPY4() {

		this.offsetPY4_0();
	}
	protected void offsetPY4_0() {
		this._3 = this._2;
		this._2 = this._1;
		this._1 = this._0;
		this._0 = 0;
	}
	protected void offsetPY2() {

		this.offsetPY2_0();
	}
	protected void offsetPY2_0() {
		this._3 = (this._3 & -4294967296L) | ((this._3 & -4294967296L) >> 32);
		this._3 = (this._3 & 4294967295L) | ((this._2 & 4294967295L) << 32);
		this._2 = (this._2 & -4294967296L) | ((this._2 & -4294967296L) >> 32);
		this._2 = (this._2 & 4294967295L) | ((this._1 & 4294967295L) << 32);
		this._1 = (this._1 & -4294967296L) | ((this._1 & -4294967296L) >> 32);
		this._1 = (this._1 & 4294967295L) | ((this._0 & 4294967295L) << 32);
		this._0 = (this._0 & -4294967296L) | ((this._0 & -4294967296L) >> 32);
		this._0 = this._0 & 4294967295L;
	}
	protected void offsetPY1() {

		this.offsetPY1_0();
	}
	protected void offsetPY1_0() {
		this._3 = (this._3 & -281474976710656L) | ((this._3 & -65536L) >> 16);
		this._3 = (this._3 & 281474976710655L) | ((this._2 & 65535L) << 48);
		this._2 = (this._2 & -281474976710656L) | ((this._2 & -65536L) >> 16);
		this._2 = (this._2 & 281474976710655L) | ((this._1 & 65535L) << 48);
		this._1 = (this._1 & -281474976710656L) | ((this._1 & -65536L) >> 16);
		this._1 = (this._1 & 281474976710655L) | ((this._0 & 65535L) << 48);
		this._0 = (this._0 & -281474976710656L) | ((this._0 & -65536L) >> 16);
		this._0 = this._0 & 281474976710655L;
	}
	protected void offsetNY4() {

		this.offsetNY4_0();
	}
	protected void offsetNY4_0() {
		this._0 = this._1;
		this._1 = this._2;
		this._2 = this._3;
		this._3 = 0;
	}
	protected void offsetNY2() {

		this.offsetNY2_0();
	}
	protected void offsetNY2_0() {
		this._0 = (this._0 & 4294967295L) | ((this._0 & 4294967295L) << 32);
		this._0 = (this._0 & -4294967296L) | ((this._1 & -4294967296L) >> 32);
		this._1 = (this._1 & 4294967295L) | ((this._1 & 4294967295L) << 32);
		this._1 = (this._1 & -4294967296L) | ((this._2 & -4294967296L) >> 32);
		this._2 = (this._2 & 4294967295L) | ((this._2 & 4294967295L) << 32);
		this._2 = (this._2 & -4294967296L) | ((this._3 & -4294967296L) >> 32);
		this._3 = (this._3 & 4294967295L) | ((this._3 & 4294967295L) << 32);
		this._3 = this._3 & -4294967296L;
	}
	protected void offsetNY1() {

		this.offsetNY1_0();
	}
	protected void offsetNY1_0() {
		this._0 = (this._0 & 65535L) | ((this._0 & 281474976710655L) << 16);
		this._0 = (this._0 & -65536L) | ((this._1 & -281474976710656L) >> 48);
		this._1 = (this._1 & 65535L) | ((this._1 & 281474976710655L) << 16);
		this._1 = (this._1 & -65536L) | ((this._2 & -281474976710656L) >> 48);
		this._2 = (this._2 & 65535L) | ((this._2 & 281474976710655L) << 16);
		this._2 = (this._2 & -65536L) | ((this._3 & -281474976710656L) >> 48);
		this._3 = (this._3 & 65535L) | ((this._3 & 281474976710655L) << 16);
		this._3 = this._3 & -65536L;
	}

	public void offsetZ(int amount) {
		amount = Math.max(-DEPTH, Math.min(DEPTH, amount));
		if(amount >= 0) {
			while((amount / 4) > 0) {
				this.offsetPZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetPZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetPZ1();
				amount -= 1;
			}
		} else {
			amount *= -1;
			while((amount / 4) > 0) {
				this.offsetNZ4();
				amount -= 4;
			}
			while((amount / 2) > 0) {
				this.offsetNZ2();
				amount -= 2;
			}
			while((amount / 1) > 0) {
				this.offsetNZ1();
				amount -= 1;
			}
		}
		assert amount == 0;
	}
	protected void offsetPZ4() {

		this.offsetPZ4_0();
	}
	protected void offsetPZ4_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}
	protected void offsetPZ2() {

		this.offsetPZ2_0();
	}
	protected void offsetPZ2_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}
	protected void offsetPZ1() {

		this.offsetPZ1_0();
	}
	protected void offsetPZ1_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}
	protected void offsetNZ4() {

		this.offsetNZ4_0();
	}
	protected void offsetNZ4_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}
	protected void offsetNZ2() {

		this.offsetNZ2_0();
	}
	protected void offsetNZ2_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}
	protected void offsetNZ1() {

		this.offsetNZ1_0();
	}
	protected void offsetNZ1_0() {
		this._0 = 0;
		this._1 = 0;
		this._2 = 0;
		this._3 = 0;
	}

	public void complement() {
		this.complement_0();
	}
	protected void complement_0() {
		this._0 = ~this._0;
		this._1 = ~this._1;
		this._2 = ~this._2;
		this._3 = ~this._3;
	}

	public void union(BitField that0) {
		if(!(that0 instanceof BitField16x16x1Impl)) {
			MutableBitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1Impl) that0;
		this.union_0(that);
	}
	protected void union_0(BitField16x16x1Impl that) {
		this._0 |= that._0;
		this._1 |= that._1;
		this._2 |= that._2;
		this._3 |= that._3;
	}

	public void intersect(BitField that0) {
		if(!(that0 instanceof BitField16x16x1Impl)) {
			MutableBitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1Impl) that0;
		this.intersect_0(that);
	}
	protected void intersect_0(BitField16x16x1Impl that) {
		this._0 &= that._0;
		this._1 &= that._1;
		this._2 &= that._2;
		this._3 &= that._3;
	}

	public void exclusive(BitField that0) {
		if(!(that0 instanceof BitField16x16x1Impl)) {
			MutableBitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1Impl) that0;
		this.exclusive_0(that);
	}
	protected void exclusive_0(BitField16x16x1Impl that) {
		this._0 ^= that._0;
		this._1 ^= that._1;
		this._2 ^= that._2;
		this._3 ^= that._3;
	}

	public void subtract(BitField that0) {
		if(!(that0 instanceof BitField16x16x1Impl)) {
			MutableBitField.super.union(that0);
			return;
		}
		var that = (BitField16x16x1Impl) that0;
		this.subtract_0(that);
	}
	protected void subtract_0(BitField16x16x1Impl that) {
		this._0 &= ~that._0;
		this._1 &= ~that._1;
		this._2 &= ~that._2;
		this._3 &= ~that._3;
	}


}
